### ISSUE TITLE
'spark-submit' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by RafaelFOl** [dotnet/spark#1037]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant
![SAPRK_SUBMIT](https://user-images.githubusercontent.com/33993344/155866442-80fb278e-e3c2-431c-ad17-17a2c9458a88.png)

**Comment by suhsteve** [comment]
@RafaelFOl  You may need to close and reopen your cmd/powershell sessions after you updated your PATH env variables. Also please take a look and follow the suggested steps in https://github.com/dotnet/spark/issues/557 and https://github.com/dotnet/spark/issues/304 .
