### ISSUE TITLE
Unable to get the version since i added env details 

### ISSUE THREAD

**Issue by kr185187** [dotnet/spark#1042]
Problem encountered on https://dotnet.microsoft.com/en-us/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Unable to get the version since i added env details

**Comment by kr185187** [comment]
C:\WINDOWS\system32>spark-submit --version
'spark-submit' is not recognized as an internal or external command,
operable program or batch file.

**Comment by suhsteve** [comment]
You may need to close and reopen your cmd/powershell sessions after you updated your PATH env variables.  Also please take a look and follow the suggested steps in https://github.com/dotnet/spark/issues/557 and https://github.com/dotnet/spark/issues/304 .
