### ISSUE TITLE
Spark; The system cannot find the path specified

### ISSUE THREAD

**Issue by konradcetes** [dotnet/spark#1044]
I have been trying to install spark 3.1.3 for the last few days but I keep getting the same error, 'The system cannot find the path specified". 

I have already read through #557 and #304 but these don't help. I tried with both \bin and without \bin as part of the JAVA_HOME path but neither seem to fix the problem. 
![image](https://user-images.githubusercontent.com/22103554/159364705-9943dfd7-af55-4a2f-aa34-4e0f5c835ea0.png)

**Comment by Habeebah157** [comment]
Did you figure it out?

**Comment by wudanzy** [comment]
I found it didn't block me from using the spark.NET, did it make trouble for you?
