### ISSUE TITLE
Support for spark v3.3.1

### ISSUE THREAD

**Issue by natilivni** [dotnet/spark#1123]
Hello, can we expect support for spark v3.3.1?

**Comment by GeorgeS2019** [comment]
Dec 14 2022: [Azure Synapse Runtime for Apache Spark 3.3 is now in Public Preview](https://techcommunity.microsoft.com/t5/azure-synapse-analytics-blog/azure-synapse-runtime-for-apache-spark-3-3-is-now-in-public/ba-p/3686449)

Apache Spark to version **3.3.1** 
Delta Lake to version **2.1.0**.

**Comment by dcosta91** [comment]
Hey, 

We also require this package to support 3.3.
We are using it on Cloudera CDH-7.1.8, which has Spark version 3.3.2.
We are able to run our apps using Spark 2, but when trying to migrate to Spark3 we get this error:
`User class threw exception: java.lang.IllegalArgumentException: Unsupported spark version used: '3.3.2.3.3.7180.12-5'. Normalized spark version used: '3.3.2'. Supported spark major.minor version: '3.2'.`

Thanks a lot!

**Comment by GeorgeS2019** [comment]
@dcosta91 
https://github.com/dotnet/spark/pull/1150

**Comment by wudanzy** [comment]
Fixed by #1194
