### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by varanasitarun** [dotnet/spark#1148]
**Describe the bug**

**To Reproduce**

If you think the bug depends on external factors (e.g., dataset), please provide us with a minimal reproducible example that consists of the following items:

- a minimal dataset, necessary to reproduce the error
- the minimal runnable code necessary to reproduce the error, which can be run on the given dataset
- the necessary information on any used packages, .NET runtime version, and system it is run on
- in the case of random processes, a seed for reproducibility

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

![Bug](https://user-images.githubusercontent.com/45089160/233894320-1bf2a006-88de-4af7-ad77-5f583ed04141.PNG)
Still facing the same issue

**Additional context**

**Comment by dbeavon** [comment]
@varanasitarun 
Can you close?

I think this was accidentally submitted in the wrong repo.  This repo is only for .Net developers of Spark.

**Comment by wudanzy** [comment]
Seems not related.
