### ISSUE TITLE
Calling Scala Functions from .NET for Spark 

### ISSUE THREAD

**Issue by Ragavenderan** [dotnet/spark#115]
We have some prebuilt Jars ( Scala methods to query data from HDInsight). 
How can we call these methods from .Net for Spark API ?

**Comment by rapoth** [comment]
@Ragavenderan: Thanks for raising this! Can you give us a sample Scala method and how you intend to use it within Spark?

**Comment by Ragavenderan** [comment]
Currently we have a jar file that contains the  function definitions. 
From pyspark - this is how we call the method - 

from pyspark.sql import SparkSession, DataFrame
def load_curated_email(spark, category, startdate="", enddate="", location=""):
    
    df = spark._jvm.com.microsoft.odinml.Extractor.loadCuratedEmail(spark._jsparkSession, category, startdate, enddate, location)
    return DataFrame(df, spark)

**Comment by imback82** [comment]
The proper way to do this to introduce new datasource such that you can do:

```C#
var df = spark.Read().Format("your_format_here").Option("startdate","something").Load();
```
Have you considered this option?

Otherwise, we don't have a plan to support calling Scala methods from .NET other than `RegisterJava` for UDF [here](https://github.com/dotnet/spark/blob/35048c9cfa324336497055d6543fa46b8d2de247/src/csharp/Microsoft.Spark/Sql/UDFRegistration.cs#L230).

**Comment by garyyang2002** [comment]
Hi @imback82 
I assume the UDF can only be used in spark sql, right?
The scenario Raga shared is to call a scala method to return a DataFrame as the python code shows, since we don't want to duplicate the logic in C#, is there any way to achieve this goal?

**Comment by rapoth** [comment]
@garyyang2002: Yes, that's correct. 

I'm afraid what you want is not possible by any simple means and is a use case we cannot support immediately. While you can call into regular Java functions through SparkSQL, the use case described here is to call a wrapper function that then invokes spark.read.format().load() which will return a Dataframe. This is a bit unconventional and is not the recommended way – that brings me to the next question – can you share some details regarding the loadCuratedEmail()? How complex would it be to write this one function in .NET?

**Comment by imback82** [comment]
The workaround is to use https://github.com/aelij/IgnoresAccessChecksToGenerator to access some internal classes (but this is not recommended since internal classes can break APIs).
