### ISSUE TITLE
Why I try to run  GetConnection(), It will throw Exception?

### ISSUE THREAD

**Issue by robyle** [dotnet/spark#116]
I'm a new user for dotnet spark.  When I run the Examples,The code run to \src\csharp\Microsoft.Spark\Interop\Ipc\JvmBridge.cs  ，on line 171, it will be throw a exception.
Anyone can help me ?  I don't know how to continue .

![spark-problem](https://user-images.githubusercontent.com/11662528/58085385-351cf080-7bef-11e9-9d09-564fd28ed907.png)

**Comment by imback82** [comment]
Looking at your port, you are running as a debug mode. Can you make sure your are following https://github.com/dotnet/spark/blob/master/docs/developer-guide.md?

**Comment by robyle** [comment]
![ok_spark](https://user-images.githubusercontent.com/11662528/58146630-82e63700-7c89-11e9-8b04-08ba6f06c194.jpg)
yes, I trys ok now,  Thinks.  I 'm a new dotnet sparker ,  Can you give me some learning tips for spark?

**Comment by imback82** [comment]
You can try our [samples](https://github.com/dotnet/spark#samples) to get familiar with .NET experience and there are many tutorials on Spark on the web.

**Comment by robyle** [comment]
> You can try our [samples](https://github.com/dotnet/spark#samples) to get familiar with .NET experience and there are many tutorials on Spark on the web.

OK，Thank you.
