### ISSUE TITLE
[FEATURE REQUEST]: IsIn

### ISSUE THREAD

**Issue by borgdylan** [dotnet/spark#118]
IsIn operator is not available on column as is available on the Scala API. Is it possible to add it?

**Comment by imback82** [comment]
```Scala
def isin(list: Any*):
```
The current implementation of `JvmBridge` (C#) and `DotnetBackendHandler` (Scala) doesn't support passing `IEnumerable<object>` (somewhat equivalent to `Any*` in Scala), thus `isin` didn't make it to the `Column`'s public APIs. Any help would be appreciated to extend `JvmBridge` and `DotnetBackendHandler`.

**Comment by borgdylan** [comment]
Wouldn't it possible to pass an array/list, not necessarily any IEnumerable. IsIn is important for queries and it is not ideal to force people to use UDFs for this.

**Comment by imback82** [comment]
It's actually the "Any" type inside array/list/ienumerable that's not supported, not array/list/IEnumerable of a known Type.

What's the type you are passing here, Column, or something else? Depending on use cases, we could expose `Colulmn[]` and `string[]` first.

**Comment by borgdylan** [comment]
Column[] would be priortity nr. 1, folowed by string[].

**Comment by borgdylan** [comment]
I do not have any use cases in mind that use anything other than those.

**Comment by imback82** [comment]
@borgdylan Looking into this further, the arguments should be literals like `int[]`, `string[]`, etc. instead of `Column[]`. Am I missing something? Do you have an use case where you need to pass Column here?

**Comment by borgdylan** [comment]
For the majority of cases those should be enough. However, there may be join cases that use ```In()``` where the list coulld be retrieved from a query, hence having support for ```Column[]``` would be a nice plus.
