### ISSUE TITLE
[FEATURE REQUEST]:

### ISSUE THREAD

**Issue by SoumyadipYT-OSS** [dotnet/spark#1184]
Apache spark with .NET 8 LTS. Can students contribute in the Apache Spark for .NET Environment?

**Comment by grazy27** [comment]
Implemented in https://github.com/dotnet/spark/pull/1178

**Comment by wudanzy** [comment]
Thanks Ihor (@grazy27), then let's close this issue.

**Comment by SoumyadipYT-OSS** [comment]
What is new issue is going on in this repository? If I can solve it.

**Comment by wudanzy** [comment]
Hi @SoumyadipYT-OSS, thanks for offering the help! We would like to remove the support for spark 2.4. It would be great if you can make that happen! Besides, you can browse the issues and see if there's any thing interesting to you.
