### ISSUE TITLE
[BUG]: spark.streaming.stopGracefullyOnShutdown not working for the dotnet spark worker

### ISSUE THREAD

**Issue by VettelCao** [dotnet/spark#1190]
**Describe the bug**
I set `spark.streaming.stopGracefullyOnShutdown` to true when submitting the dotnet spark application locally, but it seems not working.

**To Reproduce**

1. A dotnet spark application, which is mainly like ![Image](https://github.com/user-attachments/assets/b4a0228d-a5cc-4357-9f17-964d990a496c)
It read data from kafka input topic, does some simple transformation, and then write to another kafka output topic.

2. Execute the spark-submit in Windows system:
`spark-submit --conf spark.streaming.stopGracefullyOnShutdown=true --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.2.1 --class org.apache.spark.deploy.dotnet.DotnetRunner --master local microsoft-spark-3-2_2.12-2.1.1.jar dotnet xxxxxxxx.dll`

3. Sending messages to kafka input topic continuously

4. Stop the spark application by `CTRL C` when it's processing a batch.

5. The spark application stops immediately, and the batch is processed partially. After restart the spark application, it will re-process this batch, so I will get some duplicated data in the kafka output topic.
 
**Expected behavior**
The spark application would stop until the batch is processed completely.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
The dotnet version is net6.0.

**Comment by VettelCao** [comment]
Or is there any other way to ensure the processing batch would be finished completely when stop the app in a normal way? Thanks very much:)

**Comment by wudanzy** [comment]
Hi @VettelCao , have you tried this using Scala Spark? Since Spark.NET wraps over Scala Spark, it is better to know whether it is in Spark or Spark.NET.

**Comment by VettelCao** [comment]
Ah, it seems I got the wrong way to test this.
If I use spark-submit `--master spark://{host}:{port}` instead of `--master local`, and kill the application through the master web like this:![Image](https://github.com/user-attachments/assets/515518d7-cd18-4ab0-a26c-e59192fb723a)
, the working batch would be finished:)
