### ISSUE TITLE
[FEATURE REQUEST]: Automate build drops for MacOS

### ISSUE THREAD

**Issue by rapoth** [dotnet/spark#132]
**Is your feature request related to a problem? Please describe.**
We do not publish binaries for MacOS today nor do we check if the build passes.

**Describe the solution you'd like**
It would be great if Azure Pipelines had a way to output binary drops for MacOS.

**Comment by rapoth** [comment]
CC: @imback82 @suhsteve

**Comment by imback82** [comment]
Closed by #133.
