### ISSUE TITLE
Getting Started doc - missing info about HADOOP_HOME

### ISSUE THREAD

**Issue by AAATechGuy** [dotnet/spark#136]
Without HADOOP_HOME set, we receive exception 
```IOException: (null) entry in command string: null chmod 0644”? [duplicate]```

See issue at https://stackoverflow.com/questions/48010634/why-does-spark-application-fail-with-ioexception-null-entry-in-command-strin?noredirect=1

This is not documented at https://github.com/dotnet/spark/blob/master/docs/building/windows-instructions.md

We need to download binaries from https://github.com/srccodes/hadoop-common-2.2.0-bin to HADOOP_HOME.

**Comment by imback82** [comment]
Looks like it's hidden inside "Click to see sample console output", we will update the doc to be more visible.

**Comment by suhsteve** [comment]
Addressed in PR #134
