### ISSUE TITLE
Is there a plan to implement dotnet for Flink?

### ISSUE THREAD

**Issue by aioloswong** [dotnet/spark#137]
There are more and more Internet companies Like Alibaba, Tencent, Baidu change their big data computing engine from Spark to Flink. I want to know that is there a plan to implement dotnet for Flink in dotnet foundation.

**Comment by imback82** [comment]
@aioloswong currently, there is no plan to expose .NET bindings to Flink.

**Comment by imback82** [comment]
Closing this since there is no plan to support Flink at the moment.

**Comment by kingreatwill** [comment]
Lonely project
https://github.com/justmine66/FLink.CSharp
