### ISSUE TITLE
Assembly Loading Best Practices

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#138]
Revisit the `LoadAssembly` method used in UdfSerDe.cs .  Explore alternative approach to loading assemblies.  Instead of using `Assembly.LoadFrom`, consider `AssemblyLoadContext`

[Best Practices for Assembly Loading](https://docs.microsoft.com/en-us/dotnet/framework/deployment/best-practices-for-assembly-loading)

[MSBuild Example](https://github.com/microsoft/msbuild/blob/fc10ea8ce260b764bb9fa5033b327af9fefcaabe/src/Shared/TaskEngineAssemblyResolver.cs#L127)

**Comment by imback82** [comment]
Closed by #135.
