### ISSUE TITLE
Support custom worker path

### ISSUE THREAD

**Issue by danny8002** [dotnet/spark#140]
consider the following use case:

Assume .net framework C# project (HelloWord)  will output helloword.exe which use Spark.Net. 

1) the Hello Worker c# project has a lot of dependencies 
2) when submit job to Spark with YARN:
   

- by nature,  use spark-submit with --files. as you know, --files will have long arguments, also maybe we will forget some files. 

- pack our project output as zip file, eg.  helloworld.zip 

`    spark-submit  xxxx --files hdfs://xxxx/helloword.zip  hdfs://xxx/microsoft-spark-2.3.x-0.2.0.jar helloworld.zip   helloword.exe  param_0`

  in this solution, Spark.Net (DotnetRunner) will unzip file, then start, but **worker can't get started** because Microsoft.Spark.Worker.exe is in helloword.zip file which is not get decompressed in worker machine.

so in order to let helloworld.zip get decompressed in worker, we can use **--archives** to let spark handle unzip issue. eg. 
`spark-submit  xxxx --archives hdfs://xxxx/helloword.zip  hdfs://xxx/microsoft-spark-2.3.x-0.2.0.jar 
 helloword.zip/helloword.exe param_0`

but worker still failed in starting Microsoft.Spark.Worker.exe because in worker the correct path is 
` (WorkingDirInWorker)/helloword.zip/Microsoft.Spark.Worker.exe`
 instead of 
`(WorkingDirInWorker)/Microsoft.Spark.Worker.exe`

so if **Spark.Net support configure custom worker path**. this can works perfect, 
here is commandline

`spark-submit  xxxx --archives hdfs://xxxx/helloword.zip  hdfs://xxx/microsoft-spark-2.3.x-0.2.0.jar  helloword.zip/helloword.exe param_0   helloword.zip/Microsoft.Spark.Worker.exe`

here is the sudo code

```
public class HelloWorld{
    static void Main(string[] args){
            var param0 = args[0];
            var workerName = args[1];

            // set custom worker path through env 
            Environment.SetEnvironmentVariable("XXX", workerName);

           SparkSession spark=xxxx
           
           spark.Udf().Register<string, string>("test", s=>s);

           // xxxx

    }
}

```

**Comment by imback82** [comment]
Actually I was able to get `--archives worker.zip` working by doing on HDInsight (Linux)
```shell
export DOTNET_WORKER_DIR=./worker.zip
```

Did you try this? I tried this with the code in the master (commit 972825c)

**Comment by imback82** [comment]
Closing this since this is supported by `DOTNET_WORKER_DIR`.
