### ISSUE TITLE
Error in calling UDF for structured streaming

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#149]
I am getting below error, when i try to call a udf on the structured streaming from event hub on azure databricks.
 
It works when a remove the call to UDF.

`var inStream = spark.ReadStream()
			.Format("eventhubs")
			.Option("eventhubs.connectionString", "Endpoint=string")
			.Option("maxeventspertrigger", 5)
			.Load();

Func<Column, Column> ToJsonMessage= Microsoft.Spark.Sql.Functions.Udf<ArraySegment<byte>, string>((arg) => return Encoding.UTF8.GetString(arg));
	
var final = inStream.Select(ToJsonMessage(Microsoft.Spark.Sql.Functions.Col("Body")));

final.WriteStream()
	.OutputMode("append")
	.Format("console")
	.Option("truncate", false)
	.Start()
	.AwaitTermination();
`

if i just remove call to UDF it works
`var final = inStream.Select(Microsoft.Spark.Sql.Functions.Col("Body"))`.

Attach is error i get
[stderr (1).txt](https://github.com/dotnet/spark/files/3308422/stderr.1.txt)

**Comment by imback82** [comment]
```
File name: '/usr/local/bin/spark-dotnet/Microsoft.Spark.Worker-0.3.0/EHStreamConsumer.dll'
```
Can you submit this dll via --files option?

**Comment by suhsteve** [comment]
Most of the assembly file not found exceptions should be resolved if you upload them to dbfs and pass them in with either --files (if using the `spark-submit`) or run the db-init.sh script (if using the `Set Jar` job submission).


This link should help.
https://github.com/dotnet/spark/blob/master/deployment/README.md#run-your-app-on-the-cloud-2

**Comment by guruvonline** [comment]
yes,  it solved issue.
