### ISSUE TITLE
Debugging demo "StructuredNetworkWordCount"，An error：[JvmBridge] Connection refused 127.0.0.1:5567

### ISSUE THREAD

**Issue by wxzz** [dotnet/spark#157]
When I used vscode for debugging, an error occurred : [Exception] [JvmBridge] Connection refused 127.0.0.1:5567。

> Exception has occurred: CLR/System.Net.Internals.SocketExceptionFactory.ExtendedSocketException
“System.Net.Internals.SocketExceptionFactory.ExtendedSocketException”类型的未经处理的异常在 Microsoft.Spark.dll 中发生 : 'Connection refused'
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   在 Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr, Int32 port, String secret)
   在 Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
   在 Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   在 Microsoft.Spark.Sql.Builder..ctor()
   在 Microsoft.Spark.Sql.SparkSession.Builder()
   在 HelloSpark.Program.Main(String[] args) 在 /home/wxzz/workspace/HelloSpark/Program.cs 中: 第 24 行

>     private const string DotnetBackendPortEnvVarName = "DOTNETBACKEND_PORT";
        private const int DotnetBackendDebugPort = 5567;

What is DotnetBackendDebugPort for.......？？？

**Comment by rknidzam** [comment]
Hi, how do you fix this problem?
