### ISSUE TITLE
Debugging demo "StructuredNetworkWordCount"，An error：[JvmBridge] Connection refused 127.0.0.1:5567 

### ISSUE THREAD

**Issue by wxzz** [dotnet/spark#158]
When I used vscode for debugging, an error occurred : [Exception] [JvmBridge] Connection refused 127.0.0.1:5567。

>   Exception has occurred: CLR/System.Net.Internals.SocketExceptionFactory.ExtendedSocketException
>     “System.Net.Internals.SocketExceptionFactory.ExtendedSocketException”类型的未经处理的异常在 Microsoft.Spark.dll 中发生 : 'Connection refused'
>     在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
>     在 System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
>     在 Microsoft.Spark.Network.DefaultSocketWrapper.Connect(IPAddress remoteaddr, Int32 port, String secret)
>     在 Microsoft.Spark.Interop.Ipc.JvmBridge.GetConnection()
>     在 Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
>     在 Microsoft.Spark.Sql.Builder..ctor()
>     在 Microsoft.Spark.Sql.SparkSession.Builder()
>     在 HelloSpark.Program.Main(String[] args) 在 /home/wxzz/workspace/HelloSpark/Program.cs 中: 第 24 行
> 

   source code:
```
    private const string DotnetBackendPortEnvVarName = "DOTNETBACKEND_PORT";
    private const int DotnetBackendDebugPort = 5567;
```

What is DotnetBackendDebugPort for.......？？？

**Comment by rapoth** [comment]
It is for starting the Spark scala side of .NET that allows you to debug. Have you tried the instructions from the [Developer Guide](https://github.com/dotnet/spark/blob/master/docs/developer-guide.md)?

**Comment by wxzz** [comment]
Sorry, where is the Developer Guide? spark-submit has passed, vscode debug exception

 
---Original---

**Comment by wxzz** [comment]
Thanks, find the Developer Guide? I try！



 
---Original---

**Comment by wxzz** [comment]
Thanks, find the Developer Guide！！！！i try！！！

 
---Original---

**Comment by rapoth** [comment]
Great, I'm closing this issue. Please feel free to open another issue if you run into any issues.
