### ISSUE TITLE
RowNumber() function not supported

### ISSUE THREAD

**Issue by huruixd** [dotnet/spark#159]
When adding a RowNumber column to a dataframe, it says unsupported operation.

df.WithColumn("X", RowNumber()).Show();

![image](https://user-images.githubusercontent.com/6639896/60376959-2df3ba00-99c7-11e9-9047-2fedd4ac40a9.png)

**Comment by rapoth** [comment]
@huruixd: 

By including

```csharp
using Microsoft.Spark.Sql;
using static Microsoft.Spark.Sql.Functions;
using static Microsoft.Spark.Sql.Expressions.Window;
```
and using an `Over()`

```csharp
df.WithColumn("col-name", RowNumber().Over(PartitionBy()));
```

Does this work for you?

**Comment by huruixd** [comment]
Thanks!
