### ISSUE TITLE
Microsoft.Spark.Worker executable not found in Azure Databricks

### ISSUE THREAD

**Issue by TomChalkerApption** [dotnet/spark#173]
An issue occurs with the Databricks “Deploy Microsoft.Spark.Worker” section in
[https://github.com/dotnet/spark/tree/master/deployment](https://github.com/dotnet/spark/tree/master/deployment)

1. bash scripts **db-init.sh**, **install-worker.sh** are uploaded to the DBFS file system
2. install-worker.sh uses two Linux commands **wget** and **basename** that are not installed on the cluster VMs
3. Cluster creation fails when based on this init script
4. Script is simplified as follows to avoid **wget** and **basename**
5. Cluster is created successfully with simplified script
6. Processing of a uploaded jar of Microsoft Spark (using **Set JAR**) executes and produces output until first .Net UDF
7. Job fails, logs report: java.io.IOException: Cannot run program "**Microsoft.Spark.Worker**": error=2, No such file or directory

**Simplified script**: (all commands verified by running locally through Python OS shell execution in Workspace)

      cd /usr/local/bin
      tar xzf /dbfs/spark-dotnet/Microsoft.Spark.Worker.netcoreapp2.1.linux-x64-0.3.0.tar.gz -C ./
      sudo chmod 755 Microsoft.Spark.Worker-0.3.0/Microsoft.Spark.Worker
      sudo ln -sf Microsoft.Spark.Worker-0.3.0/Microsoft.Spark.Worker Microsoft.Spark.Worker

8. Tried adding the following to simplified script:

        DOTNET_SPARK_WORKER_INSTALLATION_PATH = "/usr/local/bin"
        export DOTNET_SPARK_WORKER_INSTALLATION_PATH
and, alternatively:

        DotnetWorkerPath = "/usr/local/bin"
        export DotnetWorkerPath

as well as:

        DOTNET_WORKER_DIR = "/usr/local/bin"
        export DOTNET_WORKER_DIR

Still fails at .Show() after:

        spark.Udf().Register<int?, string, string>(
            "my_udf",
            (age, name) => name + " with " + ((age.HasValue) ? age.Value.ToString() : "null"));

        sqlDf = spark.Sql("SELECT my_udf(*) FROM people");
        sqlDf.Show();
Please advise on how this should be done.

(Also added to doc: [https://github.com/dotnet/docs/issues/13326](https://github.com/dotnet/docs/issues/13326) )

**Comment by imback82** [comment]
@suhsteve can you help?

**Comment by imback82** [comment]
@TomChalkerApption can you check `db-init.sh` and `install-worker.sh`'s line endings are LF, not CRLF?

**Comment by TomChalkerApption** [comment]
Hello Terry:

They were LF only. The install.worker script ran to completion once I commented out the ‘basename’ and ‘wget’ commands.
However, I had to modify the script (as indicated) to replace the wget functionality with a file copy from /dbfs/ .

Regards,

Tom Chalker
Senior Developer
Apption
1600 Scott Str, Suite 400, Ottawa
613 725 6268 Ext 612

**Comment by suhsteve** [comment]
I've just tried running a simple example with a udf using Microsoft.Spark 0.3.0 on Microsoft Azure Databricks.  When creating the cluster, I chose `Databricks Runtime Version : 5.3 (Scala 2.11, Spark 2.4.1)`.  Can you tell me which Databricks Runtime version you chose when creating your cluster ?

Also in  a scala notebook can you run the following commands and let me know what the outputs were?

```scala
import sys.process._
"which wget".!
"which basename".!
"lsb_release -a".!
```

**Comment by TomChalkerApption** [comment]
Hello Steve:

I used the default cluster runtime version ‘5.3 (includes Apache Spark 2.4.1, Scala 2.11)’

Result of scala query:
/usr/bin/wget 
/usr/bin/basename 
Distributor ID: Ubuntu
Description: Ubuntu 16.04.6 LTS 
Release: 16.04 
Codename: xenial 
No LSB modules are available. 
import sys.process._ 
res0: Int = 0

I see that wget, basename do exist in /usr/bin

Trying again using your original db-init (configured for https://github.com/dotnet/spark/releases/download/v0.3.0/Microsoft.Spark.Worker.netcoreapp2.1.linux-x64-0.3.0.tar.gz) and original install-worker.sh also produces a partial run which breaks at the .Net UDF:

Standard output:

      +---+----+
      |age|name|
      +---+----+
      | 30|Andy|
      +---+----+

      +----+--------+--------+------------------------+
      | age|avg(age)|avg(age)|count(DISTINCT age, age)|
      +----+--------+--------+------------------------+
      |  19|    19.0|    19.0|                       1|
      |null|    null|    null|                       0|
      |  30|    30.0|    30.0|                       1|
      +----+--------+--------+------------------------+

      +----+-------+
      | age|   name|
      +----+-------+
      |null|Michael|
      |  30|   Andy|
      |  19| Justin|
      +----+-------+

       [2019-07-16T14:05:25.9681993Z] [0716-135314-chose143-10-139-64-7] [Error] [JvmBridge] JVM method execution failed: Nonstatic method showString failed for class 39       when called with 3 arguments ([Index=1, Type=Int32, Value=20], [Index=2, Type=Int32, Value=20], [Index=3, Type=Boolean, Value=False], )
       [2019-07-16T14:05:25.9683226Z] [0716-135314-chose143-10-139-64-7] [Error] [JvmBridge] org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 16.0 failed 4 times, most recent failure: Lost task 0.3 in stage 16.0 (TID 210, 10.139.64.4, executor 1): org.apache.spark.api.python.PythonException: System.IO.FileNotFoundException: Could not load file or assembly '/usr/local/bin/spark-dotnet/Microsoft.Spark.Worker-0.3.0/HelloSpark.dll'. The system cannot find the file specified.

      File name: '/usr/local/bin/spark-dotnet/Microsoft.Spark.Worker-0.3.0/HelloSpark.dll'
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)


The .Net assembly “HelloSpark.dll” is in my HelloSpark.zip (produced by a Linux zip command) in the /dbfs/app/ directory. It must be found as it produces the partial user output shown above. I have tried recompiling and publishing it as netcore3.0, netcore2.2 and netcore2.1 and obtained the same result.

My SetJar settings are: 
      Task: org.apache.spark.deploy.DotnetRunner in microsoft_spark_2_4_x_0_3_0.jar - Edit / Upload JAR / Remove
 Parameters Edit
 Main Class: org.apache.spark.deploy.DotnetRunner
 Arguments: ["/dbfs/apps/HelloSpark.zip","HelloSpark","dbfs:/FileStore/tables/people.json"]
 Dependent Libraries: Add

Any advice on next steps?

Regards,

Tom Chalker
Senior Developer
Apption
1600 Scott Str, Suite 400, Ottawa
613 725 6268 Ext 612

**Comment by imback82** [comment]
Did you follow steps here: https://github.com/dotnet/spark/blob/master/deployment/README.md to upload assemblies that contain your UDF? (`#3` under `Publishing your App & Running`)

**Comment by suhsteve** [comment]
The HelloSpark.dll that's contained in the HelloSpark.zip is exposed to the driver.  However the Microsoft.Spark.Worker also requires the HelloSpark.dll because it contains a UDF that the worker needs to run.  This file should either be copied to the working directory of the executor, or the worker's base directory.  The bottom portion of the db-init.sh can be uncommented and it will copy the HelloSpark.dll to the worker's base directory.

**Comment by TomChalkerApption** [comment]
OK. Success. Placing HelloSpark.dll in the /dependency directory and uncommenting db-init.sh worked.

The Set JAR Job reports as 'Failed' on the Jobs panel.
However, I realized that the 'stdout--2019-07-16--20-00' file link in Clusters/"Driver Logs" panel downloaded a file containing the output of a successful run. (The log panels do not reflect this.)

Thanks for your help on this problem.

Would you like me post further details to allow you to correct the Set JAR  Job status?

**Comment by suhsteve** [comment]
Can you check if your Spark App contains any `SparkSession.Stop()` calls?  Submitting jobs using Set JAR does not support this.

**Comment by TomChalkerApption** [comment]
It did. I have removed it.
The job now runs to success, and the 'standard out' log pane shows the output of the run.

Thanks again for your help
