### ISSUE TITLE
Writing Libraries

### ISSUE THREAD

**Issue by anicolaspp** [dotnet/spark#174]
Hello, 

I wrote part of the [MapR-Database Connector for Apache Spark](https://mapr.com/docs/61/Spark/SparkConnectorsMapRDB.html) and I was wondering how could I write nugget packages with our API to connect, for instance, to an external source so it runs on dotnet. 

our API looks like this: 

```scala
val df: DataFrame = spark.loadFromMapRDB(....)
```

how can we get this functionality written in dotnet? Do we have any doc I can be pointed to?

Best Regards

**Comment by anicolaspp** [comment]
Also, I suppose I need to write a nugget package so it can be added to the dotnet app that is being executed within spark, how can this be done?

**Comment by imback82** [comment]
We don't support writing a new data source in .NET. You can write one in Scala can call into it from .NET.

**Comment by anicolaspp** [comment]
@imback82 we have our data source code already in place in Scala. How do we call it from .NET?

**Comment by imback82** [comment]
What does the Scala API look like?

Can you call in with `DataFrameReader.Format`? If you properly implemented your data source, you should be able to do:
```
var df = spark.Read().Format("your data source name").Load("path here");
```

**Comment by anicolaspp** [comment]
We can certainly do that. Now, how do I link our library from Maven Central on a .NET app?

**Comment by imback82** [comment]
> We can certainly do that. Now, how do I link our library from Maven Central on a .NET app?

I think you can just use `--packages` option in `spark-submit`: https://stackoverflow.com/questions/51434808/spark-submit-packages-vs-jars

> Is there any plans to add the ability to create data sources as nugget packages?

I don't understand this question. Can you elaborate on this?

**Comment by anicolaspp** [comment]
I got it working now. Thanks.

**Comment by imback82** [comment]
Great!
