### ISSUE TITLE
Port spark/examples/src/main/python/sql to C# and verify

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#18]
Python Examples
---
- *python/sql/streaming/**structured_kafka_wordcount.py***
  - [x] CSharp
  - [x] FSharp
- *python/sql/streaming/**structured_network_wordcount.py***
  - [x] CSharp
  - [x] FSharp
- *python/sql/streaming/**structured_network_wordcount_windowed.py***
  - [x] CSharp
  - [x] FSharp
- *python/sql/**arrow.py***
  - [ ] CSharp
  - [ ] FSharp
- *python/sql/**basic.py***
  - [ ] CSharp
  - [ ] FSharp
- *python/sql/**datasource.py***
  - [ ] CSharp
  - [ ] FSharp
- *python/sql/**hive.py***
  - [ ] CSharp
  - [ ] FSharp

**Comment by cesinhaugusto** [comment]
Hi guys. I'm new here. I'd love to contribute to this issue, if it's still open

**Comment by imback82** [comment]
@suhsteve can you check if there are any examples that @cesinhaugusto can help with?

**Comment by imback82** [comment]
@suhsteve can you check if there are any examples we need to port over? Otherwise, let's close this issue.

**Comment by imback82** [comment]
I think all the tests that can be ported are already done. Closing this.
