### ISSUE TITLE
[FEATURE REQUEST]: Use days() in Window.RangeBetween

### ISSUE THREAD

**Issue by deeptowncitizen** [dotnet/spark#181]
I need to execute F.Sum() over Window limited to date (-1 day to -7 days from the F.Col("date")).

From Spark examples I see there should be F.days() function which will generate something e.g.

`RANGE BETWEEN INTERVAL 8 DAYS PRECEDING AND 1 DAYS PRECEDING ROW`

But I don't see any similar wrappers in .Net wrapper. Should it be implemented in a different way?

**Comment by imback82** [comment]
Can you do `Window(Col("data"), "8 days")`? Can you check if https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark/Sql/Functions.cs#L3024 helps?

**Comment by deeptowncitizen** [comment]
I wanted to use it in WindowSpec. The current solution which works well:

```
Window
  .PartitionBy("id")
  .OrderBy(Functions.Col("date").Cast("timestamp").Cast("long"))
  .RangeBetween((int64)((-7)*60*60*24), (int64)((-1)*60*60*24))
```

**Comment by carlitosborja** [comment]
What if there is missing minutes/secs in the dataframe?? Is there some solution that defines the timestamp range instead of a range of rows???
