### ISSUE TITLE
[FEATURE REQUEST]: Implement MapType in ComplexTypes.cs.

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#185]
The `MapType` in `ComplexTypes.cs` is not implemented: https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark/Sql/Types/ComplexTypes.cs#L81

**Comment by imback82** [comment]
cc: @elvaliu

**Comment by imback82** [comment]
@elvaliuliuliu

**Comment by Citrullinome** [comment]
I will work on this.
