### ISSUE TITLE
Debian9 install documentation casing issue mySparkApp vs MySparkApp

### ISSUE THREAD

**Issue by ymitis** [dotnet/spark#190]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: Linux Debian 9 - x64

In the "Create your app" section the documentation states:

In your terminal, run the following commands: 
`dotnet new console -o mySparkApp
cd mySparkApp
`

Then in the "Run your app" section the documentation states:

In your terminal, run the following commands: 

`dotnet build`

`~/bin/spark-2.4.1-bin-hadoop2.7/bin/spark-submit --class org.apache.spark.deploy.DotnetRunner --master local bin/Debug/netcoreapp2.2/microsoft-spark-2.4.x-0.3.0.jar dotnet bin/Debug/netcoreapp2.2/MySparkApp.dll`

Note that the "M" is uppercase in "MySparkApp.dll"  but lowercase in "dotnet new console -o mySparkApp"

This results in a error:

`~/bin/spark-2.4.1-bin-hadoop2.7/bin/spark-submit --class org.apache.spark.deploy.DotnetRunner --master local bin/Debug/netcoreapp2.2/microsoft-spark-2.4.x-0.3.0.jar dotnet bin/Debug/netcoreapp2.2/MySparkApp.dll`

**Comment by imback82** [comment]
@ymitis thanks for the reporting this.

@asthana86 can you help updating the doc on https://dotnet.microsoft.com?

**Comment by ymitis** [comment]
@asthana86 - I'd be happy to help but I'm not sure what repo this documentation comes from.  I don't see it in this repo and I don't see it in https://github.com/dotnet/docs.

**Comment by rapoth** [comment]
CC: @bamurtaugh

**Comment by bamurtaugh** [comment]
Thanks for bringing this to my attention, I will try to get it updated today/sometime soon this week.

**Comment by bamurtaugh** [comment]
Thanks again for bringing this to our attention, we have now updated the tutorial!

**Comment by imback82** [comment]
Thanks @bamurtaugh
