### ISSUE TITLE
log4j no appenders

### ISSUE THREAD

**Issue by liugaocn** [dotnet/spark#191]
I am using Spark 2.4.3, Microsoft.Spark 0.4.0.  Windows 10. VS 2019.

It used to work fine with :
**spark-submit   --class org.apache.spark.deploy.DotnetRunner   --master local microsoft-spark-2.4.x-0.4.0.jar debug**

but now, it wouldn't. 
First of all, it says microsoft-spark-2.4.x-0.4.0.jar doesn't exit. So I had to use:
**spark-submit   --class org.apache.spark.deploy.DotnetRunner   --master local C:\Users\Gao\source\repos\SparkTest\SparkTest\bin\Debug\microsoft-spark-2.4.x-0.4.0.jar debug**
Then, I get 
**log4j:WARN No appenders could be found for logger (org.apache.spark.deploy.SparkSubmit$$anon$2).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.**

Is there anything I can do to make it work? 
Is it because I didn't install all the .NET frameworks? Or because I don't have .NetCore? 
But this problems seems related to java or spark.

**Comment by jalchr** [comment]
What was your solution ?
I'm facing same issue

**Comment by jalchr** [comment]
Okay solved in here #195  and reading the release notes of 0.4
https://github.com/dotnet/spark/blob/master/docs/release-notes/0.4/release-0.4.md
