### ISSUE TITLE
app debug failing after upgrade to 0.4

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#196]
- i have upgraded to 0.4 and updated DOTNET_WORKER_DIR environment variable to folder having 0.4 dlls.

- updated nuget in my app to 0.4. 

- spark-submit debug starts successfully.

- when i try to start my app in debug fails With message

```Lost task 0.0 in stage 11.0 (TID 24, localhost, executor driver): java.io.IOException: Cannot run program "Microsoft.Spark.Worker.exe": CreateProcess error=2, The system cannot find the file specified```

**Comment by imback82** [comment]
Can you provide more info on the following:

> * spark-submit debug starts successfully.
> * when i try to start my app in debug fails With message

**Comment by liugaocn** [comment]
I just changed my computer, so everything is new. I am using 0.4.0, too. If you just upgraded to 0.4.0, then probably, you should check your system variable, if that still points to your new folder. You know sometimes folder names could be changed.

**Comment by guruvonline** [comment]
i verified the value of DOTNET_WORKER_DIR is correct, it points to dir containing all dlls.

- spark submit shows 
```NET Backend running debug mode. Press enter to exit```

- when i start debugging my app it shows 
```lost task 0.0 in stage 11.0 (TID 24, localhost, executor driver): java.io.IOException: Cannot run program "Microsoft.Spark.Worker.exe": CreateProcess error=2, The system cannot find the file specified```.

pls Let me know what extra information is needed.

**Comment by guruvonline** [comment]
it's working now, probably i missed to restart my powershell window to take latest environment variable values
