### ISSUE TITLE
Getting Problem to set Spark Path in Windows Environment

### ISSUE THREAD

**Issue by rajibmcm** [dotnet/spark#198]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by imback82** [comment]
@rajibmcm can you provide details about the problem you are experiencing?

**Comment by rajibmcm** [comment]
I have resolved the problem
