### ISSUE TITLE
How to preview enumerable row[]

### ISSUE THREAD

**Issue by liugaocn** [dotnet/spark#199]
As my question, how can I preview like printing out enermerable row[], for example:

``df.Head(10);``

I want to have a preview first, in case of wasting of time processing wrong data. 
Besides, if i cannot convert ``df.Head(10);`` to dataframe and re-use it, what is the purpose of providing this API?

**Comment by imback82** [comment]
Did you try `df.Show(10)`?

**Comment by liugaocn** [comment]
Thank you. Yes i know that one. That is only an example. What I meant was how to print out enumerable row[].

**Comment by imback82** [comment]
https://github.com/dotnet/spark/blob/de1bbc02d941f5d5824c0bb2e340940d3ccc14d1/examples/Microsoft.Spark.CSharp.Examples/Sql/Basic.cs#L39-L43

**Comment by imback82** [comment]
Please reopen the issue if your question is not addressed.
