### ISSUE TITLE
Structured steaming read from delta lake

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#204]
i am trying to read stream from [Delta lake](https://docs.azuredatabricks.net/delta/delta-streaming.html). The samples loads the data by specifying path/table name to load API, but in the .net for spark load api doesn't take any parameters. 

How can i read streaming data from Delta Lake.?

**Comment by imback82** [comment]
https://github.com/dotnet/spark/blob/de1bbc02d941f5d5824c0bb2e340940d3ccc14d1/src/csharp/Microsoft.Spark/Sql/DataFrameReader.cs#L117

This doesn't work?

**Comment by guruvonline** [comment]
can i use DataFramReader in StrucutredStreaming? to me it is returning DataStreamReader and DataStreamReader.Load doesn't take any argument.

looks like i can give path as option parameter, below seems to be working
``` spark.ReadStrem().Format("delta").Option("path","/delta/mytable").load();```
