### ISSUE TITLE
Implement IsIn clause

### ISSUE THREAD

**Issue by deeptowncitizen** [dotnet/spark#206]
I want to check whether a value from Column equals to one of static array values
```
Functions.Col("my_col").IsIn(["1", "2", "3])
```
Is there any substitution for this method?

**Comment by imback82** [comment]
You can do
```C#
Functions.Col("my_col").IsIn("1", "2", "3")
```
Note that this change is in master, and not in 0.4.0 release.

Check here:
https://github.com/dotnet/spark/blob/de1bbc02d941f5d5824c0bb2e340940d3ccc14d1/src/csharp/Microsoft.Spark/Sql/Column.cs#L752-L755

**Comment by imback82** [comment]
Please reopen if the answer provided doesn't address your concern.

**Comment by deeptowncitizen** [comment]
I'm using the latest version of the package

> <PackageReference Include="Microsoft.Spark" Version="0.4.0" />

And I don't have such method

**Comment by imback82** [comment]
This feature didn't make it to 0.4.0 release. It will come in the next release. Since it is checked into master, you can build the repo and use it if you need it right away.
