### ISSUE TITLE
[BUG]: UDFs do not work on MacOS

### ISSUE THREAD

**Issue by cosmincatalin** [dotnet/spark#207]
I have a very simple example where UDF's do not seem to work properly on MacOS.
Here is my set-up:

* Environment variable pointing to Spark:
```bash
➜  env | grep DOTNET_WORKER_DIR
DOTNET_WORKER_DIR=/Users/cosmin/lib/Microsoft.Spark.Worker/
```
* Contents of the folder the environment variable is pointing to:
```bash
➜  ls /Users/cosmin/lib/Microsoft.Spark.Worker/
Microsoft.Spark.Worker-0.4.0\Apache.Arrow.dll
Microsoft.Spark.Worker-0.4.0\Microsoft.CSharp.dll
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.Worker
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.Worker.deps.json
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.Worker.dll
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.Worker.pdb
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.Worker.runtimeconfig.json
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.Worker.xml
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.dll
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.pdb
Microsoft.Spark.Worker-0.4.0\Microsoft.Spark.xml
Microsoft.Spark.Worker-0.4.0\Microsoft.VisualBasic.dll
...............
Microsoft.Spark.Worker-0.4.0\libhostpolicy.dylib
Microsoft.Spark.Worker-0.4.0\libmscordaccore.dylib
Microsoft.Spark.Worker-0.4.0\libmscordbi.dylib
Microsoft.Spark.Worker-0.4.0\libsos.dylib
Microsoft.Spark.Worker-0.4.0\mscorlib.dll
Microsoft.Spark.Worker-0.4.0\netstandard.dll
Microsoft.Spark.Worker-0.4.0\sosdocsunix.txt
```
* Program listing
```csharp
using Microsoft.Spark.Sql;

namespace HelloSpark
{
    class Program
    {
        static void Main(string[] args)
        {
            var spark = SparkSession.Builder().GetOrCreate();
	    spark.Udf().Register<string, bool>("MyUDF", (text) => text == "Andy");
            spark.Read().Json("people.json").CreateOrReplaceTempView("people");
	    spark.Sql("SELECT name, MyUDF(name) FROM people").Show();
        }
    }
}
```
* Project file:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Spark" Version="0.4.0" />
  </ItemGroup>

</Project>
```

I run the compiled binary with the following command:
`spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local microsoft-spark-2.4.x-0.4.0.jar dotnet HelloSpark.dll`

I get the following error:
```
[2019-08-13T11:31:38.6919900Z] [osX] [Error] [JvmBridge] org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Lost task 0.0 in stage 1.0 (TID 1, localhost, executor driver): java.io.IOException: Cannot run program "/Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker": error=2, No such file or directory
```

Modifying query in `Program.cs` file from `SELECT name, MyUDF(name) FROM people` to `SELECT name FROM people` results in a successful execution.

I suspect the problem is around how I set the environment variable  or something about the worker, but I just cannot figure out what.

Help is appreciated.

**Comment by imback82** [comment]
Looks like you need to set `DOTNET_WORKER_DIR` to `/Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0`

**Comment by cosmincatalin** [comment]
Doesn't seem to work

```bash
➜  env | grep DOTNET_WORKER_DIR
DOTNET_WORKER_DIR=/Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0
➜  spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local microsoft-spark-2.4.x-0.4.0.jar dotnet HelloSpark.dll
```

outputs:

```
java.io.IOException: Cannot run program "/Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0/Microsoft.Spark.Worker": error=2, No such file or directory
```

Remember, I'm on MacOS. Just to be completely clear, I attach a screen shot of how the Spark Worker folder looks. Name of the folder is on top. The full path you can see at the bottom. Everything in there are files, although they look like a weird "sub-path" thingie.

![Screenshot 2019-08-14 at 11 29 31](https://user-images.githubusercontent.com/525590/63010511-d03c0400-be86-11e9-9548-e60f90e566f8.png)

**Comment by GoEddie** [comment]
Is this because you need to untar the file? Does mac let you browse contents of tar files without having to extract them?

If you fix the sub path thing then I bet it works

**Comment by cosmincatalin** [comment]
There's no untaring. I just had a zip file.
![Screenshot 2019-08-14 at 15 16 23](https://user-images.githubusercontent.com/525590/63023963-7fd49e80-bea6-11e9-9bfb-71c60f740ba9.png)

**Comment by GoEddie** [comment]
hmm, does:

`ls /Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0/Microsoft.Spark.Worker`

work? 

"No such file or directory" isn't normally thrown by anything else?

**Comment by imback82** [comment]
Can you check if you can run
```
/Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0/Microsoft.Spark.Worker
```

If not, can you try
```
chmod +x /Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0/Microsoft.Spark.Worker
```

**Comment by cosmincatalin** [comment]
@GoEddie It does not work
```
➜  ls /Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0/Microsoft.Spark.Worker
ls: /Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0/Microsoft.Spark.Worker: No such file or directory
```

@imback82  I cannot run said path (cannot be found), but I can run the following:
```
➜  /Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker-0.4.0\\Microsoft.Spark.Worker
The application to execute does not exist: '/Users/cosmin/lib/Microsoft.Spark.Worker/Microsoft.Spark.Worker.dll'.
```

Notice the back slashes there.

**Comment by GoEddie** [comment]
You need to get it so that `ls` or running the executable actually works, this isn't a spark thing this is a mac thing.

I would copy the files somewhere else and make sure ls or running work and then reference that path.

**Comment by imback82** [comment]
Looks like there is an issue while generating the zip file. I will update the thread when I find it out the root cause.

**Comment by suhsteve** [comment]
This looks like an issue related to https://github.com/PowerShell/PowerShell/issues/2140 .   I'll take a look

**Comment by cosmincatalin** [comment]
Ok, so workaround until this issue is fixed is to do mass rename using procedure [here](http://osxdaily.com/2015/05/28/batch-rename-files-mac-os-x-finder/) and remove the `Microsoft.Spark.Worker-0.4.0\` part (including the back slash). Point the environment variable to the folder the files are in (`DOTNET_WORKER_DIR`). It will work after this.

**Comment by imback82** [comment]
@cosmincatalin we updated the worker binaries with #209 and they are available here: https://github.com/dotnet/spark/releases/download/v0.4.0/Microsoft.Spark.Worker.netcoreapp2.1.osx-x64-0.4.0.zip

Thanks @suhsteve for quickly fixing this and @GoEddie for helping out!
