### ISSUE TITLE
Connect to Elasticsearch backend from Spark

### ISSUE THREAD

**Issue by gvsrini** [dotnet/spark#212]
I am trying to get this working from .Net code. (It works in my JupyterLab).

But I don't see the API for `format` nor for `option`

```
es_reader = (spark.read
    .format("org.elasticsearch.spark.sql")
    .option("inferSchema", "true")
    .option("es.read.field.as.array.include", "tags")
    .option("es.nodes","myelasticsearchserver:9200")
    .option("es.net.http.auth.user","elastic")
    .option("es.net.http.auth.pass","mypassword")
)
```

Can someone help me get this to work.

**Comment by imback82** [comment]
`Format` and `Option` are available. Check the following example:
https://github.com/dotnet/spark/blob/af05ef25d412fe1443c3de77a0383428c2bf37da/examples/Microsoft.Spark.CSharp.Examples/Sql/Datasource.cs#L50-L60
