### ISSUE TITLE
Have to manually move dll for spark-submit

### ISSUE THREAD

**Issue by bamurtaugh** [dotnet/spark#215]
I'm using the following command to build and run my Spark programs:

`dotnet build`

`spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.4.0.jar dotnet bin\Debug\netcoreapp2.2\mySparkAppAdv.dll`

If I run an app without any UDFs, this works fine. However, if my app contains a UDF, I get the following error: 

`[2019-08-21T20:51:13.6926438Z] [MININT-M0C5UII] [Error] [TaskRunner] [0] ProcessStream() failed with exception: System.IO.FileNotFoundException: Assembly 'mySparkAppAdv, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' file not found: 'mySparkAppAdv.dll'`

When I check the bin\Debug\netcoreapp2.2 path, I find the dll in there. In order to run my program successfully, I end up having to manually copy the dll to my app's general folder after any new build.

What's going wrong? Also, it appears to be able to find the jar file fine in that directory since it doesn't require me to also copy the jar file to the general app's folder.

**Comment by suhsteve** [comment]
@bamurtaugh since you are running `spark-submit` using `--master local` there are two options. You can either:
- Change your current working directory to a location that contains the required dll, ie `cd path\to\mySparkAppAdv\bin\Debug\netcoreapp2.2\` and then run the `spark-submit` command from there.
- Or copy the .dll to the `DOTNET_WORKER_DIR` folder

**Comment by bamurtaugh** [comment]
The third suggestion (setting the `DOTNET_ASSEMBLY_SEARCH_PATHS` env variable) worked for me, thank you! 

Just as another aspect of this question, I had already tried the first suggestion (running `spark-submit` from a location containing the dll) in the past because I thought that would be a straight-forward way to find the dll, but I always just end up with a short series of warnings/error and that's it:

```
<path_to>\mySparkAppAdv\bin\Debug\netcoreapp2.2>spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.4.0.jar dotnet bin\Debug\netcoreapp2.2\mySparkAppAdv.dll
19/08/22 09:22:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/08/22 09:22:47 WARN DependencyUtils: Local jar <path_to>\mySparkAppAdv\bin\Debug\netcoreapp2.2\bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.4.0.jar does not exist, skipping.
19/08/22 09:22:47 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.deploy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/08/22 09:22:47 INFO ShutdownHookManager: Shutdown hook called
19/08/22 09:22:47 INFO ShutdownHookManager: Deleting directory <path_to>\AppData\Local\Temp\spark-78219634-6f8b-4401-ae23-ce66f23154c9
```

Not sure why it wouldn't work/if this is just specific to my machine and setup. But the third suggestion did work, so now I don't have to manually copy over the dll every time I do a new build of my app!

**Comment by imback82** [comment]
Since you are already under `<path_to>\mySparkAppAdv\bin\Debug\netcoreapp2.2`, you can just do `spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local microsoft-spark-2.4.x-0.4.0.jar dotnet mySparkAppAdv.dll`.

Check this `19/08/22 09:22:47 WARN DependencyUtils: Local jar <path_to>\mySparkAppAdv\bin\Debug\netcoreapp2.2\bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.4.0.jar does not exist`

I am closing this, but feel free to reopen if this doesn't solve your issue.
