### ISSUE TITLE
Loading big table from oracle

### ISSUE THREAD

**Issue by topcatarg** [dotnet/spark#216]
I'm trying to get data from an oracle source, But I receive an error like this:

Unhandled Exception: System.Exception: JVM method execution failed: Nonstatic method load failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.Load(String[] paths)
   at BajadaOracle.Program.Main(String[] args) in C:\XXXX\Source\Repos\testspark\BajadaOracle\Program.cs:line
35

Line 35 is the load of the dataframe:

    Console.WriteLine("myversion 1.2");
    // Create a Spark session
    var spark = SparkSession
                .Builder()
                .Config("spark.sql.warehouse.dir", "file:///C:/Datos/spark/warehouse")
                .AppName("Test oracle")
                .GetOrCreate();

    string Query = "select * from table";
    Query = "select 1 from dual";
    Console.Write("paso: 1 Antes de conectarse");
    // Create initial DataFrame
    var dataFrame =
                spark
                .Read()
                //.Option("url","jdbc:oracle:thin:@1.1.1.1:1521:XXXX")
                .Options(new System.Collections.Generic.Dictionary<string, string>()
                {
                    {"url","jdbc:oracle:thin:@1.1.1.1:1521:XXXX" },
                    { "user","XXXXX" },
                    { "password", "XXXXX" },
                    { "query" , Query },
                    { "driver", "oracle.jdbc.driver.OracleDriver" }
                });
            //.Load();
    var Datos = dataFrame.Load();

The instalation of this is local, using the tutorial at https://dotnet.microsoft.com/learn/data/spark-tutorial/run

I added de jdbc driver to the jar folder in spark. and running using the command provided in the tutorial. 

I don't fully understand if the error is the connection (That I know has all the correct data, but don't know is there is a better way to test it from spark) or the load itself. 

If there anything I can do to trace this problem?

**Comment by imback82** [comment]
Can you share the full log?

**Comment by topcatarg** [comment]
19/08/22 12:47:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java
classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/08/22 12:47:40 INFO DotnetRunner: Starting DotnetBackend with dotnet.
19/08/22 12:47:41 INFO DotnetRunner: Port number used by DotnetBackend is 62278
19/08/22 12:47:41 INFO DotnetRunner: Adding key=spark.jars and value=file:/C:/Users/u40497/Source/Repos/testspark/BajadaOracle/bin/Debug/netcoreapp2.2/microsoft-spark-2.4.x-0.4.0.jar to environment
19/08/22 12:47:41 INFO DotnetRunner: Adding key=spark.app.name and value=org.apache.spark.deploy.dotnet.DotnetRunner to environment
19/08/22 12:47:41 INFO DotnetRunner: Adding key=spark.submit.deployMode and value=client to environment
19/08/22 12:47:41 INFO DotnetRunner: Adding key=spark.master and value=local to environment
myversion 1.2
[2019-08-22T15:47:41.6476372Z] [WS00100502] [Info] [ConfigurationService] Using port 62278 for connection.
[2019-08-22T15:47:41.6516372Z] [WS00100502] [Info] [JvmBridge] JvMBridge port is 62278
19/08/22 12:47:42 INFO SparkContext: Running Spark version 2.4.1
19/08/22 12:47:42 INFO SparkContext: Submitted application: Test oracle
19/08/22 12:47:42 INFO SecurityManager: Changing view acls to: u40497
19/08/22 12:47:42 INFO SecurityManager: Changing modify acls to: u40497
19/08/22 12:47:42 INFO SecurityManager: Changing view acls groups to:
19/08/22 12:47:42 INFO SecurityManager: Changing modify acls groups to:
19/08/22 12:47:42 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(u40497); groups with view permissions: Set(); users  with modify permissions: Set(u40497); groups with modify permissions: Set()
19/08/22 12:47:42 INFO Utils: Successfully started service 'sparkDriver' on port 62290.
19/08/22 12:47:42 INFO SparkEnv: Registering MapOutputTracker
19/08/22 12:47:42 INFO SparkEnv: Registering BlockManagerMaster
19/08/22 12:47:42 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
19/08/22 12:47:42 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
19/08/22 12:47:42 INFO DiskBlockManager: Created local directory at C:\Users\u40497\AppData\Local\Temp\blockmgr-d4bd1fdc-77f1-4a8a-aa9c-ed5be33e4756
19/08/22 12:47:42 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
19/08/22 12:47:42 INFO SparkEnv: Registering OutputCommitCoordinator
19/08/22 12:47:42 INFO Utils: Successfully started service 'SparkUI' on port 4040.
19/08/22 12:47:43 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://xxxx.xxx.xxx.xx:4040
19/08/22 12:47:43 INFO SparkContext: Added JAR file:/C:/Users/u40497/Source/Repos/testspark/BajadaOracle/bin/Debug/netcoreapp2.2/microsoft-spark-2.4.x-0.4.0.jar at spark://xxxx.xxx.xxx.xx:62290/jars/microsoft-spark-2.4.x-0.4.0.jar with timestamp 1566488863088
19/08/22 12:47:43 INFO Executor: Starting executor ID driver on host localhost
19/08/22 12:47:43 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService'
on port 62297.
19/08/22 12:47:43 INFO NettyBlockTransferService: Server created on xxxx.xxx.xxx.xx:62297
19/08/22 12:47:43 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
19/08/22 12:47:43 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, xxxx.xxx.xxx.xx, 62297, None)
19/08/22 12:47:43 INFO BlockManagerMasterEndpoint: Registering block manager xxxx.xxx.xxx.xx with 366.3 MB RAM, BlockManagerId(driver, xxxx.xxx.xxx.xx, 62297, None)
19/08/22 12:47:44 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, xxxx.xxx.xxx.xx, 62297, None)
19/08/22 12:47:44 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, xxxx.xxx.xxx.xx, 62297, None)
paso: 1 Antes de conectarse19/08/22 12:47:44 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:///C:/Datos/spark/warehouse').
19/08/22 12:47:44 INFO SharedState: Warehouse path is 'file:///C:/Datos/spark/warehouse'.
19/08/22 12:47:45 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
19/08/22 12:47:46 INFO SparkContext: Starting job: load at <unknown>:0
19/08/22 12:47:46 INFO DAGScheduler: Got job 0 (load at <unknown>:0) with 1 output partitions
19/08/22 12:47:46 INFO DAGScheduler: Final stage: ResultStage 0 (load at <unknown>:0)
19/08/22 12:47:46 INFO DAGScheduler: Parents of final stage: List()
19/08/22 12:47:46 INFO DAGScheduler: Missing parents: List()
19/08/22 12:47:46 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at load at <unknown>:0), which has
no missing parents
19/08/22 12:47:47 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 53.9 KB, free 366.2 MB)
19/08/22 12:47:47 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 18.4 KB, free 366.2 MB)
19/08/22 12:47:47 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on xxxx.xxx.xxx.xx:62297 (size: 18.4 KB, free: 366.3 MB)
19/08/22 12:47:47 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1161
19/08/22 12:47:47 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at load at <unknown>:0) (first 15 tasks are for partitions Vector(0))
19/08/22 12:47:47 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks
19/08/22 12:47:47 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, executor driver, partition 0, PROCESS_LOCAL, 7864 bytes)
19/08/22 12:47:47 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
19/08/22 12:47:47 INFO Executor: Fetching spark://xxxx.xxx.xxx.xx:62290/jars/microsoft-spark-2.4.x-0.4.0.jar with timestamp 1566488863088
19/08/22 12:47:47 INFO TransportClientFactory: Successfully created connection to xxxx.xxx.xxx.xx/10.30.56.121:62290 after 92 ms (0 ms spent in bootstraps)
19/08/22 12:47:47 INFO Utils: Fetching spark://xxxx.xxx.xxx.xx:62290/jars/microsoft-spark-2.4.x-0.4.0.jar to C:\Users\u40497\AppData\Local\Temp\spark-19224811-378c-4abc-b23d-b50738f75711\userFiles-19e66978-3d85-4a7d-8dd4-0f21920cdb21\fetchFileTemp6130470748559847502.tmp
19/08/22 12:47:48 INFO Executor: Adding file:/C:/Users/u40497/AppData/Local/Temp/spark-19224811-378c-4abc-b23d-b50738f75711/userFiles-19e66978-3d85-4a7d-8dd4-0f21920cdb21/microsoft-spark-2.4.x-0.4.0.jar to class loader
19/08/22 12:47:48 INFO Executor: Finished task 0.0 in stage 0.0 (TID 0). 772 bytes result sent to driver
19/08/22 12:47:48 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 1073 ms on localhost (executor driver) (1/1)
19/08/22 12:47:48 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
19/08/22 12:47:48 INFO DAGScheduler: ResultStage 0 (load at <unknown>:0) finished in 1,551 s
19/08/22 12:47:48 INFO DAGScheduler: Job 0 finished: load at <unknown>:0, took 1,679781 s
19/08/22 12:47:48 ERROR DotnetBackendHandler: methods:
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.DataFrameReader.log()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.format(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(scala.collection.Seq)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(java.lang.String[])
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.load(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.table(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public java.lang.String org.apache.spark.sql.DataFrameReader.logName()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logInfo(scala.Function0)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logInfo(scala.Function0,java.lang.Throwable)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logDebug(scala.Function0,java.lang.Throwable)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logDebug(scala.Function0)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logTrace(scala.Function0)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logTrace(scala.Function0,java.lang.Throwable)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logWarning(scala.Function0,java.lang.Throwable)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logWarning(scala.Function0)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logError(scala.Function0,java.lang.Throwable)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.logError(scala.Function0)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.isTraceEnabled()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.slf4j.Logger org.apache.spark.sql.DataFrameReader.org$apache$spark$internal$Logging$$log_()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.org$apache$spark$internal$Logging$$log__$eq(org.slf4j.Logger)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary$default$2()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.options(java.util.Map)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.options(scala.collection.Map)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public void org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary(boolean)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public boolean org.apache.spark.sql.DataFrameReader.initializeLogIfNecessary(boolean,boolean)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(java.lang.String[])
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(scala.collection.Seq)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.text(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,double)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,boolean)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.option(java.lang.String,long)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(scala.collection.Seq)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.api.java.JavaRDD)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.rdd.RDD)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(org.apache.spark.sql.Dataset)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.json(java.lang.String[])
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(scala.collection.Seq)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(org.apache.spark.sql.Dataset)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.csv(java.lang.String[])
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(scala.collection.Seq)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.parquet(java.lang.String[])
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(java.lang.String[])
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.orc(scala.collection.Seq)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(scala.collection.Seq)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(java.lang.String[])
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.textFile(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.lang.String,long,long,int,java.util.Properties)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.lang.String[],java.util.Properties)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.Dataset org.apache.spark.sql.DataFrameReader.jdbc(java.lang.String,java.lang.String,java.util.Properties)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.schema(java.lang.String)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public org.apache.spark.sql.DataFrameReader org.apache.spark.sql.DataFrameReader.schema(org.apache.spark.sql.types.StructType)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public final void java.lang.Object.wait() throws java.lang.InterruptedException
19/08/22 12:47:48 ERROR DotnetBackendHandler: public final void java.lang.Object.wait(long,int) throws java.lang.InterruptedException
19/08/22 12:47:48 ERROR DotnetBackendHandler: public final native void java.lang.Object.wait(long) throws java.lang.InterruptedException
19/08/22 12:47:48 ERROR DotnetBackendHandler: public boolean java.lang.Object.equals(java.lang.Object)
19/08/22 12:47:48 ERROR DotnetBackendHandler: public java.lang.String java.lang.Object.toString()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public native int java.lang.Object.hashCode()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public final native java.lang.Class java.lang.Object.getClass()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public final native void java.lang.Object.notify()
19/08/22 12:47:48 ERROR DotnetBackendHandler: public final native void java.lang.Object.notifyAll()
19/08/22 12:47:48 ERROR DotnetBackendHandler: args:
19/08/22 12:47:48 ERROR DotnetBackendHandler: argType: scala.collection.mutable.WrappedArray.ofRef, argValue: WrappedArray()
[2019-08-22T15:47:48.5226372Z] [WS00100502] [Error] [JvmBridge] JVM method execution failed: Nonstatic method load failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
[2019-08-22T15:47:48.5226372Z] [WS00100502] [Error] [JvmBridge] org.apache.spark.sql.AnalysisException: Unable to infer schema for Parquet. It must be specified manually.;
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:185)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:185)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:184)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:373)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleMethodCall(DotnetBackendHandler.scala:162)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.handleBackendRequest(DotnetBackendHandler.scala:102)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:29)
        at org.apache.spark.api.dotnet.DotnetBackendHandler.channelRead0(DotnetBackendHandler.scala:24)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:138)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Unknown Source)

[2019-08-22T15:47:48.5556372Z] [WS00100502] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method load failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)

Unhandled Exception: System.Exception: JVM method execution failed: Nonstatic method load failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
   at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
   at Microsoft.Spark.Sql.DataFrameReader.Load(String[] paths)
   at BajadaOracle.Program.Main(String[] args) in C:\Users\u40497\Source\Repos\testspark\BajadaOracle\Program.cs:line
35
19/08/22 12:47:51 INFO DotnetRunner: Closing DotnetBackend
19/08/22 12:47:51 INFO DotnetBackend: Requesting to close all call back sockets
19/08/22 12:47:51 INFO SparkContext: Invoking stop() from shutdown hook
19/08/22 12:47:51 INFO SparkUI: Stopped Spark web UI at http://xxxx.xxx.xxx.xx:4040
19/08/22 12:47:51 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/08/22 12:47:51 INFO MemoryStore: MemoryStore cleared
19/08/22 12:47:51 INFO BlockManager: BlockManager stopped
19/08/22 12:47:51 INFO BlockManagerMaster: BlockManagerMaster stopped
19/08/22 12:47:51 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/08/22 12:47:51 INFO SparkContext: Successfully stopped SparkContext
19/08/22 12:47:51 INFO ShutdownHookManager: Shutdown hook called
19/08/22 12:47:51 INFO ShutdownHookManager: Deleting directory C:\Users\u40497\AppData\Local\Temp\spark-a2e46ea4-4475-4049-b241-f058c6699227
19/08/22 12:47:51 INFO ShutdownHookManager: Deleting directory C:\Users\u40497\AppData\Local\Temp\spark-19224811-378c-4abc-b23d-b50738f75711

Thanks for changing the label. This is the full console output. I don't see a log anywhere, maybe I have to turn it on elsewhere?

**Comment by imback82** [comment]
This is the culprit:
```
 org.apache.spark.sql.AnalysisException: Unable to infer schema for Parquet. It must be specified manually.;
at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:185)
at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:185)
at scala.Option.getOrElse(Option.scala:121)
at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:184)
```
Can you specify `Format("jdbc")`? `spark.Read().Format("jdbc").Option(...)"`?

**Comment by topcatarg** [comment]
That was the problem. At least one of them.. Now I have a [2019-08-22T16:35:53.5686372Z] [XXXX] [Error] [JvmBridge] java.sql.SQLSyntaxErrorException: ORA-00911: car?cter
no v?lido (not valid character). I will keep digging around it... thanks a lot! (didn't change the query, still select 1 from dual)

**Comment by rapoth** [comment]
@topcatarg Did you manage to resolve this issue?

**Comment by rapoth** [comment]
@topcatarg I'm closing this issue due to lack of response but please feel free to reopen if you'd like to continue the discussion. Thank you!

**Comment by topcatarg** [comment]
Uhh.. I suspend this.. And totally forgot about you.. sorry.. yes, we manage to make some things works... Sorry and thanks a lot!!!!
