### ISSUE TITLE
Unable to publish and run app on Databricks

### ISSUE THREAD

**Issue by LHuang2019** [dotnet/spark#217]
Currently working through the document on deploy a [.NET app to Databricks](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/databricks-deployment).

I am able to build my [app](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started) correctly, and have create the cluster with the provided scripts from the documentation.

But when I try to [publish and run](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/databricks-deployment#one-time-setup) my app. The job fails with the following status:
`Your administrator has only allowed sql and python and r commands on this cluster. This execution contained at least one disallowed language.`

Any chance you guys know what the issue is?

**Comment by LHuang2019** [comment]
The issue has been resolved. I realized that the above error occurs if you created a High Concurrency cluster, it can be fixed if you switch to Standard Cluster Mode.

Follow-up, please update the document for the change that package has been update from 
`org.apache.spark.deploy.DotnetRunner` to `org.apache.spark.deploy.dotnet.DotnetRunner`.

**Comment by imback82** [comment]
The release notes for breaking changes are not enough? https://github.com/dotnet/spark/blob/master/docs/release-notes/0.4/release-0.4.md#breaking-changes

**Comment by LHuang2019** [comment]
> The release notes for breaking changes are not enough? https://github.com/dotnet/spark/blob/master/docs/release-notes/0.4/release-0.4.md#breaking-changes

Sorry, wasn't aware that it existed. I was originally following the guide from the [Microsoft website](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/databricks-deployment). Thank you for pointed it out to me.

**Comment by imback82** [comment]
Ah OK, thanks for pointing it out @LHuang2019.

@bamurtaugh, do you know which repo we need to update to fix https://docs.microsoft.com/en-us/dotnet/spark/tutorials/databricks-deployment#use-spark-submit ?

**Comment by imback82** [comment]
Created https://github.com/dotnet/docs/pull/14139 to address this.
