### ISSUE TITLE
How to set the log level?

### ISSUE THREAD

**Issue by 939481896** [dotnet/spark#222]
How to set the log level? There are so many logs when I debug the program! Is there any method to close some other  logs (such as info logs)?

**Comment by GoEddie** [comment]
“To stop these, in your Spark folder there is a conf directory. In the conf directory, you will have a log4j.properties file add these lines to the end of the file:

log4j.logger.org.apache.spark.util.ShutdownHookManager=OFF
log4j.logger.org.apache.spark.SparkEnv=ERROR

If you don’t have a log4j.properties you should have a log4j.properties.template, copy it to log4j.properties.“

**Comment by 939481896** [comment]
Thank you!I know it!
