### ISSUE TITLE
[FEATURE REQUEST]: Support Apache Spark 2.3.4 and 2.4.4. 

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#223]
Apache Spark 2.3.4/2.4.4 should be released soon. Once they are released, we need to support them.

**Comment by AceHack** [comment]
I am building them from source now and can't use them :(

I would really like to get 3.0.0 in there too for when I build from master, I know there will be issues but it would be nice for it to at least work.

**Comment by imback82** [comment]
2.4.4. is addressed by #232.

**Comment by imback82** [comment]
@AceHack you can take a look at #232 for 2.4.4 support. I will merge the PR once the E2E tests are validated.

Regarding 3.0.0, since the APIs are still not stable, we plan to work on supporting it as soon as branch-3.0 is cut in apache/spark.

**Comment by AceHack** [comment]
FYI, this is how I test 2.4.4
https://github.com/AceHack/spark-on-k8s-dotnet/blob/master/from-source/Dockerfile

**Comment by AceHack** [comment]
Will there be an updated version of the scala.jar released that references 2.4.4?

https://github.com/dotnet/spark/blob/4e6653610725e1bf56cee0361bc3773a5b023171/src/scala/microsoft-spark-2.4.x/pom.xml#L15
