### ISSUE TITLE
[FEATURE REQUEST]: Support for SparkSession.Range()

### ISSUE THREAD

**Issue by AFFogarty** [dotnet/spark#224]
**Is your feature request related to a problem? Please describe.**
.Net for Spark does not currently support `SparkSession.range()`.

**Describe the solution you'd like**
An implementation that matches the interface found in Scala Spark: https://spark.apache.org/docs/2.4.2/api/java/org/apache/spark/sql/SparkSession.html#range-long-

**Additional context**
Here is the Scala Spark implementation: https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/SparkSession.scala#L539

**Comment by imback82** [comment]
Closed by #224.
