### ISSUE TITLE
[FEATURE REQUEST]: SparkSession.Catalog

### ISSUE THREAD

**Issue by GoEddie** [dotnet/spark#226]
Is there a reason why SparkSession.Catalog isn't implemented or is it just not done yet?

https://spark.apache.org/docs/2.3.0/api/java/org/apache/spark/sql/catalog/Catalog.html

I'm willing to attempt to implement it but wanted to make sure that it is something you would accept or are you avoiding it?

**Comment by imback82** [comment]
Thanks @GoEddie for starting this work. It is just not done yet, and we would definitely accept the PR!

**Comment by GoEddie** [comment]
Closing as https://github.com/dotnet/spark/pull/231 was merged in
