### ISSUE TITLE
[FEATURE REQUEST]: Support different Scala overloads of `DataFrameReader.load()`

### ISSUE THREAD

**Issue by AFFogarty** [dotnet/spark#229]
**Is your feature request related to a problem? Please describe.**
In Scala, `DataFrameReader.load()` has 3 overloads:
 
* `load()`
* `load(path: String)`
* `load(paths: String*)`

Some popular Scala libraries only support particular overloads of this function.

Until now, .Net for Spark always calls `load(path: String*)`, even if no paths or a single path are provided.

**Describe the solution you'd like**
Change the C# implementation of `DataFrameReader.Load(params string[] paths)` to call the appropriate Scala overload of `load()` depending on the number of paths provided to the `paths` parameter.

**Additional context**
Scala implementation of `load()`: https://github.com/apache/spark/blob/branch-2.4/sql/core/src/main/scala/org/apache/spark/sql/DataFrameReader.scala#L166

**Comment by imback82** [comment]
Closed by #228
