### ISSUE TITLE
spark-submit --version 提示'系统找不到指定的路径'

### ISSUE THREAD

**Issue by lmssong** [dotnet/spark#233]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

spark-submit --version 提示'系统找不到指定的路径'

**Comment by imback82** [comment]
@lmssong can you describe the problem you encountered? Also, can you try to translate to English?

**Comment by imback82** [comment]
Closing due to the inactivity. Please feel free to reopen.
