### ISSUE TITLE
Tutorial: setx PATH considered harmfull

### ISSUE THREAD

**Issue by Peter-B-** [dotnet/spark#238]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

The tutorial advises to enter 
`setx PATH "C:\bin\spark-2.4.1-bin-hadoop2.7\bin;%PATH%"`

The code executed successfully, but emmited a 
`WARNING: The resulting value was shortened to 1024 characters`

(or something along that line. I'm sporting a German version of Windows).

I can now verify, that the last entry in the `PATH` variable is crippled, but I have no idea what came after that.

I think that line should be replaced with something more benign in the tutorial.

**Comment by imback82** [comment]
Thanks for reporting this @Peter-B-. We will update the doc.

**Comment by Peter-B-** [comment]
Thanks a lot to you for writing and maintaining the tutorial.

**Comment by imback82** [comment]
@bamurtaugh do you know who can help updating this doc? We shouldn't update PATH, but use `SPARK_HOME\bin\spark-submit` instead.

**Comment by bamurtaugh** [comment]
@imback82 Looks like we'd want to update both the getting started tutorial on the .NET site and the doc itself. 

@rowanmiller Works with the .NET site getting started tutorials (i.e. https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark) and @mamccrea works with the docs site (https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started).

**Comment by rowanmiller** [comment]
@bamurtaugh can you confirm if these are the correct changes...

Remove this command from the Windows Install Apache Spark step:
![image](https://user-images.githubusercontent.com/4741851/65469775-7af7f880-de1d-11e9-8531-087c527ea797.png)


Update this command from the Windows Run your app step:
![image](https://user-images.githubusercontent.com/4741851/65469821-9d8a1180-de1d-11e9-9f0a-6cecd617caf4.png)

To be:
> C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit --class org.apa.......

**Comment by bamurtaugh** [comment]
@rowanmiller LGTM. @imback82 Do the changes look correct to you?

**Comment by imback82** [comment]
I would do `%SPARK_HOME%\bin\spark-submit`
