### ISSUE TITLE
How to spark-submit with additional nuget?

### ISSUE THREAD

**Issue by bamurtaugh** [dotnet/spark#245]
I have a coding example that combines .NET Spark and ML.NET to do sentiment analysis. However, in order to `spark-submit`, I have to manually copy over the ML.NET associated dll's (i.e. Microsoft.ML.Data.dll) to my app's main folder/directory, otherwise I get errors like:

`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.`

What is the best way to handle running spark-submit when using a nuget beyond Microsoft.Spark? Do I need to copy over all the dlls/dependent files, or did I perhaps miss a step that could take care of that for me (i.e. how setting the `DOTNET_ASSEMBLY_SEARCH_PATHS` environment variable to my app's `bin\Debug\netcoreapp2.2` folder allows me to not worry about manually copying my main app's dll over every time)?

**Comment by rapoth** [comment]
@bamurtaugh In short yes, you'd have to copy over everything. These steps are [here](https://github.com/dotnet/spark/tree/master/deployment#preparing-your-spark-net-app) and the [submission instructions](https://github.com/dotnet/spark/tree/master/deployment#run-your-app-on-the-cloud). Please let us know if you still running into issues.

**Comment by bamurtaugh** [comment]
Thank you for your feedback! I just wanted to make sure I wasn't missing any sort of other way to perform this. Closing this issue since I can get it working (it just required the manual copying).
