### ISSUE TITLE
[FEATURE REQUEST]: In process Interop between JVM <-> CLR instead of IPC socket based

### ISSUE THREAD

**Issue by QuantApp** [dotnet/spark#252]
A humble suggestion. Perhaps you can have a look at the following project that offers in process Interop link between CoreCLR and the JVM instead of using an IPC (socket based) communication. This could have a relevant performance impact.
 
Project: https://github.com/QuantApp/CoFlows-CE
Details: https://github.com/QuantApp/CoFlows-CE/blob/master/docs/Polyglot/General.md

With kind regards

**Comment by imback82** [comment]
Do you have any benchmark you want to share? We explored this approach earlier this year, but it didn't give us any performance gain at all (esp. in cluster runs).

**Comment by rapoth** [comment]
@QuantApp I'm closing this due to lack of response but please feel free to reopen if you'd like to continue the discussion. Thank you!
