### ISSUE TITLE
[FEATURE REQUEST]: Implement Broadcast Variable.

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#253]
Currently, .NET for Spark doesn't support broadcast variables. This will be a good feature to have. More info here: https://spark.apache.org/docs/2.4.4/rdd-programming-guide.html#broadcast-variables.

We first need to evaluate if it is possible to access this from UDFs (which I think it should).

**Comment by anand035** [comment]
Is there any update on this ?

**Comment by imback82** [comment]
@anand035 we started working on this, so you can expect this feature in upcoming releases.

**Comment by imback82** [comment]
Closed by #414

**Comment by Niharikadutta** [comment]
Closing this issue as this feature has been implemented as of #414
