### ISSUE TITLE
127.0.0.1:5567 access denied

### ISSUE THREAD

**Issue by cstajj** [dotnet/spark#256]
![image](https://user-images.githubusercontent.com/44864794/65488294-667a3580-dedb-11e9-8196-dfe08b9f29b4.png)

**Comment by imback82** [comment]
Looks like you are trying to run a debug session. Did you follow the instruction here? https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#how-to-do-local-debugging

**Comment by cstajj** [comment]
> Looks like you are trying to run a debug session. Did you follow the instruction here? https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#how-to-do-local-debugging

Thank you,I solved the first problem in your way.but other one problem is comming
![1](https://user-images.githubusercontent.com/44864794/65562739-05ee0580-df7a-11e9-8e40-ad1f920153f7.png)

**Comment by imback82** [comment]
Can you try running in command line via `spark-submit`? It will give you a better error messages. Or what does the other terminal (that launched the `spark-submit`) show when this happens?

**Comment by cstajj** [comment]
> Can you try running in command line via `spark-submit`? It will give you a better error messages. Or what does the other terminal (that launched the `spark-submit`) show when this happens?

This is the display of CMD in Debug mode
![3](https://user-images.githubusercontent.com/44864794/65568508-b9f88c00-df8c-11e9-9b39-c303c0a4d107.png)
and this is display of CMD
 I input 《spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.4.0.jar dotnet bin\Debug\netcoreapp3.0\mySparkApp.dll》
![4](https://user-images.githubusercontent.com/44864794/65568732-6f2b4400-df8d-11e9-9647-110a781b8d8e.png)
 I think this is work

**Comment by imback82** [comment]
Can you run your application with `spark-submit` and attach a full log?

**Comment by cstajj** [comment]
> Can you run your application with `spark-submit` and attach a full log?

The Second run，isn't it?

**Comment by imback82** [comment]
Can you please attach a "full" log? The logs at the bottom are cut off.

**Comment by cstajj** [comment]
> Can you please attach a "full" log? The logs at the bottom are cut off.

![1](https://user-images.githubusercontent.com/44864794/65662532-1af49280-e067-11e9-9ec1-ba76cc92850d.png)
![2](https://user-images.githubusercontent.com/44864794/65662540-1f20b000-e067-11e9-808b-4aeb8f34cf72.png)
![3](https://user-images.githubusercontent.com/44864794/65662544-20ea7380-e067-11e9-96df-7e5191501dcc.png)
![4](https://user-images.githubusercontent.com/44864794/65662562-2647be00-e067-11e9-93a9-6688ba774bb9.png)

**Comment by cstajj** [comment]
> Can you please attach a "full" log? The logs at the bottom are cut off.

No errors were reported with absolute paths, but cmd not print
![5](https://user-images.githubusercontent.com/44864794/65664431-e3d4b000-e06b-11e9-8583-2b47ecc9c9dc.png)

**Comment by rapoth** [comment]
@cstajj I see you have resolved the problem when using an absolute path. Are you still facing issues?

**Comment by cstajj** [comment]
> @cstajj I see you have resolved the problem when using an absolute path. Are you still facing issues?

No error,But cmd did not enter the correct results,

**Comment by rapoth** [comment]
Sorry, I don't understand. What results were you expecting and what are you seeing?

**Comment by cstajj** [comment]
![2](https://user-images.githubusercontent.com/44864794/65825294-da378c00-e2a7-11e9-896a-346475f20047.png)
This is output without debug mode

**Comment by cstajj** [comment]
> Sorry, I don't understand. What results were you expecting and what are you seeing?

↑

**Comment by cstajj** [comment]
![5](https://user-images.githubusercontent.com/44864794/65825394-ecfe9080-e2a8-11e9-962b-fcabcda60c41.png)

**Comment by elvaliuliuliu** [comment]
@cstajj Looks like it works fine without debug mode from the log. But with debug mode, please follow this https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#how-to-do-local-debugging which also mentioned earlier. Let us know if you still face any issues.

**Comment by imback82** [comment]
@cstajj Please reopen if @elvaliuliuliu's suggestion didn't work.
