### ISSUE TITLE
Support more data types: ArrayType, MapType, DateType, and StructType

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#26]
The following types are not fully supported:
ArrayType, MapType, DateType, and StructType.

Check Row.cs, etc.

**Comment by imback82** [comment]
cc: @suhsteve / @elvaliuliuliu

**Comment by imback82** [comment]
@elvaliuliuliu which types are remaining now?

**Comment by elvaliuliuliu** [comment]
> @elvaliuliuliu which types are remaining now?

So according to Row.cs, `ArrayType`, `MapType`, `DecimalType`, `DateType` is not supported at the moment. I am working on `MapType`.

**Comment by Niharikadutta** [comment]
@imback82 I can take up DateTime and also expose that type for CreateDataFrame
