### ISSUE TITLE
`Window` usage for 'forward fill'

### ISSUE THREAD

**Issue by Kaime90** [dotnet/spark#264]
Im running a .NET Spark app for processing localization data. I'm grouping locations by time (locations group per minute) and i need to fill missing time with avarage of nearest locations. 
I run into a problem where i need to 'forward fill' those missing values, i found a similar implementation to the one i need but written in java: [https://stackoverflow.com/a/46712692](url)

My problem is that im not able to find a way of implementing this in .NET Spark, seems like `Window` usage i a little bit different in Spark.NET and im not able to find any documentation of this or examples of 'forward fill' written in Spark.NET. Am i missing something? 
Any clue will be help for me.

**Comment by imback82** [comment]
> My problem is that im not able to find a way of implementing this in .NET Spark, seems like `Window` usage i a little bit different in Spark.NET

Can you elaborate on the difference? If you have a sample code that you tried, we can help.

**Comment by Kaime90** [comment]
Hi, after diging a little bit more in the source code i found out that i was using `Window` class from a wrong namespace. There is `Window` method in namespace `Microsoft.Spark.Sql` and `Window` class in `Microsoft.Spark.Sql.Expressions` (that is the one i was looking for). 
To be able to use it had to specify whole namespace:
```var window = Microsoft.Spark.Sql.Expressions.Window
                        .PartitionBy(df[_userIdColName])
                        .OrderBy(_dayColName, _minutesColName);```

Sorry for false alarm, maybe it will be helpfull for someone else looking for it.
