### ISSUE TITLE
 The term 'spark-submit' is not recognized as the name of a cmdlet,

### ISSUE THREAD

**Issue by dotnettrainingacademy** [dotnet/spark#276]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

spark-submit : The term 'spark-submit' is not recognized as the name of a cmdlet, function, script file, or operable   program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.     At line:1 char:1                                                                                                       + spark-submit --version                                                                                               + ~~~~~~~~~~~~                                                                                                             + CategoryInfo          : ObjectNotFound: (spark-submit:String) [], CommandNotFoundException                           + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rapoth** [comment]
CC: @bamurtaugh

@dotnettrainingacademy Could you please see this issue: https://github.com/dotnet/spark/issues/268?

**Comment by imback82** [comment]
This is now fixed: https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark.
