### ISSUE TITLE
RelationalGroupedDataSet does not support Apply

### ISSUE THREAD

**Issue by schinchanikar-rms** [dotnet/spark#281]
in the examples given in repo here
https://github.com/dotnet/spark/blob/master/examples/Microsoft.Spark.CSharp.Examples/Sql/VectorUdfs.cs

I see that dataframe is grouped by Age and them Apply is called on it. But I cannot use Apply. For some reason it keeps saying Apply is not supported.

**Comment by imback82** [comment]
Can you check if the following Nuget is installed? https://www.nuget.org/packages/Microsoft.Spark.Experimental/

**Comment by schinchanikar-rms** [comment]
Actually, I also checked the code on github. The Apply method is marked internal. I don’t think I will be able to use Apply if it is marked internal.

**Comment by imback82** [comment]
That can be accessed thru the Nuget package I mentioned above: https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark.Experimental/Sql/RelationalGroupedDatasetExtensions.cs

**Comment by rapoth** [comment]
@schinchanikar-rms Did you get a chance to try out the suggestion above?

**Comment by imback82** [comment]
Please reopen this if the suggested solution didn't work.
