### ISSUE TITLE
Failed to load org.apache.spark.deploy.dotnet.DotnetRunner.

### ISSUE THREAD

**Issue by liangb4009** [dotnet/spark#302]
first, The error picture as below:
![02-issue_for_installed](https://user-images.githubusercontent.com/17453548/67257710-d1f5f980-f4bf-11e9-80e4-133c7457a86f.jpg)
second, This issues happen when I run command to exectue the demo program which name is "mySparkApp".
**Note:** i already add User Variables "DOTNET_ASSEMBLY_SEARCH_PATHS", the value is "C:\Users\CN093128\mySparkApp\bin\Debug\netcoreapp2.2";
third, The detail information as below:

```
C:\Users\CN093128\mySparkApp>%SPARK_HOME%\bin\spark-submit --class org.apache.sp
ark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.0\microsoft-
spark-2.4.x-0.5.0.jar dotnet bin\Debug\netcoreapp3.0\mySparkApp.dll
19/10/22 11:26:45 WARN NativeCodeLoader: Unable to load native-hadoop library fo
r your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/10/22 11:26:46 WARN DependencyUtils: Local jar C:\Users\CN093128\mySparkApp\b
in\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.5.0.jar does not exist, skipping.

19/10/22 11:26:46 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.depl
oy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubm
it$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167
)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scal
a:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/10/22 11:26:46 INFO ShutdownHookManager: Shutdown hook called
19/10/22 11:26:46 INFO ShutdownHookManager: Deleting directory C:\Users\CN093128
\AppData\Local\Temp\spark-06dad8b6-1ab5-4719-bd3c-05a76fb68a72
```

**Comment by liangb4009** [comment]
The command which raises the error as below:

> %SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.0\microsoft-spark-2.4.x-0.5.0.jar dotnet bin\Debug\netcoreapp3.0\mySparkApp.dll

**Comment by elvaliuliuliu** [comment]
It could not find the microsoft-spark-2.4.x-0.5.0.jar file. it seems like you have installed .net core 2.2. Can you try`%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.5.0.jar dotnet bin\Debug\netcoreapp2.2\mySparkApp.dll`?

**Comment by liangb4009** [comment]
@elvaliuliuliu Thank you for response.
I have tried to change the command as below, it is still return error message as below:
C:\Users\CN093128>%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.
dotnet.DotnetRunner --master local bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x
-0.5.0.jar dotnet bin\Debug\netcoreapp2.2\mySparkApp.dll
19/10/22 13:17:35 WARN NativeCodeLoader: Unable to load native-hadoop library fo
r your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
19/10/22 13:17:36 WARN DependencyUtils: Local jar C:\Users\CN093128\bin\Debug\ne
tcoreapp2.2\microsoft-spark-2.4.x-0.5.0.jar does not exist, skipping.
19/10/22 13:17:36 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.depl
oy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubm
it$$runMain(SparkSubmit.scala:810)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167
)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scal
a:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/10/22 13:17:36 INFO ShutdownHookManager: Shutdown hook called
19/10/22 13:17:36 INFO ShutdownHookManager: Deleting directory C:\Users\CN093128
\AppData\Local\Temp\spark-31c5844f-78c2-4360-b34d-d673a24da103
![03-issue_for_installed](https://user-images.githubusercontent.com/17453548/67260588-b21a0200-f4ce-11e9-9768-40d12f5db826.jpg)

**Comment by elvaliuliuliu** [comment]
Have you done dotnet build? If so, can you try cd to mySparkApp folder?

**Comment by imback82** [comment]
From the log:
```
Local jar C:\Users\CN093128\bin\Debug\netcoreapp2.2\microsoft-spark-2.4.x-0.5.0.jar does not exist, 
```
Can you first locate the jar?

**Comment by liangb4009** [comment]
@elvaliuliuliu @imback82 it can return the analysis results.
at the end of call progress. it will return java.io.IOException
Is it an issue?
before return the analysis results, it will do preparation, it wastes some time, is it correct behavior?
[log.txt](https://github.com/dotnet/spark/files/3753982/log.txt)
[analysisresult.txt](https://github.com/dotnet/spark/files/3753983/analysisresult.txt)

**Comment by liangb4009** [comment]
when i open cmd which name is "spark-submit.cmd".
it will then call another cmd which name is "spark-submit2.cmd".
then call "spark-class2.cmd"
then call many cmd such as "find-spak-home.cmd", "load-spark-env.cmd".
Is there any instruction how would you do like that?

**Comment by rapoth** [comment]
Would you be able to share your code snippet?

Also, at the end of your program, can you try adding the line `spark.Stop()`? Also, for the last error regarding deleting files, please refer to https://github.com/dotnet/spark/issues/49#issuecomment-486714091. In short, this is a known issue with Spark on Windows.
