### ISSUE TITLE
 Init script dbfs:/spark-dotnet/db-init.sh failed

### ISSUE THREAD

**Issue by anand035** [dotnet/spark#305]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

Trying to deploy sample Spark App on Azure data bricks. I get this error while running the Spark job
` Unexpected failure while waiting for the cluster to be ready. Cause Unexpected state for cluster (job-7-run-1): Init scripts failed. instance_id: af42971ed91c4248a893139238cd962e, databricks_error_message: Init script dbfs:/spark-dotnet/db-init.sh failed: Script exit status is non-zero`

Here are the files I uploaded to dbfs
`C:\>databricks fs ls dbfs:/spark-dotnet`
`Microsoft.Spark.Worker.netcoreapp2.1.linux-x64-0.2.0.tar.gz`
`Microsoft.Spark.Worker.netcoreapp2.1.linux-x64-0.6.0.tar.gz`
`db-init.sh`
`install-worker.sh`
`microsoft-spark-2.3.x-0.4.0.jar`
`microsoft-spark-2.4.x-0.4.0.jar`
`publish.zip`

My db-init.sh is pointing to this tar 
`DOTNET_SPARK_RELEASE=https://github.com/dotnet/spark/releases/download/v0.2.0/Microsoft.Spark.Worker.netcoreapp2.1.linux-x64-0.2.0.tar.gz`

I have tried changing to version 0.6.0 as well, I get same error.

**Comment by anand035** [comment]
I changed spark worker version to `0.6.0` in `init.sh` and then I uploaded following jars 
`microsoft-spark-2.3.x-0.6.0.jar`
`microsoft-spark-2.4.x-0.6.0.jar`
My cluster is using  Apache Spark 2.4.3, Scala 2.11

**Comment by imback82** [comment]
@suhsteve can you help?

@anand035 can you check if your db-init.sh's line endings are LFs, and not CR/LFs?

**Comment by suhsteve** [comment]
@anand035  can you try @imback82  regarding LF and CR/LF line endings ?  If you modified the .sh files in Windows, it may have added CR/LF as the line ending and that would cause issues when running the shell scripts on linux.  

Can you also try looking at the [init script logs](https://docs.databricks.com/clusters/init-scripts.html#cluster-scoped-init-script-logs) and see if there's any relevant error messages contained in them ?

**Comment by anand035** [comment]
yes my shell script had CR/LF endings, when I replaced CR/LF with LF, the job ran successfully
