### ISSUE TITLE
Sql UDF not working on databricks/locally getting System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by anand035** [dotnet/spark#307]
**Describe the bug**
Getting this error when trying to run simple UDF operation locally
`[Error] [JvmBridge] org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 16.0 failed 1 times, most recent failure: Lost task 0.0 in stage 16.0 (TID 207, localhost, executor driver): org.apache.spark.api.python.PythonException: System.IO.FileNotFoundException: Assembly 'mySparkApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' file not found 'mySparkApp.dll' in 'C:\Users\xyz\AppData\Local\Temp\spark-9d4405d4-2b0b-4965-a2e2-3fb2dfa2bb4c\userFiles-2aa6270a-9b16-4b7a-9cae-2ba4c212d7f5,C:\Users\xyz\mySparkApp,C:\bin\Microsoft.Spark.Worker-0.5.0\'`

Same job when I run from Databricks I get following
` [Error] [JvmBridge] JVM method execution failed: Nonstatic method showString failed for class 15 when called with 3 arguments ([Index=1, Type=Int32, Value=20], [Index=2, Type=Int32, Value=20], [Index=3, Type=Boolean, Value=False], )
[Error] [JvmBridge] org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 4, 10.139.64.92, executor 1): org.apache.spark.api.python.PythonException: System.IO.FileNotFoundException: Assembly 'mySparkApp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' file not found 'mySparkApp.dll' in '/local_disk0/spark-1a624afa-b31d-4d8d-828a-c03ab4eec774/userFiles-a4f6677f-123f-4237-8cd6-56ce5b208d57,/databricks/spark/work/app-20191025185344-0000/1,/usr/local/bin/spark-dotnet/Microsoft.Spark.Worker-0.6.0/'
   at Microsoft.Spark.Utils.AssemblyLoader.LoadAssembly(String assemblyName, String assemblyFileName) in /_/src/csharp/Microsoft.Spark/Utils/AssemblyLoader.cs:line 109
   at Microsoft.Spark.Utils.UdfSerDe.<>c.<DeserializeType>b__10_0(TypeData td) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 260
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Spark.Utils.UdfSerDe.Deserialize(UdfData udfData) in /_/src/csharp/Microsoft.Spark/Utils/UdfSerDe.cs:line 160
   at Microsoft.Spark.Utils.CommandSerDe.DeserializeUdfs[T](UdfWrapperData data, Int32& nodeIndex, Int32& udfIndex) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 266
   at Microsoft.Spark.Utils.CommandSerDe.Deserialize[T](Stream stream, SerializedMode& serializerMode, SerializedMode& deserializerMode, String& runMode) in /_/src/csharp/Microsoft.Spark/Utils/CommandSerDe.cs:line 225`

**To Reproduce**
Attaching my cs file and log files of Databricks run in which I was trying to do similar operation

**Expected behavior**
UDF operation performed on sql
[ProgramAttachment.txt](https://github.com/dotnet/spark/files/3773658/ProgramAttachment.txt)

[SparkUDFError.txt](https://github.com/dotnet/spark/files/3773652/SparkUDFError.txt)

**Comment by suhsteve** [comment]
@anand035 for your local run, you have a couple of options:
- copy your `mySparkApp.dll` to the same directory that your worker is installed in, ie `C:\bin\Microsoft.Spark.Worker-0.5.0\`
- change your working directory to the folder that contains `mySparkApp.dll` and run your `spark-submit` command there.
- Set the environment variable `DOTNET_ASSEMBLY_SEARCH_PATHS` to the path that contains `mySparkApp.dll`

For your Databricks job, the steps will be different depending on if you are submitting your job using `Set JAR` or `spark-submit`.  The instructions are [documented here](https://github.com/dotnet/spark/tree/master/deployment#run-your-app-on-the-cloud-2)

**Comment by anand035** [comment]
I am able to run it locally after manually copying the dll to `C:\bin\Microsoft.Spark.Worker-0.5.0\` 
In data bricks, it worked after 

- Uploaded mySparkApp.dll to "dbfs:/apps/dependencies/mySparkApp.dll
- Uncommented few lines at bottom of db-init.sh and 
- I added "--files","dbfs:/apps/dependencies/mySparkApp.dll" in param list of spark submit

**Comment by tkent** [comment]
@suhsteve I know this is an older post, but the situation has not changed since the OP's comments. The instructions you referenced...

1. Do not match [the databricks getting started guide](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/databricks-deployment), which covers the `spark-submit` route. Specifically, that guide does not include copying up the `mySparkApp.dll` separately and including a reference to it in the application string. Unless somebody come across at this specific issue, they won't know why it's not working.
2.  Does not work correctly for `spark-submit` jobs because it does not include instructions to uncomment/modify the `db-init.sh` lines so the application's dll is copied into the worker's installation directory.

The instructions referenced by @anand035 in the comment above work.
