### ISSUE TITLE
 Exception while deleting Spark temp dir

### ISSUE THREAD

**Issue by ericgrover** [dotnet/spark#312]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

Program executes and outputs correct results, but then gives me the following error:

 Exception while deleting Spark temp dir

java.io.IOException: Failed to delete: C:\Users\grovere\AppData\Local\Temp\spark-127e6ebd-f829-44c5-9666-ccbd7ef392d1\userFiles-25af16be-43b0-4ea3-b0f5-7cd694184633\microsoft-spark-2.4.x-0.5.0.jar

**Comment by elvaliuliuliu** [comment]
Could you please provide the command you use and attach a full log for us to better troubleshoot? Thanks.

**Comment by suhsteve** [comment]
Please refer to  [#49 (comment)](https://github.com/dotnet/spark/issues/49#issuecomment-486714091)

**Comment by imback82** [comment]
Closing as this is a known Spark issue on Windows.

**Comment by mrpaulandrew** [comment]
This still needs fixing please. Or, at least update the tutorial with a note about the known bug.

**Comment by imback82** [comment]
@bamurtaugh Can you help updating the tutorial with this info?

**Comment by bamurtaugh** [comment]
@imback82 Absolutely, just let me know what you folks think the update should say. I can then open a PR to update the website tutorial.

**Comment by imback82** [comment]
same as #483

**Comment by bamurtaugh** [comment]
Warning has been merged into the tutorial and should be visible soon.
