### ISSUE TITLE
[FEATURE REQUEST]: Support for Bucketizer

### ISSUE THREAD

**Issue by camer314** [dotnet/spark#313]
For ML workloads, the Bucketizer is a handy function -> [https://spark.apache.org/docs/latest/ml-features#bucketizer](url)

You can get around this by writing a UDF however the Bucketizer supports applying to multiple columns in a single task which is way more performant.

**Comment by GoEddie** [comment]
Have you got an example of how you want it to look in dotnet?

**Comment by imback82** [comment]
This will require expose MLlib APIs, possibly as a separate Nuget similar to how Delta was done.

**Comment by GoEddie** [comment]
so everything in here? 

https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.package

**Comment by imback82** [comment]
Yes, or we can try to match pyspark offering: https://github.com/apache/spark/tree/master/python/pyspark/mllib. We can start implementing `Bucketizer` first then expand it as necessary.

**Comment by GoEddie** [comment]
got it, implement bucketizer first but put it in a new project (similar to delta)

**Comment by imback82** [comment]
@GoEddie did you want to work on this? I can assign this to you.

Also, to make things simpler, we can create a new project as a part of `Microsoft.Spark` Nuget.

**Comment by GoEddie** [comment]
yep great, i'll get started

**Comment by imback82** [comment]
Thanks @GoEddie!

**Comment by camer314** [comment]
One important thing to note is the pyspark implementation is nowhere near as performant as Scala because the Scala version allows you to pass in multiple columns and buckets in the one call, pyspark current only supports singular column (as far as I am aware).

https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.ml.feature.Bucketizer
https://spark.apache.org/docs/latest/api/python/pyspark.ml.html#pyspark.ml.feature.Bucketizer

**Comment by GoEddie** [comment]
@camer314 got it, include inputCols and outputCols rather than just inputCol and outputCol.

So you'd like to be able to create bucketizer2 in this example?

https://github.com/apache/spark/blob/master/examples/src/main/scala/org/apache/spark/examples/ml/BucketizerExample.scala

ed

**Comment by GoEddie** [comment]
I think this can be closed now, Bucketizer was merged in last year.

**Comment by Niharikadutta** [comment]
Closing this issue as it has been completed with #378.
