### ISSUE TITLE
[FEATURE REQUEST]: Expose Column.Apply() API

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#314]
`Column` class is missing `Apply()` which can help scenarios described in #201.

**Comment by imback82** [comment]
@Niharikadutta Can you help on this?

**Comment by Niharikadutta** [comment]
Yes I'll look into this, thanks!

**Comment by imback82** [comment]
You can check #270 for reference.

**Comment by rapoth** [comment]
Closing as this functionality is in now.
