### ISSUE TITLE
[Question]: Read multiple parquet files at once from Azure Data lake Gen 2

### ISSUE THREAD

**Issue by anand035** [dotnet/spark#315]
- How to read all parquet files in a folder to a datafame ?
- How to read/write data from Azure data lake Gen2 ?

In PySpark, you would do it this way
`df = spark.read.parquet("abfss://sharedFolder@abc.dfs.core.windows.net/shared/compact.parquet/")`
`display(df)`

How do we do the same for DotNet for Apache spark job that runs in Azure databricks?

**Comment by imback82** [comment]
Did you try the following?
```C#
var df = spark.Read.Parquet("abfss://sharedFolder@abc.dfs.core.windows.net/shared/compact.parquet/")
df.Show();
```

**Comment by anand035** [comment]
@rapoth : I am not using Notebook, that code I shared as sample code of pySparkm, I am running my code as job only in databricks

@imback82 : I did, it does not work in databricks, I get error something like `[2019-10-29T17:52:45.1943070Z] [1029-173806-goat465-10-139-64-15] [Error] [JvmBridge] Configuration property lmteamsv.dfs.core.windows.net not found.` 

If I run it locally and replace path with `D:\temp\parquetfiles`, it works.. though I want to read the files from Abfss location

**Comment by rapoth** [comment]
@anand035 That's because you haven't configured your storage access keys. Please refer to Azure Databricks' documentation on [Azure Data Lake Storage Gen2](https://docs.databricks.com/data/data-sources/azure/azure-datalake-gen2.html). In short, you should do something along the following lines to configure access:

```csharp
spark.Conf().Set("fs.azure.account.auth.type.<storage-account-name>.dfs.core.windows.net", "SharedKey");
spark.Conf().Set("fs.azure.account.key.<storage-account-name>.dfs.core.windows.net","*** key ***")
```

**Comment by anand035** [comment]
I tried several things, but this one worked
`SparkSession spark = SparkSession
                .Builder()
                .AppName(".NET Spark SQL basic example")
                .Config("spark.some.config.option", "some-value")
                .Config("spark.hadoop.fs.azure.account.oauth2.client.secret", "abcd")
                .Config("spark.hadoop.fs.azure.account.oauth2.client.endpoint", @"https://login.microsoftonline.com/abcd")
                .Config("spark.hadoop.fs.azure.account.oauth2.client.id", "abcd")
                .Config("spark.hadoop.fs.azure.account.auth.type", "OAuth")
                .Config("spark.hadoop.fs.azure.account.oauth.provider.type", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider")
                .GetOrCreate();`

**Comment by rapoth** [comment]
Thanks for the update!
