### ISSUE TITLE
[BUG]: Typo in HDInsight deployment tutorial

### ISSUE THREAD

**Issue by AFFogarty** [dotnet/spark#324]
**Describe the bug**
In [this doc](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/hdinsight-deployment#publish-your-app) there is a typo.

**To Reproduce**

The doc says to compile on windows using this command:

```
cd mySparkApp
dotnet publish -c Release -f netcoreapp3.0 -r ubuntu.16.04-x6
```
There is a `4` missing in the `ubuntu.16.04-x6` which should be `ubuntu.16.04-x64`.

**Comment by suhsteve** [comment]
We should update it to `linux-x64`

**Comment by imback82** [comment]
@AFFogarty can you help creating a PR for fixing this?

**Comment by AFFogarty** [comment]
@imback82 OK, we can open a PR against https://github.com/dotnet/docs/tree/master/docs/spark

**Comment by imback82** [comment]
Oh, it's a docs repo. @bamurtaugh can you help?

**Comment by bamurtaugh** [comment]
@imback82 Yep, I'll open up a PR to fix this today.

**Comment by AFFogarty** [comment]
Fixed in https://github.com/dotnet/docs/pull/15601.  Closing issue.
