### ISSUE TITLE
chinese garbled

### ISSUE THREAD

**Issue by bouyeijiang** [dotnet/spark#335]
chinese garbled

**Comment by imback82** [comment]
Can you please provide more information?

**Comment by bouyeijiang** [comment]
sample code
 SparkSession spSession = SparkSession.Builder().AppName("words").GetOrCreate();
            DataFrame dFrame = spSession.Read().Csv(CsvPath);
            dFrame.Show();

result:

|    _c0|           _c1|    _c2|       _c3|   _c4|        _c5|    _c6|       _c7|    _c8|       _c9|
+-------+--------------+-------+----------+------+-----------+-------+----------+-------+----------+
|    ???|      ????????|?=?????|   ???????|??a???|  ??a?=????|???????|?????=????|???????|?????=????|
|2019269|2019-10-10(??)|    417|49,266,492| 28730| 29,857,760|      0|         0|  52012| 8,991,384|
|2019268|2019-10-09(??)|    373|47,912,294| 17082| 17,758,200|  14896| 5,149,180|      0|         0|

**Comment by imback82** [comment]
What's the encoding of your csv file? The default is UTF-8 and if you have a different encoding, you cand use `Option("encoding", "your-encoding-here")` when you read it. Also, looks like you want the strings to be header, so try `Option("header", "true")` as well.

**Comment by bouyeijiang** [comment]
csv file  default encoding is UTF-8,but no effect
code:
SparkSession spSession = SparkSession.Builder().AppName("words").GetOrCreate();
            var opt = new Dictionary<string, string>();
            opt.Add("header", "true");
            opt.Add("encoding", "utf-8");//gb2312 or gbk is same effect

            DataFrame dFrame = spSession.Read().Options(opt).Csv(CsvPath);
            dFrame.Show();


result:
+-------+--------------+----------+----------+---------+------------+--------+------------+--------+------------+
| number|      opendate|winingcode|     sales|singlenum|singlewining|?  ?p|?    -V?|?m?p|?m-V?|
+-------+--------------+----------+----------+---------+------------+--------+------------+--------+------------+
|2019269|2019-10-10(?)|       417|49,266,492|    28730|  29,857,760|       0|           0|   52012|   8,991,384|
|2019268|2019-10-09(    )|       373|47,912,294|    17082|  17,758,200|   14896|   5,149,180|       0|           0|
|2019267|2019-10-08(?)|       898|49,041,746|    31749|  33,001,640|   21472|   7,421,174|       0|           0|

**Comment by imback82** [comment]
can you post the input file you are using?

**Comment by bouyeijiang** [comment]
[彩票数据.txt](https://github.com/dotnet/spark/files/3845491/default.txt)

**Comment by elvaliuliuliu** [comment]
@bouyeijiang So I don't think this is a spark dotnet related problem. Could you try [this](https://superuser.com/questions/269818/change-default-code-page-of-windows-console-to-utf-8)?

**Comment by bouyeijiang** [comment]
is it maybe caused by spark environment or system? I saw dotnet  code have some problem about
SerDe.cs file.
 
 public static string ReadString(Stream s, int length)
        {
            if (length == (int)SpecialLengths.NULL)
            {
                return null;
            }

            var buffer = GetThreadLocalBuffer(length);
            TryReadBytes(s, buffer, length);
            return Encoding.UTF8.GetString(buffer, 0, length);
        }

those code is no problem?

**Comment by elvaliuliuliu** [comment]
Could you please specify what issue you see here at SerDe.cs? Moreover, could you try scala-shell to quickly test the reading Chinese character problem?

**Comment by bouyeijiang** [comment]
scala test is ok..

**Comment by bouyeijiang** [comment]
result 

![TIM截图20191118155205](https://user-images.githubusercontent.com/4083760/69034204-99dcca80-0a1b-11ea-939e-c59d13f239ca.png)

**Comment by robyle** [comment]
You are actually using Spark to predict lottery results.
你居然在用Spark做彩票结果预测。有空一起交流下使用Spark的心得哈
