### ISSUE TITLE
How to connect to ADLS Gen 2 in Spark.Net?

### ISSUE THREAD

**Issue by fxd1111359** [dotnet/spark#337]
How to connect to ADLS Gen 2 in Spark.Net? I tried something below, but the local debug may return the error

**[Error] [JvmBridge] JVM method execution failed: Nonstatic method json failed for class 11 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
[[Error] [JvmBridge] java.io.IOException: No FileSystem for scheme: abfss**

The code is

           var spark = SparkSession
                .Builder()
                .AppName("Click Stream Aggregation")
                .GetOrCreate();

            spark.Conf().Set("fs.azure.account.auth.type." + storageAccountName + ".dfs.core.windows.net", "OAuth");
            spark.Conf().Set("fs.azure.account.oauth.provider.type." + storageAccountName + ".dfs.core.windows.net", "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider");
            spark.Conf().Set("fs.azure.account.oauth2.client.id." + storageAccountName + ".dfs.core.windows.net", "" + appID + "");
            spark.Conf().Set("fs.azure.account.oauth2.client.secret." + storageAccountName + ".dfs.core.windows.net", "" + password + "");
            spark.Conf().Set("fs.azure.account.oauth2.client.endpoint." + storageAccountName + ".dfs.core.windows.net", "https://login.microsoftonline.com/" + tenantID + "/oauth2/token");

            var df = spark
                .Read()
                .Option("header", "true")
                .Csv(path);

**Comment by rapoth** [comment]
Did you try running this on the cloud (e.g., HDInsight Spark or Azure Databricks)? I'm not sure there is a local run experience for connecting to ADLS Gen2.

**Comment by asears** [comment]
Should be possible to connect to Gen2 from local client depending on what hadoop libraries are installed.

https://hadoop.apache.org/docs/stable/hadoop-azure/abfs.html
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-abfs-driver

**Comment by clegendre** [comment]
Hello,

I manage to connect from local client to ADLS Gen 2 in Spark.Net, using a dedicated Hadoop and a Spark without Hadoop installation:
* hadoop-2.10.0
* spark-2.4.5-bin-without-hadoop

Then by configuring the Hadoop installation: https://spark.apache.org/docs/latest/hadoop-provided.html (for Windows use this syntax),: 
```bash
for /f %%i in ('%HADOOP_HOME%bin\hadoop.cmd classpath') do set SPARK_DIST_CLASSPATH=%%i
```

In core-site.xml on Hadoop configuration file:

```xml
<configuration>
  <property>
    <name>fs.azure.account.auth.type.[your-account-name].dfs.core.windows.net</name>
    <value>SharedKey</value>
    <description></description>
  </property>
  <property>
    <name>fs.azure.account.key.[your-account-name].dfs.core.windows.net</name>
    <value>[your-shared-key]</value>
    <description>The secret password. Never share these.</description>
  </property>
</configuration>
```

Regards

**Comment by asears** [comment]
This could be closed or improvements made to local developer experience?

**Comment by Niharikadutta** [comment]
Hi @fxd1111359 , @asears We have recently added documentation on how to connect to ADLS Gen2 in Spark .NET and it is available [here](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/connect-to-azure-storage). We will be closing this issue as we believe it has been resolved. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
