### ISSUE TITLE
[FEATURE REQUEST]: Distributed aggregated user defined function example

### ISSUE THREAD

**Issue by Plasma** [dotnet/spark#366]
**Is your feature request related to a problem? Please describe.**
It would be great if an example was provided that showed how to:

1. Read from blob storage for example csv/json records
1. Partition the workload by a column, eg User ID
1. Run custom C# code across all rows in the workload on a per User-ID basis to emit a new result to be written to a new output stream (eg a new table)

There does not appear to be any example showing how you can actually _distribute_ the data processing across nodes.

It would also be good to understand how to then run this function on Azure Databricks.

**Comment by imback82** [comment]
@Plasma if you write in a C# UDF, Spar will do the distributing process with your custom C# code. If you are doing groupBy operation, please take a look: https://github.com/dotnet/spark/blob/master/examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/VectorUdfs.cs. 

https://github.com/dotnet/spark/blob/master/examples/Microsoft.Spark.CSharp.Examples/Sql/Batch/Basic.cs also has some UDF examples.

**Comment by Plasma** [comment]
Thanks @imback82 That looks like something that may work for me.

However the Apply() function is marked internal and so I cannot use it in my own code, see https://github.com/dotnet/spark/blame/master/src/csharp/Microsoft.Spark/Sql/RelationalGroupedDataset.cs#L87 any ideas?

**Comment by Plasma** [comment]
To elaborate on my use case a bit further, would GroupBy shuffle/hash/partition the data by the grouped column so that on a per-group basis I can distribute the arbitrary running of C# code on that group, allowing me to then process that group as a logical unit and emit zero or more rows based upon that group?

**Comment by Plasma** [comment]
Are there alternatives to GroupBy and Apply? eg flatMap or something with a partition-by clause?

Hope my use case is making sense -- thank you

**Comment by Plasma** [comment]
https://github.com/dotnet/spark/issues/359#issuecomment-563681965 references a nuget that lets me access Apply(). I think I know how to proceed from here, thank you.
