### ISSUE TITLE
Response status code does not indicate success: 401 (Unauthorized)

### ISSUE THREAD

**Issue by SaraMoitinho** [dotnet/spark#371]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-package
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by elvaliuliuliu** [comment]
@SaraMoitinho Can you provide more details e.g. error log, etc? Thanks!

**Comment by suhsteve** [comment]
There may be a bad entry in your nuget sources.   Can you run the following instead ?

`dotnet add package Microsoft.Spark --version 0.6.0 -s https://api.nuget.org/v3/index.json`

>**note**: Replace 0.6.0 with 0.7.0 if you would like to use the latest release.

**Comment by imback82** [comment]
@SaraMoitinho please reopen this issue when you provide more info.
