### ISSUE TITLE
[BUG]: Unable to use File Sink

### ISSUE THREAD

**Issue by anduran** [dotnet/spark#372]
**Describe the bug**
Unable to use File sink when using Spark Streaming

**To Reproduce**

I'm trying to write appends to a file on a streaming way, but getting the exception:

> System.Exception
>   HResult=0x80131500
>   Message=JVM method execution failed: Nonstatic method start failed for class 287 when called with no arguments
>   Source=Microsoft.Spark
>   StackTrace:
>    at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
>    at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object[] args)
>    at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object[] args)
>    at Microsoft.Spark.Sql.Streaming.DataStreamWriter.Start(String path)

None of this versions work:
```c#
            StreamingQuery query = spark
                .Sql("SELECT * FROM Messages")
                .WriteStream()
                .OutputMode("append")
                .Format("csv")
                .Option("path", @"<dirPath>\a.txt")
                .Start();

            StreamingQuery query = spark
                .Sql("SELECT * FROM Messages")
                .WriteStream()
                .OutputMode("append")
                .Format("csv")
                .Option("path", @"<dirPath>")
                .Start();

            StreamingQuery query = spark
                .Sql("SELECT * FROM Messages")
                .WriteStream()
                .OutputMode("append")
                .Format("csv")
                .Start(@"<dirPath>\a.txt");

            StreamingQuery query = spark
                .Sql("SELECT * FROM Messages")
                .WriteStream()
                .OutputMode("append")
                .Format("csv")
                .Start(@"<dirPath>");
```

**Comment by imback82** [comment]
In the error message, you should see something like the following:
```
[Error] [JvmBridge] org.apache.spark.sql.AnalysisException: checkpointLocation must be specified either through option("checkpointLocation", ...) or SparkSession.conf.set("spark.sql.streaming.checkpointLocation", ...);
```

So you need to set this config: `spark.sql.streaming.checkpointLocation` for your file sink.

**Comment by anduran** [comment]
Thanks! I was looking at the wrong output window (seems like there are three), so I didn't read that useful message. This is resolved.
