### ISSUE TITLE
Microsoft.Data.Analysis.DataFrame

### ISSUE THREAD

**Issue by AeroXuk** [dotnet/spark#375]
It seems on the 16th December, Microsoft has published a new DataFrame type. Adding this here as there may be code from this project that can be contributed or code from there that can be adopted.

- https://devblogs.microsoft.com/dotnet/an-introduction-to-dataframe/
- https://www.nuget.org/packages/Microsoft.Data.Analysis/
- https://github.com/dotnet/corefxlab/tree/master/src/Microsoft.Data.Analysis

**Comment by imback82** [comment]
Thanks @AeroXuk. There is an ongoing PR #277 that utilizes this to simplify writing UDFs.

FYI @eerhardt @pgovind

**Comment by Niharikadutta** [comment]
Completed as of #277. Closing this issue.
