### ISSUE TITLE
[FEATURE REQUEST]: The ability to process a bunch of messages in Udf

### ISSUE THREAD

**Issue by will-beta** [dotnet/spark#377]
I am writing a Udf extension for DataFrame, and I found that the `Functions.Udf<string, string>(msg =>...)` only allow one message to process. Can I write a Udf that supports multiple messages processing at a time?
Thanks in advance!

**Comment by will-beta** [comment]
It seems like the [ForeachBatch](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#foreachbatch) is what I wanted.

**Comment by elvaliuliuliu** [comment]
Thanks for your question! This is the ongoing work item. Please refer to #208.

**Comment by imback82** [comment]
@will-beta are you looking at the streaming write scenario only? If not, you can take a look at `VectorUDF` which takes a batch of rows at a time: https://github.com/dotnet/spark/blob/131d9b1f33dde357998b4464e9359ac03abc83fb/src/csharp/Microsoft.Spark.E2ETest/IpcTests/Sql/DataFrameTests.cs#L157

**Comment by will-beta** [comment]
@imback82 Thanks for your help! 
It seems like an experimental function.

**Comment by imback82** [comment]
Yes, it is currently under experimental, but will be moved to `Microsoft.Spark.Sql` namespace in a future release as the APIs become stable.

**Comment by Niharikadutta** [comment]
@will-beta We believe this issue to be addressed. Please let us know if there is any further assistance needed from us, thanks!

**Comment by will-beta** [comment]
> @will-beta We believe this issue to be addressed. Please let us know if there is any further assistance needed from us, thanks!

nothing further. thanks for the help!
