### ISSUE TITLE
Microsoft.Spark nuget package shouldn't have symbols files in it

### ISSUE THREAD

**Issue by eerhardt** [dotnet/spark#38]
We are currently packaging the `.pdb` symbols file into the NuGet package. But we should be using the new `.snupkg` format instead.

See https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

The reason we don't want symbols in the NuGet package is because it bloats every application that uses this package. Symbols are only be used when debugging, so publishing an application shouldn't need them.

**Comment by rapoth** [comment]
Great point! Ideally, we'd like to have separated Debug and Release packages similar to https://github.com/dotnet/machinelearning

What do you think?
