### ISSUE TITLE
Set master url & use mongo connector

### ISSUE THREAD

**Issue by blenddata** [dotnet/spark#380]
Hi
I have a spark cluster on ubuntu which is accessible from http://xxxx:32771/ (running on docker).
Here what i want to do:
1- Connect to cluster 
2- Run mongo scripts [(#164)](https://github.com/dotnet/spark/issues/164), I have no idea how to use mongo connector with dotnet core. ([mongo connector](https://docs.mongodb.com/spark-connector/master/python/read-from-mongodb/))
3- Get the result in an object

Could someone help me with this or I have to go with another solution since our project runs on dotnet core.  

Thanks

**Comment by imback82** [comment]
@blenddata can you be a bit more specific to the issue you are facing?

Did you try the following?
```C#
var spark = // create spark session.
var df = spark.Read.Format("mongo").Load();
df.PrintSchema();
```
#164 should have enough info for you to get started.

**Comment by blenddata** [comment]
I can't connect to my instance
`var spark = SparkSession.Builder().AppName("test").Master("spark://172.31.64.69:32771").GetOrCreate();`
I've got this exception
`No connection could be made because the target machine actively refused it. 127.0.0.1:5567`

**Comment by imback82** [comment]
Looks like you are trying to run a debug session. Can you try to run your application using `spark-submit` (https://github.com/dotnet/spark/blob/master/docs/getting-started/windows-instructions.md#running-your-net-for-apache-spark-app)?

If you want to debug your app, you can try the following instruction: https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#how-to-do-local-debugging

**Comment by blenddata** [comment]
@imback82 it was about `spark.driver.host` (remote access), I wrote in java in case of test:

```
SparkSession spark = SparkSession.builder()
            .master("spark://nodemaster:7077")
            .appName("MongoSparkConnectorIntro")
            .config("spark.network.timeout",2000000)
            .config("spark.driver.port","32772")
            .config("spark.driver.host","172.31.64.69")
            .config("spark.driver.bindAddress","172.18.0.2")
            .config("spark.mongodb.input.uri", "mongodb://")
            .config("spark.mongodb.output.uri", "mongodb://")
            .getOrCreate();
```
and ended up with this error 
`org.apache.spark.util.Utils: Service 'sparkDriver' could not bind on a random free port. You may check whether configuring an appropriate binding address.`

It seems spark on docker has some malfunctions. I want to go with k8s.
Thanks

**Comment by robyle** [comment]
Hi, Is this poroblem sloved ? I 'm trying ,but doesn't work~!
