### ISSUE TITLE
[FEATURE REQUEST]: Consider exposing JvmObjectReference

### ISSUE THREAD

**Issue by GoEddie** [dotnet/spark#382]
There are lots of Apache Spark classes/functions that have not been covered in spark dotnet and it is unlikely that there will ever be 100% coverage (it is possible but dotnet is always going to be playing catchup).

Is it worth exposing some of the internal classes that give access to create Java objects and call Java methods? 

It should come with a very big warning that it should be used only until the class/method is available in the official package but it could give some advanced users a way to start using spark dotnet  while they were still waiting for critical parts to be implemented.

It should be clear that the correct path is to use supported functions and that any direct calls are replaced with supported functions as and when they become available.

I would think if more people implemented their own functions that would mean more contributions to spark dotnet as more people know how to implement methods.

**Comment by imback82** [comment]
@GoEddie this was by design not to expose them to avoid confusion and misuses.

For advanced users, https://github.com/aelij/IgnoresAccessChecksToGenerator#usage can be used instead to access internal classes.

**Comment by GoEddie** [comment]
Nice, I’ll give it a go thanks!
