### ISSUE TITLE
[Question] Slack or gitter or something? 

### ISSUE THREAD

**Issue by GoEddie** [dotnet/spark#393]
Is there a community channel like slack or gitter where we can ask questions?

It would be useful to be able to ask questions when implementing changes and also it would probably stop some of the issues getting created and then left to hang around (like https://github.com/dotnet/spark/issues/303).

I know the delta lake team have a public slack channel that works really well

(please don't say yammer :) )

**Comment by Niharikadutta** [comment]
Hi @GoEddie, Thanks for reaching out and apologies for the delay in getting back about this. We had a discussion in the team and we were wondering if you would be open to the idea of an office hour perhaps bi-weekly where we can discuss any open issues or other questions you might have. Please let us know if that works, and we can set up a Teams meeting at the decided frequency.

Thanks!

**Comment by GoEddie** [comment]
Hi,

Yes anything like that would be interesting, I wouldn’t want to cause extra work so maybe monthly or every other month?


Ed

**Comment by Niharikadutta** [comment]
@GoEddie yes I think monthly would work great. Could you please provide us with your preferred email id and I will set up a monthly Teams meeting. Thanks!

**Comment by Niharikadutta** [comment]
Closing this issue as have a monthly meeting set up. Thanks @GoEddie !
