### ISSUE TITLE
No connection could be made because the target machine actively refused it. 127.0.0.1:5567

### ISSUE THREAD

**Issue by Yogesh-yrbyogi** [dotnet/spark#395]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/code
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

Getting error "No connection could be made because the target machine actively refused it. 127.0.0.1:5567"

**Comment by elvaliuliuliu** [comment]
Port 5567 is used for debug mode. Please follow [Debugging Spark .NET Application](https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#debugging-spark-net-application) if you want to debug the application. And you can refer to #175. 
Feel free to let us know if any questions. Thanks!

**Comment by imback82** [comment]
Please reopen this the suggested solution didn't work.
