### ISSUE TITLE
Official testing guidelines

### ISSUE THREAD

**Issue by AndreasVolkmann** [dotnet/spark#400]
It seems there is no guidance on how to test spark code written with the dotnet api.

From the resources I found, creating a spark context with `local` as the master is enough to run a single worker on the jvm but it looks like we cannot do this from c#. 
(https://stackoverflow.com/a/43734481/5335131)
 
I replicated the test set up from this repository, which locates the jar and starts a process using spark submit. Is this the current recommended approach?

**Comment by imback82** [comment]
@AndreasVolkmann, yes, setting up similar to https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark.E2ETest/SparkFixture.cs is one recommended way to test E2E .NET Spark application.

**Comment by AndreasVolkmann** [comment]
Thanks @imback82 . 
Maybe consider adding a note about this to the docs.
