### ISSUE TITLE
 Is apache spark .net compatible with elasticSearch?

### ISSUE THREAD

**Issue by JoseTala23** [dotnet/spark#408]
I need to obtain data from elasticSearch and I can't find a solution for it. I wanted to know if there is any manual or any way to make an inquiry to elasticsearch

**Comment by imback82** [comment]
Yes, can you check this thread: #212, #213? Basically you will need to do something like:
```C#
var df = spark.Read
    .Format("org.elasticsearch.spark.sql")
    .Option("inferSchema", "true")
    .Option("es.read.field.as.array.include", "tags")
    .Option("es.nodes","myelasticsearchserver:9200")
    .Option("es.net.http.auth.user","elastic")
    .Option("es.net.http.auth.pass","mypassword")
    .Load();
```

**Comment by imback82** [comment]
@JoseTala23 I hope that the suggestion worked out for you. Feel free to reopen the issue if it didn't work.
