### ISSUE TITLE
[FEATURE REQUEST]: Ability to reference Nuget packages in UDFs in notebooks

### ISSUE THREAD

**Issue by bamurtaugh** [dotnet/spark#409]
**Is your feature request related to a problem? Please describe.**

I am trying to use a Nuget package in Azure Synapse Analytics notebooks. I wrote a UDF that calls an earlier method, and that method depends on a Nuget package. When I called the UDF (through a Spark SQL call), I got an error: "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.ML.Data, Version 1.0.0.0..."

**Describe the solution you'd like**

We can write and call UDFs that depend on Nuget packages, i.e. by deploying the necessary Nuget packages/assemblies/dependencies to the worker nodes.

**Additional context**

The cell in which I defined the method that depends on the Microsoft.ML nuget package/Microsoft.ML.Data assembly runs fine. The error occurs when I run the cell that calls the UDF (which calls that method using Microsoft.ML) and tries to show the resulting DataFrame.

**Comment by imback82** [comment]
cc @suhsteve who worked on integrating this feature to .NET interactive kernel.

**Comment by Niharikadutta** [comment]
Completed as of #515. Closing this issue.
