### ISSUE TITLE
[FEATURE REQUEST]: Make the DateTime type available in the create dataframe api

### ISSUE THREAD

**Issue by ewatson95** [dotnet/spark#410]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to pass in an object of type DateTime to the CreateDataFrame API. Most data sets, at least from my experience, have some sort of timestamp associated with the data. However, when I try to pass in a DateTime, DateTimeOffset or TimeSpan data type, I get the error: System.DateTime not supported yet. This seems like an important data type for most applications.

**Describe the solution you'd like**
Implement the System.DateTime data type for the CreateDataFrame API. Or has anyone built an implementation of this that I can use until the feature comes out officially?

**Comment by imback82** [comment]
Thanks @ewatson95 for reporting this. This is in our roadmap, and you should see this in upcoming releases. Also #26 

cc @elvaliuliuliu

**Comment by ewatson95** [comment]
Just to be 100% certain we are talking about the same thing, I'm interested in the SparkSession.CreateDataFrame api. I have seen the DateType data type - will this be sufficient for a c# DateTime object to be passed into the CreateDataFrame method?

**Comment by imback82** [comment]
Yes, it is the current plan to use C# DateTime objects.

**Comment by elvaliuliuliu** [comment]
@ewatson95 , thanks for your question! Could you provide a code snippet of how you are using DateType in your application?

**Comment by imback82** [comment]
@elvaliuliuliu Basically, C# [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=netcore-3.1) objects should be allowed to be used if the type of your `DataFrame`'s fields is `DateType`. This applies to `UDF`, `Collect`, `CreateDataFrame`, etc.

**Comment by elvaliuliuliu** [comment]
> @elvaliuliuliu Basically, C# [DateTime](https://docs.microsoft.com/en-us/dotnet/api/system.datetime?view=netcore-3.1) objects should be allowed to be used if the type of your `DataFrame`'s fields is `DateType`. This applies to `UDF`, `Collect`, `CreateDataFrame`, etc.

Got it! Thanks for clarification! That's also my understanding. It applies not only to `CreateDataFrame` API, but also all related APIs.

**Comment by ewatson95** [comment]
Yes that's it - so i want to do:

`            var schema = new StructType(new List<StructField>()
            {
                new StructField("Point", new StringType()),
                new StructField("Status", new StringType()),
                new StructField("Value", new DoubleType()),
                new StructField("Timestamp", new DateType())
            });

DataFrame dataFrame = spark.CreateDataFrame(data, schema);`

where the timestamp field is a datetime object!

**Comment by elvaliuliuliu** [comment]
@ewatson95, Thanks for providing the example! This is an ongoing work item which will be supported in the upcoming releases. Thanks!

**Comment by MikeRys** [comment]
Can we make sure that we use the right datatype in .NET with the right timezone behavior for managing date time values?

E.g., C#’s DateTime datatype does not preserve timezone and uses a property to say if the value should be interpreted as local, system specific or as UTC. Other datatypes give more timezone support.

Thanks
Michael

**Comment by imback82** [comment]
FYI, note that there is no timezone involved with [DateType](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/types/DateType.scala), but [TimestampType](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/types/TimestampType.scala) is in UTC.

**Comment by MikeRys** [comment]
Thanks. That means we need to set the DateTime.Kind to UTC to keep the semantics.

**Comment by ewatson95** [comment]
It seems like TimestampType has a much greater precision and so is the more useful implementation - so if my DateTime object has time associated with it I should be using TimestampType?

**Comment by imback82** [comment]
What I am thinking is if you use C# `DateTime`, it will be converted to `DateType`, and a new, C# `Timestamp` class which wraps C# `DateTime` will be introduced to be used for `TimestampType`. All the necessary conversion operator, etc. will be provided. What do you folks think?

**Comment by imback82** [comment]
Adding few more folks for discussion: @suhsteve @rapoth @Niharikadutta

**Comment by imback82** [comment]
closed by #420 and #428
