### ISSUE TITLE
Issue when running apache spark in .net CMD

### ISSUE THREAD

**Issue by fazal-hotmail** [dotnet/spark#412]
WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

I have setup the path for dotnet_assembly_search according to microsoft tutorial
OS - Windows 10 - 64X
jdk 8 - 64X

full error message

D:\C# examples\Apache Spark Samples\mySparkApp3>%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.8.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll
20/02/02 06:47:03 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/02/02 06:47:04 INFO DotnetRunner: Starting DotnetBackend with dotnet.
20/02/02 06:47:04 INFO DotnetRunner: Port number used by DotnetBackend is 50368
20/02/02 06:47:04 INFO DotnetRunner: Adding key=spark.jars and value=file:/D:/C%23%20examples/Apache%20Spark%20Samples/mySparkApp3/bin/Debug/netcoreapp3.1/microsoft-spark-2.4.x-0.8.0.jar to environment
20/02/02 06:47:04 INFO DotnetRunner: Adding key=spark.app.name and value=org.apache.spark.deploy.dotnet.DotnetRunner to environment
20/02/02 06:47:04 INFO DotnetRunner: Adding key=spark.submit.deployMode and value=client to environment
20/02/02 06:47:04 INFO DotnetRunner: Adding key=spark.master and value=local to environment
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-bin\Debug\netcoreapp3.1\mySparkApp.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
20/02/02 06:47:05 INFO DotnetRunner: Closing DotnetBackend
20/02/02 06:47:05 INFO DotnetBackend: Requesting to close all call back sockets
20/02/02 06:47:05 INFO ShutdownHookManager: Shutdown hook called
20/02/02 06:47:05 INFO ShutdownHookManager: Deleting directory C:\Users\Fazal\AppData\Local\Temp\spark-e6dbe9f3-0ade-42dc-a5da-a51973a866f7

**Comment by elvaliuliuliu** [comment]
Can you please confirm the jar file and dll exist in the path specified?

**Comment by fazal-hotmail** [comment]
![image](https://user-images.githubusercontent.com/60559517/73601785-78f13380-458d-11ea-889c-3c52280a6a5a.png)

yes, Please check the image

**Comment by fazal-hotmail** [comment]
It Worked ! I found the issue.

I have made 2 mistakes.

1. I changed mySparkApp.dll to mySparkApp3.dll in spark-submit command
2. I created text file naming as "input.txt" and changed to "input" because extension is no need.
