### ISSUE TITLE
spark-submit --version error in cmd

### ISSUE THREAD

**Issue by filipstojakovic** [dotnet/spark#423]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/intro/install-spark
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

i am having trouble setting up spark in windows 10.
I get an error message "The filename, directory name, or volume label syntax is incorrect.", when running a command:
> %SPARK_HOME%\bin\spark-submit --version

Environment variables:
SPARK_HOME=C:\bin\spark-2.4.5-bin-hadoop2.7
HADOOP_HOME=C:\bin\spark-2.4.5-bin-hadoop2.7
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_241

**Comment by GoEddie** [comment]
From your command line does "java -version" work?

**Comment by elvaliuliuliu** [comment]
Can you run `spark-submit` directly in the `C:\bin\spark-2.4.5-bin-hadoop2.7\bin`?

**Comment by filipstojakovic** [comment]
> From your command line does "java -version" work?

>java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

**Comment by filipstojakovic** [comment]
> Can you try run `spark-submit` directly in the `C:\bin\spark-2.4.5-bin-hadoop2.7\bin`?

when running full command i get a same error
C:\bin\spark-2.4.5-bin-hadoop2.7\bin\spark-submit --version
The filename, directory name, or volume label syntax is incorrect.

**Comment by GoEddie** [comment]
Does it have a spark-submit script in the spark bin folder?

**Comment by filipstojakovic** [comment]
> Does it have a spark-submit script in the spark bin folder?

yes

**Comment by filipstojakovic** [comment]
> > Does it have a spark-submit script in the spark bin folder?
> 
> yes, i even added winutils.exe just in case

**Comment by Niharikadutta** [comment]
Can you try setting HADOOP_HOME to some other folder, say `C:/hadoop`, and place winutils.exe inside `C:/hadoop/bin` and see if that fixes/changes anything?

**Comment by filipstojakovic** [comment]
> Can you try setting HADOOP_HOME to some other folder, say `C:/hadoop`, and place winutils.exe inside `C:/hadoop/bin` and see if that fixes/changes anything?

Everything i tried was of no avail :(
But i notice this message when typing DIR command

C:\bin\spark-2.4.5-bin-hadoop2.7>dir
 Volume in drive C has no label.
 Volume Serial Number is 98DA-5528

 Directory of C:\bin\spark-2.4.5-bin-hadoop2.7

09-Feb-20  01:59 PM    <DIR>          .
09-Feb-20  01:59 PM    <DIR>          ..
09-Feb-20  02:17 PM    <DIR>          bin
09-Feb-20  01:59 PM    <DIR>          conf
09-Feb-20  01:59 PM    <DIR>          data
09-Feb-20  01:59 PM    <DIR>          examples
09-Feb-20  01:59 PM    <DIR>          jars
09-Feb-20  01:59 PM    <DIR>          kubernetes
02-Feb-20  08:47 PM            21,371 LICENSE
09-Feb-20  01:59 PM    <DIR>          licenses
02-Feb-20  08:47 PM            42,919 NOTICE
09-Feb-20  01:59 PM    <DIR>          python
09-Feb-20  01:59 PM    <DIR>          R
02-Feb-20  08:47 PM             3,756 README.md
02-Feb-20  08:47 PM               187 RELEASE
09-Feb-20  01:59 PM    <DIR>          sbin
09-Feb-20  01:59 PM    <DIR>          yarn
               4 File(s)         68,233 bytes
              13 Dir(s)  40,302,071,808 bytes free

**Comment by GoEddie** [comment]
Can you also type “set” in a command prompt and paste the output (mask things like username etc.) - key ones are path and java_home

**Comment by filipstojakovic** [comment]
> Can you also type “set” in a command prompt and paste the output (mask things like username etc.) - key ones are path and java_home

ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\filip\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-BSSOJPH
ComSpec=C:\Windows\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HADOOP_HOME=C:\bin\hadoop
HOMEDRIVE=C:
HOMEPATH=\Users\filip
IntelliJ IDEA=C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\bin;
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_241;C:\Program Files\Java\jre1.8.0_241;C:\Program Files\Java\jdk-12.0.2;
JetBrains Rider=C:\Program Files\JetBrains\JetBrains Rider 2019.2.2\bin;
LOCALAPPDATA=C:\Users\filip\AppData\Local
LOGONSERVER=\\DESKTOP-BSSOJPH
MOZ_PLUGIN_PATH=C:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\plugins\
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\filip\OneDrive
OneDriveConsumer=C:\Users\filip\OneDrive
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.232-3\bin;C:\Program Files\RedHat\java-1.8.0-openjdk-1.8.0.232-3\jre\bin;C:\Program Files\Java\jdk-12.0.2\bin;C:\Users\filip\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\JetBrains Rider 2019.2.2\bin;C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3\bin;C:\Users\filip\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Oracle\VirtualBox;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PATH_TO_FX=C:\Users\filip\javafx-sdk-13
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 11, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=8e0b
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SPARK_HOME=C:\bin\spark-2.4.5-bin-hadoop2.7
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\filip\AppData\Local\Temp
TMP=C:\Users\filip\AppData\Local\Temp
USERDOMAIN=DESKTOP-BSSOJPH
USERDOMAIN_ROAMINGPROFILE=DESKTOP-BSSOJPH
USERNAME=filip
USERPROFILE=C:\Users\filip
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
windir=C:\Windows

**Comment by GoEddie** [comment]
Ok, set JAVA_HOME to just one path without a ; in so “ C:\Program Files\Java\jdk1.8.0_241” - the spark scripts do %JAVA_HOME%\bin\java so multiple paths with a semi colon cause an error

**Comment by filipstojakovic** [comment]
> Ok, set JAVA_HOME to just one path without a ; in so “ C:\Program Files\Java\jdk1.8.0_241” - the spark scripts do %JAVA_HOME%\bin\java so multiple paths with a semi colon cause an error

Now i get a new error message 
C:\bin\spark-2.4.5-bin-hadoop2.7\bin> .\spark-submit --version                                                       The system cannot find the path specified.

**Comment by GoEddie** [comment]
You only need the .\ in a powershell prompt try spark-shell —version

**Comment by filipstojakovic** [comment]
> You only need the .\ in a powershell prompt try spark-shell —version

i use tab for autocomplete that is why i get .\ at start
In power shell i get a blink/flash of cmd. No message just windows open and closes
in cmd i still get a same error.
Maybe its time to make VM

**Comment by GoEddie** [comment]
Probably makes sense, if your still getting “ The system cannot find the path specified.” you could use procmon, it is probably your JAVA_HOME path

**Comment by filipstojakovic** [comment]
> Probably makes sense, if your still getting “ The system cannot find the path specified.” you could use procmon, it is probably your JAVA_HOME path

I am giving up for now. I will make VM with Linux or windows 7/10 and try again.
Thanks for you help <3
