### ISSUE TITLE
[BUG]: Null values cannot be read from DataFrame 

### ISSUE THREAD

**Issue by zwitbaum** [dotnet/spark#436]
**Describe the bug**
While trying to read a null value from a DataFrame a NullReferenceException occurred:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Spark.Sql.Types.DateType.FromInternal(Object obj)
   at Microsoft.Spark.Sql.Row.Convert()
   at Microsoft.Spark.Sql.Row..ctor(Object[] values, StructType schema)
   at Microsoft.Spark.Sql.RowConstructor.GetRow()
   at Microsoft.Spark.Sql.RowCollector.Collect(ISocketWrapper socket)+MoveNext()
   at Microsoft.Spark.Sql.DataFrame.GetRows(String funcName)+MoveNext()
   ...
```

**To Reproduce**

1. Create a DataFrame with a null value. Try to enumerate the rows:
```
var dates = new[] { DateTime.Today, DateTime.Today.AddDays(-1) };
var columnName = "Date";
var df = spark.Session.CreateDataFrame(dates.Select(date => new Date(date)).Append(null)).WithColumnRenamed("_1", columnName);
foreach (var row in df.Collect())
{
    var value = row.Get("Date"); // Case1: NRE
    var value2 = row.Get<Date?>("Date"); // // Case2: NRE, null expected
}
```
2. NullReferenceException is thrown (see above)

**Additional info**
```
df.PrintSchema();

root
 |-- Date: date (nullable = true)

df.Show();

+----------+
|      Date|
+----------+
|2020-03-02|
|2020-03-01|
|      null|
+----------+
```

**Expected behavior**
- row.Get("Date") returns null instead of throwing the NRE
- row.Get<Date?>("Date") returns null instead of throwing the NRE

**Is any workaround exists to read the null value by now?**

**Comment by imback82** [comment]
@zwitbaum Thanks for reporting. This looks like a valid bug. @elvaliuliuliu Can you help fixing this? Note that null should be handled correctly for both reference types and value types (`int`, `double`, etc.)

For a workaround, you can either catch the `NullReferenceException` on your side or drop null rows by using `Na().Drop()` on your dataframe before collecting rows (if it makes sense for your  scenario).

**Comment by elvaliuliuliu** [comment]
@zwitbaum Thanks for reporting this. I will take a look and update.
