### ISSUE TITLE
[FEATURE REQUEST]: Running an C# executable under a directory for spark-submit

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#438]
**Is your feature request related to a problem? Please describe.**
Currently, if you run the following:
```
spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner run.zip dir\runner.exe
```
where `runner.exe` exists under `dir` directory when `run.zip` is unzipped.

**Describe the solution you'd like**
`DotnetRunner.resolveDotnetExecutable` should be able to handle this case.

**Comment by elvaliuliuliu** [comment]
I will work on this.

**Comment by imback82** [comment]
Thanks @elvaliuliuliu!
