### ISSUE TITLE
[Question]: Does dotnet spark support mapWithState now ?

### ISSUE THREAD

**Issue by skyridder** [dotnet/spark#459]
Does dotnet spark support mapWithState now ? If so, how to use it ?

**Comment by imback82** [comment]
@skyridder Spark Streaming (DStream) APIs (including `mapWithState`) are not supported in .NET for Apache Spark. You can use newer Structured Streaming APIs instead.

**Comment by skyridder** [comment]
> @skyridder Spark Streaming (DStream) APIs (including `mapWithState`) are not supported in .NET for Apache Spark. You can use newer Structured Streaming APIs instead.
----------------
Thanks for reply.
My goal is to store calculate result in redis and take it as a new condition at next calculation. 
Can I achive the goal by using “newer Structured Streaming API” ?

**Comment by skyridder** [comment]
Thanks for reply.
My goal is to store calculate result in redis and take it as a new condition at next calculation. 
Can I achive the goal by using “newer Structured Streaming API” ?

**Comment by imback82** [comment]
@skyridder Can you check https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html to Structured Streaming APIs? Stateful operations like `mapGroupsWithState` are only supported in Java/Scala (and not in Python which .NET for Apache Spark piggybacks on).
