### ISSUE TITLE
[FEATURE REQUEST]: Forward compatibility E2E tests

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#462]
Similar to #453, I think it's equally important to have forward compatibility tests. There are scenarios where the version of worker binaries is newer than the client side Nuget. This testing framework should help easily identify the forward compatibility.

For this, we need to set up a new project that depends on old Microsoft.Spark Nuget, and run it against the Worker in the master branch. One idea is to copy E2E tests from the known working release version, and modify it to depend on that version of Nuget.

**Comment by imback82** [comment]
@elvaliuliuliu Can you help on this?

**Comment by elvaliuliuliu** [comment]
Sure, I will work on this!
