### ISSUE TITLE
create database no show in hadoop

### ISSUE THREAD

**Issue by bigbigword3** [dotnet/spark#467]
when i use hive cmd :  create database test_db_98k
it will create a "test_db_98k.db" on hadoop,
but if i use follow codes create database,then not show db in hadoop,and then i find it in my application debug folder.
`            var spark = SparkSession.Builder()
                .Config("spark.sql.warehouse.dir", "/user/hive/warehouse/")
                .EnableHiveSupport().GetOrCreate();
            var db = $"test_db_98k";
            spark.Sql($"create database {db}");`

**Comment by imback82** [comment]
If you want to write data to HDFS by default, you need to configure Spark to do that. Otherwise, it will use the local filesystem. This may help https://cbw.sh/spark.html. And this may help for Hive interoperability: https://spark.apache.org/docs/latest/sql-data-sources-hive-tables.html

**Comment by imback82** [comment]
I am closing this since the question is not specific to .NET for Spark but more of a general question for Spark. You can also try asking Spark-related questions to Spark community: https://spark.apache.org/community.html

**Comment by bigbigword3** [comment]
thanks!
