### ISSUE TITLE
[FEATURE REQUEST]: Structured DataFrame.Explain

### ISSUE THREAD

**Issue by thrixton** [dotnet/spark#471]
Is there any technical reason why the output of `DataFrame.Explain` cannot be returned in a structured form?
Happy to have a look and submit a PR if it's possible and would be desirable.

Thanks for the great work.

**Comment by elvaliuliuliu** [comment]
@thrixton thanks for your question! Could you please provide an example of the format you want?

And your contributions would be really appreciated! Please feel free to explore and submit your PR! Thank you!

**Comment by imback82** [comment]
@thrixton This is the same behavior as Scala: https://github.com/apache/spark/blob/55dea9be62019d64d5d76619e1551956c8bb64d0/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L547

We may expose something like `explainString` but I am -1 for supporting C# specific APIs at the moment unless they are absolutely necessary.

**Comment by thrixton** [comment]
@elvaliuliuliu , I really just want to be able to easily grab the output for logging at this stage to be honest.
@imback82 , I think something like explainString would be fine.
Would this be ok?
```csharp
        public string ExplainString(bool extended = false)
        {
            var execution = (JvmObjectReference)_jvmObject.Invoke("queryExecution");
            return ((string)execution.Invoke(extended ? "toString" : "simpleString"));
        }
````
And then refactor Explain to use `ExplainString`.

**Comment by imback82** [comment]
> @imback82 , I think something like explainString would be fine.
> Would this be ok?
> 
> ```cs
>         public string ExplainString(bool extended = false)
>         {
>             var execution = (JvmObjectReference)_jvmObject.Invoke("queryExecution");
>             return ((string)execution.Invoke(extended ? "toString" : "simpleString"));
>         }
> ```

Since `queryExecution` is an [unstable developer API ](https://github.com/apache/spark/blob/5d76b12e9b2ca0eb090c3c5145eee4cf78caba13/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L192), I don't think it's a good idea to depend on it (although it's less likely to change). Can you work around by using https://github.com/aelij/IgnoresAccessChecksToGenerator to access internal fields?

> And then refactor Explain to use `ExplainString`.

Actually, I tried this for the first version to print on the C# process side. However, the behavior was not consistent when I integrated with a notebook so I switched back to get this printed on the JVM side.

**Comment by thrixton** [comment]
I don't quite follow. Apologies, I'm a long way from understanding how the bridge internals work or even how Spark works internally.
The output is already outputted to the console on the .NET side, not the JVM side, as per below. Am I missing something?

```csharp
        public void Explain(bool extended = false)
        {
            var execution = (JvmObjectReference)_jvmObject.Invoke("queryExecution");
            Console.WriteLine((string)execution.Invoke(extended ? "toString" : "simpleString"));
        }
```
I'm not sure exactly how accessing any internals would help me here.

**Comment by imback82** [comment]
You can get to `JvmObjectReference IJvmObjectReferenceProvider.Reference => _jvmObject;` or `SparkEnvironment.JvmBridge`.

**Comment by imback82** [comment]
> The output is already outputted to the console on the .NET side, not the JVM side, as per below. Am I missing something?

They are two different processes so the output can go to a different console, for example.

**Comment by imback82** [comment]
Also, if you want to see this in action, you can try to debug the application: https://github.com/dotnet/spark/blob/master/docs/developer-guide.md#how-to-do-local-debugging and you will see which gets outputted to which console.

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
