### ISSUE TITLE
Explode UDF response for returning multiple rows

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#477]
HI,
How can I have udf return multiple rows? I am trying to return string from UDF as json array and then explode/fromjson to get rows but getting error.

I have UDF which returns a string (josn array) like

[
{"id":"1", "name":"name1"},
{"id":"2", "name":"name2"}
]

I want to explode it into 2 rows and then save into table with id and name as columns.

I tried defining schema like

/ schema of each item in the array
StructType arrayItemDataType= new StructType(new structfiled("name"), new structfiled(id));
var rootType = new ArrayType(itemDataType); // array of items

var field = new StructField(name: "MyJson", dataType: rootType, isNullable: false);
StructType schema = new StructType(new structField(field));

after explode it create schema like

root
 |-- col: struct (nullable = true)
 |    |-- name: string
 |    |-- id: string
I am running on local cluster and writing to csv, I was expecting after explode it should have dataframe with 2 columns name and id and i can write all rows in csv. When I run it is not creating df schema as name,id and fails to write to csv with message "csv doesn't support struct<>

**Comment by imback82** [comment]
Spark doesn't support this scenario (CSV support complex types): https://github.com/apache/spark/blob/f5250a581b765ef8c9044438b5d27461f843b7fd/sql/core/src/test/scala/org/apache/spark/sql/FileBasedDataSourceSuite.scala#L326

Can you use Parquet instead if you want to write a struct type to a file?

**Comment by guruvonline** [comment]
got the correct syntax from another [forum ](https://stackoverflow.com/questions/61070630/spark-explode-column-with-json-array-to-rows)and able to explode json array as simple types and save into csv file.
