### ISSUE TITLE
[FEATURE REQUEST]: How to call C# UDF from pyspark

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#478]
Can i call a UDF written in c# ,from other languages? I have a UDF and want to use same from pyspark.

**Comment by imback82** [comment]
Theoretically yes, but you need hop thru many steps. I have one example where you can call C# UDF from Scala: https://github.com/imback82/sparkdotnetudf. Enjoy!

**Comment by guruvonline** [comment]
thanks will try it.
