### ISSUE TITLE
[Coding Style]: Is there a preference for methods?

### ISSUE THREAD

**Issue by GoEddie** [dotnet/spark#479]
Hi,

I just wanted to see if there was a preference for when to use either of these styles?

```csharp
public string GetOutputCol()
{
    return (string)(_jvmObject.Invoke("getOutputCol"));
}
```
or
```csharp        
public string GetOutputCol() => (string)(_jvmObject.Invoke("getOutputCol"));
```

Thanks,

Ed

**Comment by Niharikadutta** [comment]
@GoEddie Thanks for your question! The preference is to use the second style whenever there is a one-line function.

**Comment by GoEddie** [comment]
Great thanks
