### ISSUE TITLE
[Question]: Unexpected warning "Unable to load native-hadoop library for your platform..."

### ISSUE THREAD

**Issue by neil-hudson-SQC** [dotnet/spark#481]
Having followed the installation process, when I run the tutorial application I see the warning message

WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

Having checked this out I believe that the installation of WinUtils (https://github.com/steveloughran/winutils/blob/master/hadoop-2.7.1/bin/winutils.exe) done as part of the tutorial is intended to provide a native Hadoop library.

Therefore I am unclear why the warning is being generated. Please can you clarify whether a correct deployment of WinUtils should prevent this warning and, if so, what to look for in terms of an issues that may be preventing it from doing so in this case.

Software information below...

SPARK
spark-submit  --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.1
      /_/

Using Scala version 2.11.12, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_241
Branch
Compiled by user  on 2019-03-26T22:44:44Z
Revision
Url
Type --help for more information.

OS
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~800 Mhz
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Hotfix(s):                 12 Hotfix(s) Installed.
                           [01]: KB4534132
                           [02]: KB4508433
                           [03]: KB4515383
                           [04]: KB4516115
                           [05]: KB4521863
                           [06]: KB4524244
                           [07]: KB4524569
                           [08]: KB4528759
                           [09]: KB4537759
                           [10]: KB4538674
                           [11]: KB4541338
                           [12]: KB4551762

**Comment by neil-hudson-SQC** [comment]
Have now established this is not related to WinUtils. The question is now..
(a) Is there a "downside" to not using a native-hadoop library compared with using a native-hadoop library, the read me page for the native libraries mentions performance benefits?
Assuming there would be some benefit then..
(b) Are there native libraries for Windows available as binaries?
(c) Is there a way of building native libraries from existing source code or is it something that would need to be written?

**Comment by imback82** [comment]
@neil-hudson-SQC Hadoop is a library that Spark depends on (client part), so I cannot help much here. You may want to look at some answers from Stackoverflow or reach out to Hadoop community. 

Unless you plan to deploy/manage Hadoop on Windows by yourself, I wouldn't worry too much about this warning message. Thanks!

**Comment by imback82** [comment]
@neil-hudson-SQC I am closing this since the question is related more to Hadoop. But feel free to reopen if you have further questions.
