### ISSUE TITLE
error when submitting new script action

### ISSUE THREAD

**Issue by yuejli** [dotnet/spark#485]
I followed the tutorial and instructions in [.NET for Apache Spark 101](https://www.youtube.com/watch?v=7PY84oJ6LQU&list=PLdo4fOcmZ0oXklB5hhg1G1ZwOJTEjcQ5z&index=8) and [.NET for Apache Spark-hdinsight-deployment](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/hdinsight-deployment) to deploy a app on HDInsight. But when submmitting script action, it installed failed with the following information:
```
"error_log": "/var/lib/ambari-agent/data/errors-895.txt",
```
and 
```
"error_log": "/var/lib/ambari-agent/data/errors-896.txt",
```
I followed the option selection in the tutorial, and meet with failure. Is there anything I missed or did wrong? If it is, how could I fix this issue.

**Comment by imback82** [comment]
Can you follow instruction in #470? I think the install script is out of date and @Niharikadutta is planning to update it asap.

**Comment by yuejli** [comment]
> 
> 
> Can you follow instruction in #470? I think the install script is out of date and @Niharikadutta is planning to update it asap.

Thanks @imback82, I was wondering If changing .netcore version back into 2.1 could temporarily solve this problem?

**Comment by imback82** [comment]
Can you share the actual log messages when you run the script action?

**Comment by yuejli** [comment]
Sure
```
Debug information
{
    "href": "http://hn0-excels.mm2brxx0l2ouvbv4fwbleiff3e.hx.internal.cloudapp.net:8080/api/v1/clusters/excelspark/requests/227",
    "tasks": [
        {
            "href": "http://hn0-excels.mm2brxx0l2ouvbv4fwbleiff3e.hx.internal.cloudapp.net:8080/api/v1/clusters/excelspark/requests/227/tasks/895",
            "Tasks": {
                "attempt_cnt": 1,
                "command": "ACTIONEXECUTE",
                "command_detail": "run_customscriptaction ACTIONEXECUTE",
                "end_time": 1586661849642,
                "error_log": "/var/lib/ambari-agent/data/errors-895.txt",
                "exit_code": 0,
                "host_name": "wn22-excels.mm2brxx0l2ouvbv4fwbleiff3e.hx.internal.cloudapp.net",
                "id": "895",
                "output_log": "/var/lib/ambari-agent/data/output-895.txt",
                "request_id": "227",
                "role": "run_customscriptaction",
                "stage_id": "0",
                "start_time": 1586661847186,
                "status": "FAILED",
                "stderr": null,
                "stdout": null,
                "structured_out": null
            }
        },
        {
            "href": "http://hn0-excels.mm2brxx0l2ouvbv4fwbleiff3e.hx.internal.cloudapp.net:8080/api/v1/clusters/excelspark/requests/227/tasks/896",
            "Tasks": {
                "attempt_cnt": 1,
                "command": "ACTIONEXECUTE",
                "command_detail": "run_customscriptaction ACTIONEXECUTE",
                "end_time": 1586661849683,
                "error_log": "/var/lib/ambari-agent/data/errors-896.txt",
                "exit_code": 0,
                "host_name": "wn38-excels.mm2brxx0l2ouvbv4fwbleiff3e.hx.internal.cloudapp.net",
                "id": "896",
                "output_log": "/var/lib/ambari-agent/data/output-896.txt",
                "request_id": "227",
                "role": "run_customscriptaction",
                "stage_id": "0",
                "start_time": 1586661847187,
                "status": "FAILED",
                "stderr": null,
                "stdout": null,
                "structured_out": null
            }
        }
    ]
}
```

**Comment by imback82** [comment]
Hmm the logs don't seem to be useful. Did you try the one in #470?

**Comment by imback82** [comment]
Btw, HDInsight currently comes with Microsoft.Spark.Worker 0.8.0 version by default, so if you are using the script action to install worker, you can skip it and use 0.8.0 Nuget version to test it out.

**Comment by elvaliuliuliu** [comment]
@yuejli Can you also share the HDI Spark version and the parameters you use to submit script action (as @imback82 mentioned)?

**Comment by yuejli** [comment]
Sure. The HDI Spark version is Spark 2.4 (HDI 4.0), and the parameters are
```
azure wasbs://excelanalysis.blob.core.windows.net/excelspark-2020-04-08/Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-0.10.0.tar.gz /usr/local/bin

**Comment by yuejli** [comment]
> 
> 
> Btw, HDInsight currently comes with Microsoft.Spark.Worker 0.8.0 version by default, so if you are using the script action to install worker, you can skip it and use 0.8.0 Nuget version to test it out.

@imback82 Do you mean that I should install `Microsoft.Spark` with verision 0.8.0 and skip the “install-worker.sh step”, and directly go to ssh and run app with `spark-submit`?

**Comment by elvaliuliuliu** [comment]
@yuejli : I am able to submit the script action successfully. Can you share the stderr and stdout log from ambari as below?
![image](https://user-images.githubusercontent.com/47404285/79061705-a6babe80-7c47-11ea-903d-9d95efb6c1eb.png)

**Comment by elvaliuliuliu** [comment]
> > Btw, HDInsight currently comes with Microsoft.Spark.Worker 0.8.0 version by default, so if you are using the script action to install worker, you can skip it and use 0.8.0 Nuget version to test it out.
> 
> @imback82 Do you mean that I should install `Microsoft.Spark` with verision 0.8.0 and skip the “install-worker.sh step”, and directly go to ssh and run app with `spark-submit`?

@yuejli : Right, If you are not requesting to use the feature in 0.8.0 version above, you can skip the install-work.sh step, and submit your app with microsoft-spark-2.4.x-0.8.0.jar.

**Comment by yuejli** [comment]
> 
> 
> @yuejli : I am able to submit the script action successfully. Can you share the stderr and stdout log from ambari as below?
> ![image](https://user-images.githubusercontent.com/47404285/79061705-a6babe80-7c47-11ea-903d-9d95efb6c1eb.png)

@elvaliuliuliu So how can I find this task log from ambari?

**Comment by elvaliuliuliu** [comment]
> > @yuejli : I am able to submit the script action successfully. Can you share the stderr and stdout log from ambari as below?
> > ![image](https://user-images.githubusercontent.com/47404285/79061705-a6babe80-7c47-11ea-903d-9d95efb6c1eb.png)
> 
> @elvaliuliuliu So how can I find this task log from ambari?

@yuejli : Please see my updated comments with instructions as above. Feel free to let me know if any questions.

**Comment by yuejli** [comment]
> 
> 
> > > @yuejli : I am able to submit the script action successfully. Can you share the stderr and stdout log from ambari as below?
> > > ![image](https://user-images.githubusercontent.com/47404285/79061705-a6babe80-7c47-11ea-903d-9d95efb6c1eb.png)
> > 
> > 
> > @elvaliuliuliu So how can I find this task log from ambari?
> 
> @yuejli : Please see my updated comments with instructions as above. Feel free to let me know if any questions.

@elvaliuliuliu Thanks a lot! Here is the copy of the error
```
stderr: 
get: `wasbs://excelanalysis.blob.core.windows.net/excelspark-2020-04-08/Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-0.10.0.tar.gz': No such file or directory
tar (child): /tmp/temp_worker.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
chmod: cannot access '/usr/local/bin/spark-dotnet/Microsoft.Spark.Worker-0.10.0/Microsoft.Spark.Worker': No such file or directory
rm: cannot remove '/tmp/temp_worker.tgz': No such file or directory
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 209, in <module>
    ExecuteScriptAction().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 191, in actionexecute
    ExecuteScriptAction.execute_bash_script(bash_script, scriptpath, scriptparams)
  File "/var/lib/ambari-agent/cache/custom_actions/scripts/run_customscriptaction.py", line 158, in execute_bash_script
    raise Exception("Execution of custom script failed with exit code",exitcode)
Exception: ('Execution of custom script failed with exit code', 1)
 ```
 and the stdout is 
```
stdout:
('Start downloading script locally: ', u'https://excelanalysis.blob.core.windows.net/excelspark-2020-04-08/install-worker.sh')
Fromdos line ending conversion successful
('Unexpected error:', "('Execution of custom script failed with exit code', 1)")
Removing temp location of the script

Command failed after 1 tries
```
Seems like it didn't find the `Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-0.10.0.tar.gz`. But I have checked my contianer and it is over there.

**Comment by yuejli** [comment]
@imback82 @elvaliuliuliu Thanks a lot, I have found the reason. The parameters for script action is wrong. I directly use the copy of the uri of `Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-0.10.0.tar.gz` from the property of it in azure storage explorer. But the right format is wasbs://containername@... After changing this, it worked!
