### ISSUE TITLE
%SPARK_HOME%\bin\spark-submit --version

### ISSUE THREAD

**Issue by PAPIPANNE** [dotnet/spark#487]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by elvaliuliuliu** [comment]
@PAPIPANNE ：Can you provide more details on the problem you encounter? Thanks.

**Comment by imback82** [comment]
This must be related to #488. Closing.
