### ISSUE TITLE
'spark-submit' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by PAPIPANNE** [dotnet/spark#488]
I ran this commands to set environment variables 
setx HADOOP_HOME C:\bin\spark-2.4.1-bin-hadoop2.7\
setx SPARK_HOME C:\bin\spark-2.4.1-bin-hadoop2.7\

then ran this command to check if everything is installed correctly
%SPARK_HOME%\bin\spark-submit --version

but i get this error :
C:\WINDOWS\system32>spark-submit --version
'spark-submit' is not recognized as an internal or external command,
operable program or batch file.

**Comment by elvaliuliuliu** [comment]
Can you try `%SPARK_HOME%\bin\spark-submit --version` as shown in the [get-started tutorial](https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark)?

**Comment by PAPIPANNE** [comment]
>%SPARK_HOME%\bin\spark-submit --version
The system cannot find the path specified.

**Comment by imback82** [comment]
Can you check if you can run `java`?

**Comment by PAPIPANNE** [comment]
>jAVA
Usage: java [-options] class [args...]
           (to execute a class)
   or  java [-options] -jar jarfile [args...]
           (to execute a jar file)
where options include:
    -d32          use a 32-bit data model if available
    -d64          use a 64-bit data model if available
    -server       to select the "server" VM
                  The default VM is server.

    -cp <class search path of directories and zip/jar files>
    -classpath <class search path of directories and zip/jar files>
                  A ; separated list of directories, JAR archives,
                  and ZIP archives to search for class files.
    -D<name>=<value>
                  set a system property
    -verbose:[class|gc|jni]
                  enable verbose output
    -version      print product version and exit
    -version:<value>
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  require the specified version to run
    -showversion  print product version and continue
    -jre-restrict-search | -no-jre-restrict-search
                  Warning: this feature is deprecated and will be removed
                  in a future release.
                  include/exclude user private JREs in the version search
    -? -help      print this help message
    -X            print help on non-standard options
    -ea[:<packagename>...|:<classname>]
    -enableassertions[:<packagename>...|:<classname>]
                  enable assertions with specified granularity
    -da[:<packagename>...|:<classname>]
    -disableassertions[:<packagename>...|:<classname>]
                  disable assertions with specified granularity
    -esa | -enablesystemassertions
                  enable system assertions
    -dsa | -disablesystemassertions
                  disable system assertions
    -agentlib:<libname>[=<options>]
                  load native agent library <libname>, e.g. -agentlib:hprof
                  see also, -agentlib:jdwp=help and -agentlib:hprof=help
    -agentpath:<pathname>[=<options>]
                  load native agent library by full pathname
    -javaagent:<jarpath>[=<options>]
                  load Java programming language agent, see java.lang.instrument
    -splash:<imagepath>
                  show splash screen with specified image
See http://www.oracle.com/technetwork/java/javase/documentation/index.html for more details.

**Comment by imback82** [comment]
How about `C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit`?

**Comment by PAPIPANNE** [comment]
>C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit
The system cannot find the path specified.

>echo C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit
C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit

**Comment by elvaliuliuliu** [comment]
Can you please refer to #304 and give it a try?

**Comment by imback82** [comment]
@PAPIPANNE please reopen this issue if the suggestion by @elvaliuliuliu didn't work.
