### ISSUE TITLE
Apache Spark Problem

### ISSUE THREAD

**Issue by BhanumathiSubramanian** [dotnet/spark#492]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

While running the following code: **%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll**

The final step showed me error **java.lang.ClassNotFoundException: org.apache.spark.deploy.dotnet.DotnetRunner.**

Regards,
Bhanu

**Comment by elvaliuliuliu** [comment]
Could you share the full log?

**Comment by BhanumathiSubramanian** [comment]
Hi...

Please find the below given complete error log

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform
(file:/C:/bin/spark-2.4.1-bin-hadoop2.7/jars/spark-unsafe_2.11-2.4.1.jar)
to method java.nio.Bits.unaligned()
WARNING: Please consider reporting this to the maintainers of
org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal
reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/04/23 00:13:09 WARN NativeCodeLoader: Unable to load native-hadoop
library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile:
org/apache/spark/log4j-defaults.properties
20/04/23 00:13:09 WARN DependencyUtils: Local jar
C:\Users\bhanumathi.s\mySparkApp\bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar
does not exist, skipping.
20/04/23 00:13:09 WARN SparkSubmit$$anon$2: Failed to load
org.apache.spark.deploy.dotnet.DotnetRunner.
java.lang.ClassNotFoundException:
org.apache.spark.deploy.dotnet.DotnetRunner
        at
java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:415)
        at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
        at org.apache.spark.deploy.SparkSubmit.org
$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
        at
org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
        at
org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at
org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
20/04/23 00:13:09 INFO ShutdownHookManager: Shutdown hook called
20/04/23 00:13:09 INFO ShutdownHookManager: Deleting directory
C:\Users\bhanumathi.s\AppData\Local\Temp\spark-af2c56ad-fac8-41a1-93aa-d34cf4a7b2fd

Regards,
Bhanu

**Comment by Niharikadutta** [comment]
@BhanumathiSubramanian Can you please verify if the `microsoft-spark-2.4.x-0.10.0.jar` is present in `bin\Debug\netcoreapp3.1\`? How did you build the jar? Please look for this jar in `src\scala\microsoft-spark-2.4.x\target\` folder.

**Comment by imback82** [comment]
I see that
```
C:\Users\bhanumathi.s\mySparkApp\bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar
does not exist, 
```

**Comment by BhanumathiSubramanian** [comment]
Nope. Its available. C:\Users\bhanumathi.s\mySparkApp\bin\Debug\netcoreapp2.1\microsoft-spark-2.3.x-0.10.0.jar

but the version of .NET Core is 2.1. Will this work with only 3.1 ? Please let me know.

**Comment by elvaliuliuliu** [comment]
> Nope. Its available. C:\Users\bhanumathi.s\mySparkApp\bin\Debug\netcoreapp2.1\microsoft-spark-2.4.x-0.10.0.jar
> 
> but the version of .NET Core is 2.1. Will this work with only 3.1 ? Please let me know.

Please use .NET Core 3.1.

**Comment by BhanumathiSubramanian** [comment]
ok..will try to upgrade my .net version and check

**Comment by imback82** [comment]
For the example you are running, .NET Core 2.1 should work fine. Just make sure that the jar is present. And please feel free to reopen the issue if something doesn't work.

**Comment by BhanumathiSubramanian** [comment]
Hi All...Thanks it is working fine with .NET Core 3.1...Thank you all.
