### ISSUE TITLE
after set the environment variable as SPARK_HOME with path as  C:\bin\spark-2.4.1-bin-hadoop2.7\ and try to run command as %SPARK_HOME%\bin\spark-submit --version i get this message as "The system cannot find the path specified."  where when i do echo on cmd its prints this path as why its giving this error not getting kindly suggest please in this regards.

### ISSUE THREAD

**Issue by ashishambekar018** [dotnet/spark#496]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by imback82** [comment]
Can you check #304?

**Comment by ashishambekar018** [comment]
please find below details if anything required please let me know

operating system -  windows 10 home single edition
-----------------------------------------------------------------------------------
java version install as below after running command java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_201\bin
------------------------------------------------------------------------------------
after setting SPARK_HOME variable and HADOOP_HOME variable I run the command as below
ECHO %SPARK_HOME% ----  C:\bin\spark-2.4.1-bin-hadoop2.7\
echo %HADOOP_HOME% ---- C:\bin\spark-2.4.1-bin-hadoop2.7\

**Comment by ashishambekar018** [comment]
after setting all the things as mentioned above still i getting the same as below 

%SPARK_HOME%\bin\spark-submit --version
The system cannot find the path specified.

can anyone suggest me

**Comment by Niharikadutta** [comment]
@ashishambekar018  Could you please try the following steps:

1. Set JAVA_HOME to C:\Program Files\Java\jdk1.8.0_201 (removing the bin)
2. Set HADOOP_HOME to the parent directory of where you saved winutils.exe (and not spark as you are doing currently).
3. Please check if you find spark-submit.cmd in the folder C:\bin\spark-2.4.1-bin-hadoop2.7\bin

Please try after setting the above as mentioned and let us know if you still see any issues.

**Comment by ashishambekar018** [comment]
echo %JAVA_HOME%
C:\Program Files\Java\jdk1.8.0_201
echo %HADOOP_HOME%
C:\bin\hadoop
echo %SPARK_HOME%
C:\bin\spark-2.4.1-bin-hadoop2.7\
%SPARK_HOME%\bin\spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.4.1
      /_/

I GUESSS IT WORKS 

THANKS A LOT NIHARIKA

WHAT NEXT TO BE DONE IF ANYTHING LEFT AND HOW CAN I START WITH IT CAN U TELL ME

**Comment by Niharikadutta** [comment]
Please take a look at [getting started docs](https://github.com/dotnet/spark/blob/master/docs/getting-started/windows-instructions.md ) for further steps.

**Comment by imback82** [comment]
Closing this as the original issue has been resolved.
