### ISSUE TITLE
[BUG]: The Udf() member of Spark should be a property, not a method

### ISSUE THREAD

**Issue by saveenr** [dotnet/spark#498]
Here's the PySpark

`spark.udf.register("UDF_MyUpper", UDF_MyUpper)`

Here's what I have to do with .NET for Spark

`spark.Udf().Register<string, string>("UDF_MyUpper", Helpers.MyUpper);`

It should instead work like this:

`spark.Udf.Register<string, string>("UDF_MyUpper", Helpers.MyUpper);`

**Comment by imback82** [comment]
We tried to mirror the Scala APIs and we used a function on C# side if the Scala side is a `def` even if it's a `def` without parenthesis (and use a property if the Scala side is a `val`):
```
  def udf: UDFRegistration = sessionState.udfRegistration
```

But I am open for a discussion for a `def` without parenthesis. @rapoth / @suhsteve What do you think?

**Comment by rapoth** [comment]
@imback82 Yes, in my opinion, we can handle `def` without parenthesis similar to how we handle `val`. We should support both APIs for the time being to ensure backward compatibility. We can get rid of the `Udf()` API when we release v1.0.

**Comment by imback82** [comment]
Some APIs like `SparkSession.read` is also a `def` without parenthesis. So to be consistent, `def` on Scala will be mapped to a method in C# regardless whether it has parenthesis or not.
