### ISSUE TITLE
Implementation Question

### ISSUE THREAD

**Issue by GoEddie** [dotnet/spark#500]
Hi,

In the ML API each (most/all?) of the classes implement `Identifiable` (https://spark.apache.org/docs/latest/api/java/org/apache/spark/ml/util/Identifiable.html) and `Params` (https://spark.apache.org/docs/1.5.1/api/java/org/apache/spark/ml/param/Params.html).

Is it preferred to re-implement these on every class or use a base class to implement the shared code? 

For a base class implementation, is something like this ok? 

https://github.com/GoEddie/spark/blob/ml/missing-methods/src/csharp/Microsoft.Spark/ML/Feature/FeatureBase.cs

Ed

**Comment by imback82** [comment]
Do you have an example code that utilizes `FeatureBase.cs`? I think this is the right direction.

**Comment by GoEddie** [comment]
Thanks @imback82 I have added started to add it to Bucketizer:

https://github.com/GoEddie/spark/blob/ml/missing-methods/src/csharp/Microsoft.Spark/ML/Feature/Bucketizer.cs#L23

**Comment by imback82** [comment]
Looks reasonable to me. Do you want to create a PR that utilizes `FeatureBase` for the existing classes?

**Comment by GoEddie** [comment]
yep will do, thanks!
