### ISSUE TITLE
[FEATURE REQUEST]: Expose exceptions

### ISSUE THREAD

**Issue by michael-damatov** [dotnet/spark#502]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when any exception I get is an `Exception`. For example, when reading a delta file fails, I do not know why: it could be a concurrency error, or, simply, the file doesn't exist. Reading/parsing the exception text is not a viable option.

**Describe the solution you'd like**
Please introduce more exception types and extend the documentation on methods to describe what exceptions could be thrown.

**Comment by michael-damatov** [comment]
possible duplicate of #472

**Comment by imback82** [comment]
@michael-damatov Would #472 address your issue, or do you need more info? You can help reviewing the PR as well.

**Comment by michael-damatov** [comment]
Simply throwing `JvmException` instead of `Exception` does not help to distinguish between different cases.

#472 is definitely not a duplicate of this issue.

**Comment by imback82** [comment]
https://github.com/dotnet/spark/issues/472#issuecomment-643057149 would not be enough? Exposing more exception types is not a scalable solution.

**Comment by michael-damatov** [comment]
I do not expect from an exception to be scalable because it has already been thrown. I'm pretty sure that the scala code somehow distinguish between exceptions: either by using different exception types or by providing additional properties (e.g. "error code").

If the `JvmException` added with #472 would expose additional properties, which are helpful to distinguish between different cases, it would be enough.

**Comment by rapoth** [comment]
Since #566 has been merged, I am closing this issue. Please feel free to re-open if it has not answered your question.
