### ISSUE TITLE
Not able to use async functions in UDF

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#504]
my UDF calls a helper function, which gets some data from external API call, if i declare the helper functions as async, and put await. it doesn't wait for it's completion and exit immediately.

 can i use C# async/await functions in my code running on spark.

Thanks

**Comment by Niharikadutta** [comment]
Can you share your code snippet where you are using the `async` function and calling `await`? The `await` operator doesn't block the thread that evaluates the `async` method, ([refer](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await)), so for the control to exit immediately is normal. If you want the control to wait till your helper function finishes executing, please consider calling `Wait` or `Result` on the Task.

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
