### ISSUE TITLE
[BUG]: Not able to return error from UDF

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#518]
i have a UDF  used in a Batch job(not streaming) which does one time initialization of reading some config data from blob storage and then run for each row. If there is some exception in initialization function of UDF,  it still continues with rest of my job.
Even if my UDF has throw, still my mail job continue with rest of the steps and don't fail the job.
How can i return error from my UDF, so that.

- my job doesn't continue with rest of step. It should not update checkpoint.
- spark should show job as failed. Presently it shows job as success.

```
var inputDataDF = GetInputData();
var myUDF= Functions.Udf<Row, string>(row => myClass.MyFunc(row, captureconfigName));               

var allColumns = inputDataDF.Columns().ToArray<string>();                

 // create a column attribute with all data
var rowModelDF = rowModelDF.WithColumn("RowData", Functions.Struct(allColumns[0], allColumns.Skip(1).ToArray<string>()));                

// call UDF to get response as json string
var udfResponseDF = rowModelDF.Select(calc(Functions.Column("RowData")).As("JsonResult"));


Checkpoint();  // I don't want this to be called if my UDF initialization is failed
```
 below is UDF code
```
public string MyFunc(Row rowData, string captureconfigName)
{
 try
  {
      if(!initialized)
      {
        loadBlob(captureconfigName)
       }
 // process
  return response;
  }
   catch(exception)
    {
      throw;  // if loadblob fails i throw exception by still my job continue
    }
 }

**Comment by imback82** [comment]
I am a bit confused.

```
// call UDF to get response as json string
var udfResponseDF = rowModelDF.Select(calc(Functions.Column("RowData")).As("JsonResult"));
```

When you run above, your dataframe is not materialized since `Select` is a transformation, not an action. Thus, the UDF doesn't run yet.

So by the it reaches `CheckPoint` below, it's expected that UDF didn't run.

```
Checkpoint();  // I don't want this to be called if my UDF initialization is failed
```

**Comment by guruvonline** [comment]
in my checkpoint i have action to save UDF response DataFrame into table and inserts  current checkpoint datetime into checkpoint table (to indicate till that datetime records are processed).
 When my UDF executes(on saving to delta table) if there is error I was expecting it should not save into checkpoint table. my driver code is like

try
{
   read();
   calludf() ;
// i want when UDF executes and throws exception, driver should  should go to catch block and not // save in checkpoint table
    savetable(); 
}
catch()
{
}

**Comment by imback82** [comment]
The following works as expected (prints "exception thrown"):
```C#
    class Program
    {
        static void Main(string[] args)
        {
            var spark = SparkSession.Builder().GetOrCreate();
            var df = spark.CreateDataFrame(new int[] { 1 });
            var udf = Functions.Udf<int, string>(i => throw new Exception());
            try
            {
                df.Select(udf(df["_1"])).Show();
                Console.WriteLine("should not reach here");
            }
            catch (Exception e)
            {
                Console.WriteLine("exception thrown");
            }
        }
    }
```
You may want to share a simplest example to repro.

**Comment by Niharikadutta** [comment]
@guruvonline Are you still facing this issue? Please let us know if you can provide a repro or need any further assistance. Thanks!

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
