### ISSUE TITLE
SPARK_VERSION_OVERRIDE rename request to use DOTNET suffix 

### ISSUE THREAD

**Issue by thrajput** [dotnet/spark#519]
SPARK_VERSION_OVERRIDE rename request to use DOTNET suffix

**Comment by suhsteve** [comment]
I was thinking about this.  Should we standardize all our ENV variable names with the same prefixes ?  @imback82 @Niharikadutta  what do you think ?

ie, 
`DOTNET_SPARK_`   or  `SPARK_DOTNET_`

**Comment by Niharikadutta** [comment]
I think we should do that, either looks fine to me.

**Comment by imback82** [comment]
We can do `DOTNET_SPARK_`, but let's make sure the backward compatibility (support two env variables for the time being).

**Comment by rapoth** [comment]
Closing this issue.
