### ISSUE TITLE
Cosmos and Couchbase Spark Connector

### ISSUE THREAD

**Issue by SumitMeh** [dotnet/spark#520]
I tried using Couchbase 6.0.2 as a sink for Dataframe using [Couchbase Spark connector v2.4.0](https://docs.couchbase.com/spark-connector/2.4/download-links.html).
There was no error but nothing was written to Couchbase either.
`var dictionary = new Dictionary<string, string>
            {
                {"spark.couchbase.nodes", "127.0.0.1:8091"},
                {"spark.couchbase.username", "<uname>"},
                {"spark.couchbase.password", "<pwd>"},
                {"spark.couchbase.bucket.<bucketName>", ""}
            };`
`
fileDataFrame.Write()
                .Format("com.couchbase.spark.sql.DefaultSource")
                .Options(dictionary);`
Attaching Spark output.
[SparkOutput.txt](https://github.com/dotnet/spark/files/4628116/SparkOutput.txt)
Is there any connector available for such scenario or anything wrong that i'm doing?
Same is with Cosmos DB, while using com.microsoft.azure:azure-cosmosdb-spark_2.4.0_2.11:1.3.5

**Comment by imback82** [comment]
@SumitMeh did you call `Save()` at the end? `fileDataFrame.Write().Format("com.couchbase.spark.sql.DefaultSource") .Options(dictionary).Save();`

Otherwise, I don't see anything wrong on the Spark .NET side in the output file as you mentioned. Can you double check if the settings are correct (I am not familiar with this connector, so you may want to reach out the devs for the connector)? Thanks.

**Comment by SumitMeh** [comment]
If i remember corretly, i did tried `Save()` but it expected it with parameter which is `table` and table doesn't makes sense with NoSQL. Anyways i will try `Save` again both with and without parameter and share exact logs. If that helps identifying issue then great else will reach out to devs for the connector as suggested by you.

**Comment by imback82** [comment]
Well, without `Save()` you are not performing any action, but just building `DataFrameWriter`. If I look at the connector API, you have to do the following for Scala: `people.write.couchbase(Map("idField" -> "uid"))`.  However, the `couchbase` eventually calls `Save()`:
https://github.com/couchbase/couchbase-spark-connector/blob/master/src/main/scala/com/couchbase/spark/sql/DataFrameWriterFunctions.scala#L30-L44
So I am not sure what you mean by taking in a `table` parameter.

**Comment by SumitMeh** [comment]
For Cosmos DB, i was missing `Mode(SaveMode.Append)` without mode it gave 
`JVM method execution failed: Nonstatic method 'save' failed for class '33' when called with no arguments`.
So, changed code to 
` fileDataFrame.Write()
                .Format("com.microsoft.azure.cosmosdb.spark")
                .Options(dictionary)
                .Mode(SaveMode.Append)
                .Save();`
along with using package `com.microsoft.azure:azure-cosmosdb-spark_2.4.0_2.11:1.4.0` instead of `com.microsoft.azure:azure-cosmosdb-spark_2.4.0_2.11:1.3.5`(this has JsonFormat bug).
Still, trying out for Couchbase. Will update once succeeded.
Thanks for your time @imback82 !
