### ISSUE TITLE
'spark-submit' is not recognized as the name of a cmdlet, function

### ISSUE THREAD

**Issue by Rajeev2011J** [dotnet/spark#532]
Getting below error 

PS C:\Rajeev\Spark\QueryBase\bin\Debug\netcoreapp3.1> spark-submit --class org.apache.spark.deploy.dotnet.DotnetR
unner --master local microsoft-spark-2.4.x-0.10.0.jar dotnet QueryBase.dll
spark-submit : The term 'spark-submit' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --ma ...
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (spark-submit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by imback82** [comment]
Can you use full path to `spark-submit`? Most likely, env vars are not set up correctly.

**Comment by Rajeev2011J** [comment]
Hi,

Thanks for yours reply.

I already used full-path as well. I am trying to execute the same using Terminal window inside VS 2019.

All the Env vars are setup correctly.

Thanks,
Rajeev

**Comment by imback82** [comment]
What error message do you get if you run it under cmd instead of powershell?

**Comment by Niharikadutta** [comment]
Hi @Rajeev2011J , are you still facing this issue?

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
