### ISSUE TITLE
How can I submit my .NET Spark job via Apache Livy?

### ISSUE THREAD

**Issue by daxnet** [dotnet/spark#533]
Is it possible to submit my .NET for Spark job via Apache Livy? How can I do that?
From the official documentation I can only see the instructions related to HDInsight, what if I just want to use my local-deployed Spark cluster?
Thanks so much.

**Comment by imback82** [comment]
Yes. For a batch submission, you can do something similar to https://github.com/dotnet/spark/blob/96d0fedb13a9cdfa18f8a58b193341b71467e99f/deployment/README.md#using-apache-livy. If you have a specific issue you are encountering, please let us know.

**Comment by daxnet** [comment]
Hi @imback82 
Thank you so much for the reply. Yes, I know that it is possible for Azure HDInsight, however, I have my local deployed Spark cluster with Livy as the REST service, can I submit the .NET for spark job by using the Livy endpoint like `POST http://local-livy:8998/sessions/0/statements`?
Thanks and regards.

**Comment by suhsteve** [comment]
The livy endpoint `POST http://local-livy:8998/sessions/0/statements` would an interactive session, which is not supported out of the box.  What @imback82 is referring to would be the batches endpoint `POST http://local-livy:8998/batches` .

**Comment by daxnet** [comment]
@suhsteve oh, ok, thanks. Now I am clear.
Thanks.
