### ISSUE TITLE
[FEATURE REQUEST]: run debugger as a process

### ISSUE THREAD

**Issue by mikeTWC1984** [dotnet/spark#539]
**Is your feature request related to a problem? Please describe.**

I'm trying to adopt .net spark to use with powershell. It's actually works great. Powershell need to submit debugger first, which you can do manually within interactive shell. However this is very inconvenient. I'd like powershell to start debugger automatically. The problem is that debugger can only run in interactive shell. If you run command below as a child process it will quit righ after "press enter" message

```
 spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner microsoft-spark-2.4.x-0.10.0.jar debug
```
There are some hacky ways to emulate interactive shell in the background, but if debugger can run as foreground process it would solve the problem. It would also be helpful for containerizing it.

Other option is to start debugger somehow automatically. Say if you run ./net/powershell without submitting spark job, it will start looking for debugger and throw error. Instead it could start it automatically. So this way we can get similar experience to PySpark, it doesn't require to start debugger explicitly to run scripts

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mikeTWC1984** [comment]
Turns out it was easy fix (just commenting few lines). Will just use a custom version of this jar

**Comment by JavierLight** [comment]
Hi @mikeTWC1984 , could you please provide a more detailed description of your fix? I'm trying to containerize a simple dotnet app and can't get the debugger to work, because I need to run two interactive processes in the docker container entrypoint.

I'm using this to launch my `DotnetApp.dll` once the 5567 port is listening:

`( tail -f -n0 sparkdotnetdebug.log & ) | grep -q "Press enter to exit"`

Is there another way to execute code from this library in a dotnet DLL without the need of the debugger?

**Comment by mikeTWC1984** [comment]
@JavierLight  What I did just removed those 3 lines
https://github.com/dotnet/spark/blob/c8992e0787c6f50f2aa3572839fe67b872a3363a/src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala#L158-L160
Then you can stop debugger with ctrl+C. You can also use netstat (both windows and linux has it) to find out which process is listening on debug port and kill it. 
You would need to rebuild your target jar, but it's fairly simple (there are instructions on this repo, as far as I remember you just need jdk and maven)
