### ISSUE TITLE
[FEATURE REQUEST]: DataFrame options method to support hashtable (for powershell)

### ISSUE THREAD

**Issue by mikeTWC1984** [dotnet/spark#540]
**Is your feature request related to a problem? Please describe.**

Currently DataFrameReader Options method only takes string/string dictionary. Using this with powershell gets a bit cumbersome, since there is no literal for that:
```powershell
$opt = [System.Collections.Generic.Dictionary[String,String]]::new()
$opt.Add("url", $myUrl)
$opt.Add("dbtable", $table)
$opt.Add("driver", $driver)
$df = $spark.Read().Format("jdbc").Options($opt).Load()
```
Powershell uses hashtable as primary key/value storage. Adopting this would make above snippet look way more natural:
```powershell
$df = $spark.Read().Format("jdbc").Options(@{
    url = $myUrl
    dbtable = $table
    driver = $driver
}).Load()
```

hashtable is not generic, but it shouldn't be a problem to convert keys and values to strings. 

*  @{ } is a literal for System.Collections.HashTable

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by suhsteve** [comment]
I have some mixed feelings regarding this enhancement request. Adding this feature would open the gates to add the same enhancement to any other public API that uses Dictionary, doubling the public API footprint for those types of methods.

**Comment by mikeTWC1984** [comment]
Ok, what about just System.Collection.IDictionary,  it would cover plethora of other datastructures, including hashtable? I guess it's not a big deal anyway. At this point the killer for powershell is debugger (see my previous issue)

**Comment by imback82** [comment]
`IDictionary` sounds fine to me since it will be a non-breaking change. @mikeTWC1984 do you want to contribute? You can update both `DataFrameReader.Options` and `DataFrameWriter.Options`.

**Comment by suhsteve** [comment]
`IDictionary` sounds good.  Modifications to [PayloadHelper.cs](https://github.com/dotnet/spark/blob/ce2317774c25550ea3784a1af4f02befd2eea70b/src/csharp/Microsoft.Spark/Interop/Ipc/PayloadHelper.cs#L352) may also be required.  @imback82

**Comment by imback82** [comment]
Do we need to change PayloadHelper? I was thinking to just change `Dictionary<string, string>` to `IDictionary<string, string>`, maybe I misunderstood the ask.

**Comment by suhsteve** [comment]
`Hashtable` implements `IDictionary`
`Dictionary` implements `IDictionary` and `IDictionary<TKey, TValue>`

Unless the Hashtable will be implicitly converted to a `IDictionary<Tkey, TValue>`, we may need to make changes to support `IDictionary`

**Comment by imback82** [comment]
I don't think we want to support `IDictionary` without types because we don't support all the types.

**Comment by mikeTWC1984** [comment]
Right, the ask was about non-generic IDictionary. New method would just convert it to Dictionary[string,sting] and pass to the existing one. This is truly for scripting convenience, if you thing this would clog api feel free to close the issue.

**Comment by mikeTWC1984** [comment]
I'll probably just start a fork to do those minor adjustments for powershell, since it won't be very useful for C# anyway
