### ISSUE TITLE
Example app name starts with an invalid character in k8s

### ISSUE THREAD

**Issue by JavierLight** [dotnet/spark#544]
**Describe the bug**

When using Kubernetes as the resource manager, the app name in the examples is incompatible with the spark requirements.

**To Reproduce**

Deploy any example using `.Master("k8s://k8s_IP:k8s_port")` 

From the spark doc:

> In Kubernetes mode, the Spark application name that is specified by spark.app.name or the --name argument to spark-submit is used by default to name the Kubernetes resources created like drivers and executors. So, application names must consist of lower case alphanumeric characters, -, and . **and must start and end with an alphanumeric character**.

**Expected behavior**
Run the examples using the desired resource manager, without the need of altering the example depending on the resource manager used.

**Comment by imback82** [comment]
Thanks for reporting this. Do you want to contribute? You can change `.NET Spark SQL basic example` to `SQL basic example using .NET for Apache Spark`, and so on. I see six occurrences total. Please let me know if you are interested in fixing them. Thanks!
