### ISSUE TITLE
[FEATURE REQUEST]: Azure-pipeline should use templates to remove duplicate setup

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#546]
The current `azure-pipeline.xml` has duplicate parts and is hard to maintain, esp. for running E2E tests (current, backward compatibility and forward compatibility).  It would help to maintain if they are refactored using templates.

**Comment by imback82** [comment]
cc: @elvaliuliuliu

**Comment by elvaliuliuliu** [comment]
I will work on this.

**Comment by Niharikadutta** [comment]
Can this be closed as per the PR #697 ?

**Comment by imback82** [comment]
Closed by #697
