### ISSUE TITLE
[BUG]: The Microsoft.Spark.Extensions.DotNet.Interactive extension incompatible with newest dotnet-interactive

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#552]
The `Microsoft.Spark.Extensions.DotNet.Interactive` extension is incompatible with the newest version of dotnet-interactive.  The [ISupportNuget](https://github.com/dotnet/interactive/blob/master/src/Microsoft.DotNet.Interactive/ISupportNuget.cs) has changed and the extension needs to be updated.

**Comment by imback82** [comment]
@jonsequitur I understand it's not a stable API, but how can we know when a breaking change is introduced? Do you have release notes, etc.?

**Comment by imback82** [comment]
Fixed by #554.
