### ISSUE TITLE
Run .NET spark application in GCP DataProc

### ISSUE THREAD

**Issue by deeptowncitizen** [dotnet/spark#553]
Hi
Is that possible to run .NET spark application in DataProc (Google Cloud)?
Did anyone do that?

thank you

**Comment by Niharikadutta** [comment]
Hi @deeptowncitizen , thank you for your question!
While we haven't personally tried .NET Spark on DataProc, it should certainly be possible given DataProc supports Apache Spark jobs (https://cloud.google.com/solutions/migration/hadoop/migrating-apache-spark-jobs-to-cloud-dataproc). Please go through the following [Get Started](https://github.com/dotnet/spark#get-started) docs and feel free to reach out to us in case of any questions or issues.
Also some good reference material would be the [official .NET for Apache Spark tutorials](https://dotnet.microsoft.com/learn/data/spark-tutorial/intro)

**Comment by deeptowncitizen** [comment]
@Niharikadutta thank you for pointing on this.
We're using .NET Spark with Nomad successfully for 1 year. And now migrating to DataProc.
I was able to make the same configuration and submit an empty job. Eventually, I'm getting the error:

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
	at org.apache.spark.deploy.dotnet.DotnetRunner$.<init>(DotnetRunner.scala:35)
	at org.apache.spark.deploy.dotnet.DotnetRunner$.<clinit>(DotnetRunner.scala)
	at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
```

I'm using `microsoft-spark-2.4.x-0.6.0`. While in DataProc I'm using 1.4.x that refers to [Spark 2.4.5](https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-1.4).

I was able to find a few similar issues here, but I don't see a reasonable solution. For others that was a versioning issue.

**Comment by Niharikadutta** [comment]
@deeptowncitizen Thanks for the information. I am curious as to what you mean by 'an empty job' and if the error has something to do with that. Please feel free to reach out to us and open an issue if there is something you need help with. Also we recommend using the latest .NET for Apache Spark release (v0.12.1) for a lot of new features and updates. Thanks!

**Comment by deeptowncitizen** [comment]
Still in progress with that.
1. There is no straight way to copy binaries to driver/executor instances using the [built-in](https://cloud.google.com/sdk/gcloud/reference/dataproc/jobs/submit/spark) functionality.
Parameters `--files` and `--archives` does not copy anything to driver instance, but executor. So this is not an option
2. The current option I'm testing is a bash script

```
gcloud dataproc jobs submit spark \
        --cluster=<cluster> \
        --region=<region> \
        --class=org.apache.spark.deploy.dotnet.DotnetRunner \
        --jars=gs://<bucket>/microsoft-spark-2.4.x-0.11.0.jar \
        -- /bin/sh -c "gsutil cp gs://<bucket>/builds/test.zip . && unzip -n test.zip && chmod +x ./Spark.Job.Test && ./Spark.Job.Test"
```
In this example `test.zip` contains the published .net artifacts, `Spark.Job.Test` - spark job output binary file.

The issue I'm trying to solve is how to run the spark job from the driver inside the script. Because the current approach is running the job as a simple application not connected with the driver
