### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by Jiacheng-Li** [dotnet/spark#557]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Hi

I was trying to follow the guide to install spark. I am pretty sure I set the environment variables correctly and put the files in the right directory. But I still get this message "The system cannot find the path specified". Would you mind helping me with it? I would really appreciate it!
![Path not found](https://user-images.githubusercontent.com/53215260/85220977-f0422b00-b3a7-11ea-93b5-09d870cf8d9a.PNG)
![Environment Varible](https://user-images.githubusercontent.com/53215260/85220978-f20bee80-b3a7-11ea-86b4-775ac44d0278.PNG)
![dir](https://user-images.githubusercontent.com/53215260/85220980-f3d5b200-b3a7-11ea-950e-205e6d90631c.PNG)

**Comment by suhsteve** [comment]
@Jiacheng-Li  can you do an `echo %SPARK_HOME%` ?  Your environment variable may not be set up correctly or you need to restart your command prompt.

**Comment by Jiacheng-Li** [comment]
Hi Steve

Just did it, here is the screenshot, does it seem to be correct?
![echo](https://user-images.githubusercontent.com/53215260/85221087-f684d700-b3a8-11ea-9c62-45d0c418b081.PNG)
Thanks!

**Comment by Jiacheng-Li** [comment]
I also tried restarting command prompt and my PC, still no luck.

**Comment by suhsteve** [comment]
@Jiacheng-Li that env variable path looks fine to me.   Can you try either of the following?

```ps
%SPARK_HOME%\bin\spark-submit.cmd --version
```
or
```ps
C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit.cmd
```

**Comment by Jiacheng-Li** [comment]
> @Jiacheng-Li that env variable path looks fine to me. Can you try either of the following?
> 
> ```postscript
> %SPARK_HOME%\bin\spark-submit.cmd --version
> ```
> 
> or
> 
> ```postscript
> C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit.cmd --version
> ```

Just tried, neither of them seems to work...
![Try submitcmd](https://user-images.githubusercontent.com/53215260/85221333-06051f80-b3ab-11ea-953f-c499cfcae86d.PNG)

**Comment by suhsteve** [comment]
Can you give me the output of `echo %JAVA_HOME%` ?  Can you make sure it's also set if it isn't ?

**Comment by Jiacheng-Li** [comment]
Btw I have also set the Path variable, still doesn't work... Not sure if this is relevant though.
![Path variable](https://user-images.githubusercontent.com/53215260/85221396-6e540100-b3ab-11ea-8287-6e6ec040d6fe.PNG)

**Comment by suhsteve** [comment]
This is probably relateed to #304 .  Can you try following the recommendations and see if they resolve your issue ?

**Comment by Jiacheng-Li** [comment]
> echo %JAVA_HOME%

Seems fine. I'm using Java 14.

C:\Users\Jiacheng Li>echo %JAVA_HOME%
C:\Program Files\Java\jdk-14.0.1\bin

**Comment by suhsteve** [comment]
@Jiacheng-Li please follow the [recommendation here](https://github.com/dotnet/spark/issues/304#issuecomment-545689563)

**Comment by Jiacheng-Li** [comment]
> This is probably relateed to #304 . Can you try following the recommendations and see if they resolve your issue ?

Hi Steve

Everything works fine now after getting rid of the "\bin" from JAVA_HOME.
Thanks so much for your help!

**Comment by evonniewu** [comment]
Hi all, 

I need help getting PySpark to work 

I had a running error for PySpark

D:\spark-3.1.2-bin-hadoop3.2\bin>pyspark
The system cannot find the path specified.
The system cannot find the path specified.

JAVA_HOME = C:\Program Files\Java\jdk1.8.0_291 
PATH = C:\Program Files\Java\jdk1.8.0_291\bin 

SPARK_HOME = D:\spark-3.1.2-bin-hadoop3.2 
PATH =  D:\spark-3.1.2-bin-hadoop3.2\bin

Have tried install and uninstall and tried different method just seem unable to work 

Would appreciate if anyone can help with this. 

Thank You

**Comment by kirangollamudi** [comment]
> Hi all,
> 
> I need help getting PySpark to work
> 
> I had a running error for PySpark
> 
> D:\spark-3.1.2-bin-hadoop3.2\bin>pyspark
> The system cannot find the path specified.
> The system cannot find the path specified.
> 
> JAVA_HOME = C:\Program Files\Java\jdk1.8.0_291
> PATH = C:\Program Files\Java\jdk1.8.0_291\bin
> 
> SPARK_HOME = D:\spark-3.1.2-bin-hadoop3.2
> PATH = D:\spark-3.1.2-bin-hadoop3.2\bin
> 
> Have tried install and uninstall and tried different method just seem unable to work
> 
> Would appreciate if anyone can help with this.
> 
> Thank You

For your JAVa, I think most people said, if you have it in a directory where there are NO spaces in the dir name, that should work.

I am in the same boat, not sure if you are successful in configuring it. If so, pls let me know what you did to solve it. Thanks!

**Comment by kirangollamudi** [comment]
> Hi all,
> 
> I need help getting PySpark to work
> 
> I had a running error for PySpark
> 
> D:\spark-3.1.2-bin-hadoop3.2\bin>pyspark
> The system cannot find the path specified.
> The system cannot find the path specified.
> 
> JAVA_HOME = C:\Program Files\Java\jdk1.8.0_291
> PATH = C:\Program Files\Java\jdk1.8.0_291\bin
> 
> SPARK_HOME = D:\spark-3.1.2-bin-hadoop3.2
> PATH = D:\spark-3.1.2-bin-hadoop3.2\bin
> 
> Have tried install and uninstall and tried different method just seem unable to work
> 
> Would appreciate if anyone can help with this.
> 
> Thank You


For your JAVa, I think most people said, if you have it in a directory where there are NO spaces in the dir name, that should work.

I am in the same boat, not sure if you are successful in configuring it. If so, pls let me know what you did to solve it. Thanks!

**Comment by swathi14-5** [comment]
The system cannot find the path specified. Can someone help me with this? I m working on Windows Os.

C:\Users\Honey>pyspark
The system cannot find the path specified.

C:\Users\Honey>echo %SPARK_HOME%
C:\Users\Honey\Documents\spark\spark-3.1.2-bin-hadoop2.7

C:\Users\Honey>%SPARK_HOME%\bin\spark-submit.cmd --version
The system cannot find the path specified.

C:\Users\Honey>C:\bin\spark-2.4.1-bin-hadoop2.7\bin\spark-submit.cmd --version
The system cannot find the path specified.

C:\Users\Honey>%SPARK_HOME%\bin\spark-submit.cmd --version
The system cannot find the path specified.

C:\Users\Honey>echo %JAVA_HOME%
C:\Program Files\Java\jdk-16.0.2

**Comment by suhsteve** [comment]
@evonniewu remove the \bin from your JAVA_HOME env var.

**Comment by suhsteve** [comment]
@swathi14-5 I'd suggest trying with java 8.

**Comment by swathi14-5** [comment]
> @swathi14-5 I'd suggest trying with java 8.

Sure Thank-you

**Comment by swathi14-5** [comment]
> @swathi14-5 I'd suggest trying with java 8.

Thank You it worked.

**Comment by swathi14-5** [comment]
Hi ,
I am getting the exception error while running spark commands. Spark installation was successful.
![Screenshot (21)](https://user-images.githubusercontent.com/77978493/128803221-4f3df51e-0a32-435a-8793-b3340172da2a.png)

![Screenshot (20)](https://user-images.githubusercontent.com/77978493/128803122-d3559e4d-3717-4c80-9293-5a5f42b7fed3.png)

**Comment by kks-git-hub** [comment]
> Hi ,
> I am getting the exception error while running spark commands. Spark installation was successful.
> ![Screenshot (21)](https://user-images.githubusercontent.com/77978493/128803221-4f3df51e-0a32-435a-8793-b3340172da2a.png)
> 
> ![Screenshot (20)](https://user-images.githubusercontent.com/77978493/128803122-d3559e4d-3717-4c80-9293-5a5f42b7fed3.png)

Pl try this video, https://www.youtube.com/watch?v=S5p-2vlUBYo&t=635s . it helped me. make sure you have JAVA8 installed. to me, that was the issue atleast.

**Comment by gowtham123456789** [comment]
when i installed spark on windows 10 and running spark-shell on command prompt it shows blinking and when i press control c it shows terminate batch job(Y/N), i tried many but it is not working, please help me

**Comment by saumyatiwari03** [comment]
Hi @suhsteve, I am facing the similar issue but my pyspark opens up. 

![image](https://github.com/dotnet/spark/assets/46890692/1718e08b-f200-4462-8ac7-d14767c3c873)

![image](https://github.com/dotnet/spark/assets/46890692/79b3e54a-debb-40d6-8905-b6edc79294c6)

PATH= 
![image](https://github.com/dotnet/spark/assets/46890692/26ff834a-a54d-48d8-8690-782704e25d91)


Spark-version: 3.5.0
Java-version: jdk-8u391
Python-version: python-3.9.11

Can someone please help me out?
