### ISSUE TITLE
Spark-class-launcher-output missed

### ISSUE THREAD

**Issue by jlagr** [dotnet/spark#559]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows 10

I followed all steps but when run sparl-submit --version I got this error:
![image](https://user-images.githubusercontent.com/19929590/85233387-60ae7380-b3cb-11ea-8ba9-3dc03578c8fd.png)
All environment variables looks good including JAVA_HOME. I tried changing permissions with winutil but didn't work.
Any idea?

**Comment by Niharikadutta** [comment]
Have you tried with specifying the full path to spark-submit?
Have all environment variables been set, such as PATH etc? Also can you check if the spark-submit.cmd file is marked executable in the SPARK_HOME/bin directory?

**Comment by jlagr** [comment]
Yes... but actually I figure out the issue, running the console as administrator works, even the missing file remains, sparks looks good, I don't know if the missing file will affect when code execution.

![image](https://user-images.githubusercontent.com/19929590/85298755-17613100-b46a-11ea-9548-6bca5c71aea0.png)

**Comment by Niharikadutta** [comment]
Good to see spark-submit is working, although you shouldn't have to run it in admin mode. I see the file path for `spark-class-launcher-output-4579.txt` looks strange, i.e. it does not have a root drive specified. Can you do an echo %temp% to see what value is set there and give the full path if it is not specified correctly?

**Comment by imback82** [comment]
I see that it's being run under `c:\windows\system32`, which requires you to have the admin mode since Spark will write to a folder under `c:\windows\system32`. Try running it under your user directory.

**Comment by jlagr** [comment]
Here is the result of eho %temp%
![image](https://user-images.githubusercontent.com/19929590/85339751-675fe800-b4aa-11ea-835d-052df8ac2799.png)

**Comment by Niharikadutta** [comment]
As @imback82 mentioned, can you confirm the value of %SPARK_HOME%? If your Spark is saved in `c:\windows\system32`, it would require admin privileges. Can you save the Spark folder in a user directory (set SPARK_HOME accordingly) and then try running?

**Comment by imback82** [comment]
I meant the working directory. Spark utilizes the current working directory for some configuration (like warehouse dir), thus it could lead to an issue with access regardless of where Spark is installed.

**Comment by Niharikadutta** [comment]
User was earlier running in the user directory, and there they were seeing Access denied, and couldn't run spark-submit --version, in order to get it to work, they ran console as admin.

**Comment by Niharikadutta** [comment]
@jlagr Are you facing any issues running spark-shell or submitting spark jobs with the missing output file error? Can you please confirm the location of SPARK_HOME once?

**Comment by daviddiazsolis** [comment]
Hi Im facing the same issue, I think it has to do with the space character in the User name (his name Jose Gonzalez), and as you can see from the picture the Temp folder is trying to open only recognizes the surname part (Diaz) and is missing the name (David). My windows user is David Diaz. I hope this helps in some way to find the solution.

**Comment by daviddiazsolis** [comment]
Hello again, the issue is definitely related to the temp directory. In my case the spark-class-launcher should be in C:\, so set temp=C:\temp for me solve the issue. Is there a better way to point to the "original" Temp folder?

**Comment by suhsteve** [comment]
Can you set the TEMP environment variable to a path without spaces ?

**Comment by daviddiazsolis** [comment]
if I set temp=C:\ set tmp=C:\ spark loads, but still gives me a warning translation would be "the name of the file, the name or the directory or syntaxis of the label volume it is not correct"

![image](https://user-images.githubusercontent.com/50603932/90164210-17dcc080-dd65-11ea-9bcc-436943c2de5c.png)


otherwise, I keep getting the error that the file C:\spark-class-launcher... can't be find

**Comment by Niharikadutta** [comment]
When you say 'original' temp folder, you mean the one with your user name (David Dias\AppData\Local\Temp)?
Also the warning you are getting about "the name of the file, the name or the directory or syntaxis of the label volume it is not correct", for spark-class-launcher-output-26326.txt right? Can you check if this file is present in your current temp directory (C:\)?

**Comment by daviddiazsolis** [comment]
Hi, yes, I mean the one with the user name David Diaz\AppData\Local\Temp

And now I have several spark-class-launcher files in my root folder:

![image](https://user-images.githubusercontent.com/50603932/90179801-03f08900-dd7c-11ea-9676-936148c2288d.png)

**Comment by Niharikadutta** [comment]
Sorry, what is the error you are seeing now with `C:\` as temp, since the spark-class-launcher files are there? Are you facing any issues running in Spark-shell?

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!

**Comment by madhupellete** [comment]
Guys

I am getting similar issue when I setting up spark in my windows machine.

![image](https://user-images.githubusercontent.com/63166800/95522474-3690b980-099a-11eb-9292-8351dd38c4ea.png)

Need help to fix this issue.

**Comment by Niharikadutta** [comment]
Is there anything that changed in your environment variables or installations between the time that it used to work and then stopped?

**Comment by madhupellete** [comment]
Hi Nihari,

Thanks for your response. I dont remember what changed suddenly one day spark didnt work in my system, I tried reinstalling everything again in my system but it didnt work. Now again trying to re-install python, something got corrupted now I am not able to uninstall python from my machine. Created support ticket to IT team to fix.

**Comment by Niharikadutta** [comment]
I see, I would recommend checking out your PATH environment variable and seeing if it has anything added to it you do not need or recognize and removing them one by one to see if that helps (do keep note of what you remove for later reference). Also make sure your JAVA_HOME is set correctly as per #557 and #304 ( and if the path has spaces try entering the shortened path as explained [here](https://confluence.atlassian.com/doc/setting-the-java_home-variable-in-windows-8895.html))

**Comment by RK-YADAV** [comment]
Hello All,

I am facing the same issue as above.
Reading through all the above it doesn't seem to be conclusive what i can try. Can someone please help been stuck here for a while.

![image](https://github.com/dotnet/spark/assets/85011874/127dc0ee-f4bb-4ccd-a505-c36e759f1c49)

**Comment by RK-YADAV** [comment]
![image](https://github.com/dotnet/spark/assets/85011874/953c84e8-8590-4c91-806a-bfadc3be7226)

This is the error while running from C:\
