### ISSUE TITLE
Add rows from URL

### ISSUE THREAD

**Issue by UncleJosef** [dotnet/spark#567]
When i Use
%%pyspark
df = spark\
    .read\
    .option('basePath', 'abfss://data@gallerydatadev.dfs.core.windows.net/crowd')\
    .parquet('abfss://data@gallerydatadev.dfs.core.windows.net/crowd/***/city=VLG/*/*.parquet**')
df.printSchema()
Result:
root
 |-- oid: long (nullable = true)
 |-- addedOn: timestamp (nullable = true)
 |-- addedOnDate: timestamp (nullable = true)
 |-- mac: string (nullable = true)
 |-- radarId: string (nullable = true)
 |-- face: string (nullable = true)
 |-- admTypeBit: integer (nullable = true)
 |-- **dt: date (nullable = true)**
 |-- **city: string (nullable = true)**
 |-- **player_id: integer (nullable = true)**
But, when I use 
%%csharp
using Microsoft.Spark.Sql;
string inputPath="abfss://data@gallerydatadev.dfs.core.windows.net/crowd/***/city=VLG/*/*.parquet**";
DataFrame rawData = spark.Read().Parquet(inputPath);
rawData.PrintSchema();
result:
root
root
 |-- oid: long (nullable = true)
 |-- addedOn: timestamp (nullable = true)
 |-- addedOnDate: timestamp (nullable = true)
 |-- mac: string (nullable = true)
 |-- radarId: string (nullable = true)
 |-- face: string (nullable = true)
 |-- admTypeBit: integer (nullable = true)
How do I view fields from a URL? really need!

**Comment by imback82** [comment]
Can you try setting the `basePath`?

**Comment by UncleJosef** [comment]
Yes! This is work.
root
 |-- oid: long (nullable = true)
 |-- addedOn: timestamp (nullable = true)
 |-- addedOnDate: timestamp (nullable = true)
 |-- mac: string (nullable = true)
 |-- radarId: string (nullable = true)
 |-- face: string (nullable = true)
 |-- admTypeBit: integer (nullable = true)
 |-- dt: date (nullable = true)
 |-- city: string (nullable = true)
 |-- player_id: integer (nullable = true)
But why is this not in the description and in the examples?

**Comment by imback82** [comment]
Which description / examples are you referring to? I just compared with your PySpark query to find the difference since you were seeing a different result. Putting `basePath` is just an option depending on your scenario, and not required.

Closing this for now, but feel free to reopen the issue. Thanks!

**Comment by imback82** [comment]
You can also check https://spark.apache.org/docs/latest/sql-data-sources-parquet.html#partition-discovery for all the configurations you can use.
