### ISSUE TITLE
[BUG]: DataFrameWriter Option isn't passing the key, only the value

### ISSUE THREAD

**Issue by GoEddie** [dotnet/spark#57]
**Describe the bug**

`DataFrameWriter.Option` takes a key and a value but DataFrameWriter is only passing on the value so the method can't be found.

**To Reproduce**

```csharp
            df.Write().Format("orc")
                .Option("orc.bloom.filter.columns", "favorite_color")
                .Option("orc.dictionary.key.threshold", 1.0)
                .Option("orc.column.encoding.direct", "name")
                .Mode(SaveMode.Overwrite)
                .Save("users_with_options.orc");
```

This causes:

"cannot find matching method class org.apache.spark.sql.DataFrameWriter.option. Candidates are:"

in DataFrameWriter we have:

```csharp
 public DataFrameWriter Option(string key, bool value)
        {
            _jvmObject.Invoke("option", value);
            return this;
        }
```
which I guess should be:

```csharp
 public DataFrameWriter Option(string key, bool value)
        {
            _jvmObject.Invoke("option", key, value);
            return this;
        }
```

There is one Option for each data type it supports.

**Expected behavior**

To be able to set individual options on the DataFrameWriter

**Comment by imback82** [comment]
Closed by #59
