### ISSUE TITLE
How to use map/reduce with DataFrame?

### ISSUE THREAD

**Issue by MikyChow** [dotnet/spark#579]
```
SparkSession spark = SparkSession
    .Builder()
    .AppName("word_count_sample")
    .GetOrCreate();
var input = spark.CreateDataFrame(new int[] {1, 2, 3, 4});
//I want execute map function to input like: input.map(x=>x*x)
spark.Stop();
```

I want execute map to input dataframe,but dataframe has no function named "map"

**Comment by Niharikadutta** [comment]
You cannot `map` a dataframe in Spark (`dataframe.map` has been removed since Spark 2.0), it is the attribute of an RDD. In order to do a `map` on a dataframe as outlined in your example, you can do the following:

`
input.Select("_1").Map(x => x*x);
`
Here `Select` converts the dataframe into an RDD on which the `map` is applied.

**Comment by imback82** [comment]
@Niharikadutta, `Select` return `DataFrame`, so I don't think your example would compile.

@MikyChow You can do something like the following:
```C#
var udf = Functions.Udf<int, int>(x => x * x);
df.Select(udf(df["_1"])).Show();
```

**Comment by MikyChow** [comment]
@imback82 @Niharikadutta  
```
var udf = Functions.Udf<int, int>(x => x * x);
df.Select(udf(df["_1"])).Show();

```
This still not worked.  And raise an exception: 
![image](https://user-images.githubusercontent.com/5389478/86684510-33053380-c035-11ea-9274-0f1fe047a60c.png)

Then i use this:
```
var squared = input.Select(input["_1"] * input["_1"]).Collect();

```
It's worked

**Comment by imback82** [comment]
You need to set up the worker to use UDF: https://github.com/dotnet/spark/blob/master/docs/deploy-worker-udf-binaries.md



> ```
> var squared = input.Select(input["_1"] * input["_1"]).Collect();
> ```
> 
> 
> It's worked

Yes, that works. I thought you wanted more like an UDF approach based on your example: `input.map(x=>x*x)`. Anyway, I am closing this issue now.
