### ISSUE TITLE
[FEATURE REQUEST]: ToString should return column expr

### ISSUE THREAD

**Issue by samueleresca** [dotnet/spark#594]
**Is your feature request related to a problem? Please describe.**

At the moment the default `Column.ToString` implementation returns the following:

```
Column("att1").ToString() == "Microsoft.Spark.Sql.Column";
```

The `Column.ToString` method uses the default implementation of the `Object` class. Do you think is sensible to return the column name / column expr every time the `Column.ToString` method is called?  

**Describe the solution you'd like**
The `Column.ToString` should return column expression:
```
Column("att1").ToString() == "att1";
Column("att1 > 1").ToString() == "att1 > 1";
```

**Additional context**

Something similar is present in [apache/spark ](https://github.com/apache/spark/blob/a4ca355af8556e8c5948e492ef70ef0b48416dc4/sql/core/src/main/scala/org/apache/spark/sql/Column.scala#L153)I think

**Comment by GoEddie** [comment]
We started discussing this exact thing here: https://github.com/dotnet/spark/issues/585

**Comment by GoEddie** [comment]
I can't add a label but this is a good first issue to implement, add a method to Column:

`public override string ToString() => (string)_jvmObject.Invoke("toString");`

and a test should do it (i'd probably include a comment to say that it doesn't return the value of the column as that is a pretty common misconception with spark)

**Comment by samueleresca** [comment]
> I can't add a label but this is a good first issue to implement, add a method to Column:
> 
> `public override string ToString() => (string)_jvmObject.Invoke("toString");`
> 
> and a test should do it (i'd probably include a comment to say that it doesn't return the value of the column as that is a pretty common misconception with spark)

The `Invoke` method is not even needed in this case because it would return another `JvmObjectReference` type to be  wrapped into a new `Column` instance. I think we can directly call the `_jvmObject.ToString()` since the `_jvmObject` represents the instance of the column in this case. Will do a couple of tests during the weekend.

**Comment by samueleresca** [comment]
> I can't add a label but this is a good first issue to implement, add a method to Column:
> 
> `public override string ToString() => (string)_jvmObject.Invoke("toString");`
> 
> and a test should do it (i'd probably include a comment to say that it doesn't return the value of the column as that is a pretty common misconception with spark)
 
@GoEddie can you check if the implementation I wrote, does it make sense?

**Comment by samueleresca** [comment]
Closing the issue. Related implementation in #624
