### ISSUE TITLE
[BUG]: Not able to read from a Parquet file

### ISSUE THREAD

**Issue by yashgt** [dotnet/spark#596]
Tried reading from a Parquet file generated using Python. The spark dotnet library throws an error.

```
using System;
using Microsoft.Spark.Sql;

namespace mySparkApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            // Create a Spark session
            SparkSession spark = SparkSession
                .Builder()
                .AppName("MyDotNetSpark")
                .GetOrCreate();

            // Create initial DataFrame
            DataFrame dataFrame = spark.Read().Parquet( "..\\in.parquet" );


            dataFrame.Show();
            dataFrame.Count();


            // Stop Spark session
            spark.Stop();
        }
    }
}

```
I get the error:

> [2020-07-21T07:54:26.4982330Z] [GOL014265] [Exception] [JvmBridge] JVM method execution failed: Nonstatic method parquet failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
>    at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
> Unhandled exception. System.Exception: JVM method execution failed: Nonstatic method parquet failed for class 7 when called with 1 arguments ([Index=1, Type=String[], Value=System.String[]], )
>    at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object[] args)
>    at Microsoft.Spark.Interop.Ipc.JvmBridge.CallJavaMethod(Boolean isStatic, Object classNameOrJvmObjectReference, String methodName, Object arg0)
>    at Microsoft.Spark.Interop.Ipc.JvmBridge.CallNonStaticJavaMethod(JvmObjectReference objectId, String methodName, Object arg0)
>    at Microsoft.Spark.Interop.Ipc.JvmObjectReference.Invoke(String methodName, Object arg0)
>    at Microsoft.Spark.Sql.DataFrameReader.LoadSource(String source, String[] paths)
>    at Microsoft.Spark.Sql.DataFrameReader.Parquet(String[] paths)
>    at mySparkApp.Program.Main(String[] args) in E:\Projects\expt\myplaygroundhome\mySparkApp\Program.cs:line 18

**Comment by imback82** [comment]
Can you share the full log please?

**Comment by suhsteve** [comment]
Can you also try rerunning using the full path to the parquet file ?

**Comment by yashgt** [comment]
This is the file that was generated by pyspark.
[income_non_partitioned.parquet.zip](https://github.com/dotnet/spark/files/4957773/income_non_partitioned.parquet.zip)
This file is actually a directory. However, I have also tried with a single parquet file and have seen the same issue.
[in.parquet.txt](https://github.com/dotnet/spark/files/4957784/in.parquet.txt)


This is the log file
[log.txt](https://github.com/dotnet/spark/files/4957774/log.txt)
This is the outout that I see on screen
[output.txt](https://github.com/dotnet/spark/files/4957775/output.txt)

This is the code with full path of the parquet file:
```
using System;
using Microsoft.Spark.Sql;

namespace mySparkApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            // Create a Spark session
            SparkSession spark = SparkSession
                .Builder()
                .AppName("MyDotNetSpark")
                .GetOrCreate();

            // Create initial DataFrame
            DataFrame dataFrame = spark.Read().Parquet( "E:\\Projects\\expt\\myplaygroundhome\\income_non_partitioned.parquet");


            dataFrame.Show();
            dataFrame.Count();


            // Stop Spark session
            spark.Stop();
        }
    }
}

```

**Comment by imback82** [comment]
I see the following:
```
[2020-07-22T04:04:26.9264506Z] [GOL014265] [Error] [JvmBridge] java.lang.IllegalArgumentException: Unsupported class file major version 58
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:166)
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:148)
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:136)
	at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:237)
```
This usually indicates the Java version installed is mismatching. Can you verify Java 8 is installed?

**Comment by yashgt** [comment]
E:\Projects\expt\myplaygroundhome\mySparkApp>java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by imback82** [comment]
Can you run `spark-shell` and type `spark.read.parquet("path to parquet").show`?

**Comment by imback82** [comment]
Can you also paste the output of `spark-submit --version`?

**Comment by yashgt** [comment]
E:\Projects\expt\myplaygroundhome\mySparkApp>spark-submit --version

> Welcome to
>       ____              __
>      / __/__  ___ _____/ /__
>     _\ \/ _ \/ _ `/ __/  '_/
>    /___/ .__/\_,_/_/ /_/\_\   version 2.4.1
>       /_/
> 
> Using Scala version 2.11.12, Java HotSpot(TM) 64-Bit Server VM, 14.0.1
> Branch
> Compiled by user  on 2019-03-26T22:44:44Z
> Revision
> Url
> Type --help for more information.
> 

> scala> spark.read.parquet("E:\\Projects\\expt\\myplaygroundhome\\income_non_partitioned.parquet").show
> java.lang.IllegalArgumentException: Unsupported class file major version 58
>   at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:166)
>   at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:148)
>   at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:136)
>   at org.apache.xbean.asm6.ClassReader.<init>(ClassReader.java:237)
>   at org.apache.spark.util.ClosureCleaner$.getClassReader(ClosureCleaner.scala:49)
>   at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:517)
>   at org.apache.spark.util.FieldAccessFinder$$anon$3$$anonfun$visitMethodInsn$2.apply(ClosureCleaner.scala:500)
>   at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
>   at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
>   at scala.collection.mutable.HashMap$$anon$1$$anonfun$foreach$2.apply(HashMap.scala:134)
>   at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
>   at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
>   at scala.collection.mutable.HashMap$$anon$1.foreach(HashMap.scala:134)
>   at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
>   at org.apache.spark.util.FieldAccessFinder$$anon$3.visitMethodInsn(ClosureCleaner.scala:500)
>   at org.apache.xbean.asm6.ClassReader.readCode(ClassReader.java:2175)
>   at org.apache.xbean.asm6.ClassReader.readMethod(ClassReader.java:1238)
>   at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:631)
>   at org.apache.xbean.asm6.ClassReader.accept(ClassReader.java:355)
>   at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:307)
>   at org.apache.spark.util.ClosureCleaner$$anonfun$org$apache$spark$util$ClosureCleaner$$clean$14.apply(ClosureCleaner.scala:306)
>   at scala.collection.immutable.List.foreach(List.scala:392)
>   at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:306)
>   at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:162)
>   at org.apache.spark.SparkContext.clean(SparkContext.scala:2326)
>   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2100)
>   at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
>   at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
>   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
>   at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
>   at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
>   at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
>   at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat$.mergeSchemasInParallel(ParquetFileFormat.scala:633)
>   at org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat.inferSchema(ParquetFileFormat.scala:241)
>   at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
>   at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$6.apply(DataSource.scala:180)
>   at scala.Option.orElse(Option.scala:289)
>   at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:179)
>   at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:373)
>   at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
>   at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
>   at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:641)
>   at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:625)
>   ... 49 elided

**Comment by imback82** [comment]
> Using Scala version 2.11.12, Java HotSpot(TM) 64-Bit Server VM, 14.0.1

Spark is invoked with Java 14. You should see something like the following:

```
Using Scala version 2.11.12, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_211
```

Please fix your environement.

**Comment by yashgt** [comment]
I was following instructions from https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Now Upgraded to spark 3.0.0.

spark-shell 
spark.read.parquet("path to parquet").show

This works now.

But
E:\Projects\expt\myplaygroundhome\mySparkApp>spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll

> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/D:/downloads/dvd/spark-3.0.0-bin-hadoop2.7/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
> WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> 20/07/22 12:12:47 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
>         at org.apache.spark.deploy.dotnet.DotnetRunner$.<init>(DotnetRunner.scala:35)
>         at org.apache.spark.deploy.dotnet.DotnetRunner$.<clinit>(DotnetRunner.scala)
>         at org.apache.spark.deploy.dotnet.DotnetRunner.main(DotnetRunner.scala)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
>         at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
>         at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
>         at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
>         at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
>         at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
>         at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
>         at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
>         at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
> Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
>         at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
>         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>         ... 15 more
> log4j:WARN No appenders could be found for logger (org.apache.spark.util.ShutdownHookManager).
> log4j:WARN Please initialize the log4j system properly.
> log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by imback82** [comment]
Spark 3.0 is not yet supported in .NET for Apache Spark. Spark 3.0 supports later version of Java and that's why it's working in Scala.

**Comment by yashgt** [comment]
Reverted to Spark 2.4.1 and pointed JAVA_HOME to JDK1.8. It works now. Thanks.
