### ISSUE TITLE
[BUG]: assembly.zip files not supported as argument, as it conflicts with the need for "dotnet" as the first arg

### ISSUE THREAD

**Issue by zzhu-bh** [dotnet/spark#613]
**Describe the bug**
Using zip'd assembly containing Spark.worker dll's doesn't work with DotnetRunner.
This happens on both Windows and Linux, with .NET Core 3.1 installed.
I'm using Spark 2.4.6, but happens with other variants of spark 2.4 as well.

**To Reproduce**

1. Zip up your assembly along with Microsoft.Spark.Worker files
2. try to run it using spark submit on the cmdline, with args: 
spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local  assembly.zip dotnet assembly.dll

**Expected behavior**
Runs the same as if you just specified assembly.dll in the current directory

**Additional context**
I dug a little deeper into this issue, and fortunately I’m pretty confident this is going to be resolvable, albeit the root cause is disturbing.

I looked at the dotnet runner scala code that is the main driver for the .NET app.  It’s actually quite simple.   However, there’s a couple of bugs with it.
https://github.com/dotnet/spark/blob/master/src/scala/microsoft-spark-2.4.x/src/main/scala/org/apache/spark/deploy/dotnet/DotnetRunner.scala

From reading the code, looks like the anatomy of the DotNetRunner args is as follows:
Driver_jar_name  [dotnet] assembly_name.dll
Or
Driver_jar_name  assembly.zip [dotnet] assembly_name.dll

1)	It tries to support auto unzip by introducing the zip file, it’s a key feature because we need to bundle ms.spark.worker along with our assembly. However, if the zip file arg is introduced, they shift / splice args incorrectly in the driver, so the wrong args get passed.
2)	It needs to run within the current directory of the assembly (.net core quirk?), and not setting that would be problematic.  So need to do an explicit chdir to the location of the unzip'd binaries.  (not sure if this is a runner bug or fundamental issue with Spark.NET + .NET core?)

The ability to use zip'd assemblies is important for something like Azure Data Factory, where we can't rig / unzip the assemblies ahead of time.  However, we can provide absolute paths to /dbfs/ mounts containing the bootstrap jars and the assembly.zip

Happy to provide more details/context if needed.  Thank you, and keep up the great work on this project!
(Very much looking forward to Spark 3.x support)

**Comment by imback82** [comment]
Thanks @zzhu-bh for your encouraging comment!

If you are using a zip file, the following argument (after the zip file) should be an "executable" that's inside the zip file.

So you can `dotnet publish` your app and use  `assembly.zip assembly.exe` (or `assembly` on *nix).

**Comment by zzhu-bh** [comment]
Thanks for the quick response @imback82 !  Okay, that actually makes sense, so basically.  Now I'm still running into the issue of #2.  This is especially the case if my Spark job uses UDF's defined on the C# side.   If I don't run the spark-submit in the exact directory containing the Microsoft.Spark.Worker binaries, I run into what looks like .NET serialization errors.  This is true on both Windows or Linux, and both have .NET core SDK 3.1 installed.  e.g. export DOTNET_WORKER_DIR=/home/zzhu/Microsoft.Spark/ or SET DOTNET_WORKER_DIR=c:/sparkworker  seems to have no effect for me.   What our team ends up having to do is to basically copy the application specific compiled assemblies for the Spark .NET project from the bin/ folder into a temp folder where we have also copied the complete Microsoft.Spark.Worker binaries for that platform.   Maybe I should open a separate issue for that?

**Comment by imback82** [comment]
Yea, could you open a new issue with a repro step? Thanks!
