### ISSUE TITLE
[FEATURE REQUEST]: support for AwaitAnyTermination for Structured streaming queries

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#614]
**Is your feature request related to a problem? Please describe.**
I have multiple streaming queries running in my Job and i want to terminate my job in case any of the query fail. Presently i am using awaitTermination on the last query in my code. so if any other query fails, it doesn't terminate my job.

**Describe the solution you'd like**
is there a way to use spark api park.streams.awaitAnyTermination(), so that if any of the query fail, it will terminate job

**Describe alternatives you

**Comment by imback82** [comment]
Thanks @guruvonline. Yes, I think we should expose `StreamingQueryManager` in C#. Are you interested in contributing?

**Comment by imback82** [comment]
We can expose the following APIs from `StreamingQueryManager`:
`active`, `get`, `awaitAnyTermination`, and `resetTerminated`

**Comment by suhsteve** [comment]
Relevant PR #690 merged.
