### ISSUE TITLE
Expose DataFrame.Persist() with StorageLevel

### ISSUE THREAD

**Issue by rrekapalli** [dotnet/spark#617]
How to set storage level for DataFrame.Cache()/DataFrame.Persist() methods?

**Comment by imback82** [comment]
It's currently missing the API:

https://github.com/dotnet/spark/blob/5c5c249f6cd2957fd0ea5799c7bc6c7f6d38d662/src/csharp/Microsoft.Spark/Sql/DataFrame.cs#L17-L20

We can use this issue to track it. Let me change the issue title accordingly.

**Comment by rrekapalli** [comment]
Sure.  Thank you!

**Comment by Niharikadutta** [comment]
Has been resolved with #623. Closing the issue.
