### ISSUE TITLE
Could not use the monotonically_increasing_id to add row id into spark dataframe 

### ISSUE THREAD

**Issue by zwhrenxiaoxue** [dotnet/spark#625]
How Can I use the function monotonically_increasing_id() to add row index for the spark dataframe.
Code: DataFrame df_SrcFile2 = df_SrcFile1.WithColumn("index", monotonically_increasing_id());
Error:
Microsoft (R) Build Engine version 16.7.0-preview-20360-03+188921e2f for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
Program.cs(31,69): error CS0103: The name 'monotonically_increasing_id' does not exist in the current context 

Build FAILED.

Program.cs(31,69): error CS0103: The name 'monotonically_increasing_id' does not exist in the current context

**Comment by imback82** [comment]
It should be:
https://github.com/dotnet/spark/blob/9275678a6e46e06a266e5516b3fea50896ede761/src/csharp/Microsoft.Spark/Sql/Functions.cs#L1020

**Comment by zwhrenxiaoxue** [comment]
> It should be:
> https://github.com/dotnet/spark/blob/9275678a6e46e06a266e5516b3fea50896ede761/src/csharp/Microsoft.Spark/Sql/Functions.cs#L1020

it works fine. Thank you very much.
