### ISSUE TITLE
'spark-submit' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nhatpham170** [dotnet/spark#628]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Niharikadutta** [comment]
Could you paste the exact error message, and details like your spark-submit command, SPARK_HOME etc?

**Comment by suhsteve** [comment]
Please follow the suggested steps in #557 and #304 .
