### ISSUE TITLE
[QUESTION]: Multiple Spark Sessions in One Application

### ISSUE THREAD

**Issue by rrekapalli** [dotnet/spark#629]
A quick questions - Can we dynamically create multiple spark sessions in one application? Does .NET for Spark support such a use case?

Thanks.

**Comment by Niharikadutta** [comment]
Yes, this is supported by the [`SparkSession.NewSession()`](https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark/Sql/SparkSession.cs#L142) function. However, it should be noted as mentioned in the summary that the new SparkSession(s) would share the underlying SparkContext between them,

**Comment by rrekapalli** [comment]
Great.  Thank you!
