### ISSUE TITLE
[Feature Request]: Move extensions in Microsoft.Spark.Experimental to Microsoft.Spark in 1.0

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#639]
There are few extensions defined in `Microsoft.Spark.Experimental` for registering Vector UDFs and group UDFs (with both Arrow and .NET DataFrame support). I think this can live inside Microsoft.Spark when we move to 1.0.

Any thoughts?

**Comment by suhsteve** [comment]
I agree, I think we should.
