### ISSUE TITLE
show .net SPARK aggregate data frame in console 

### ISSUE THREAD

**Issue by m-evazzadeh** [dotnet/spark#640]
Hi
I'm using Spark and KAFKA together and I get message from KAFKA successfully.
How do show aggregate data frame in console 
```
var dfProceess = dfWindowTumbling
                .GroupBy(Col("WindowFrame"))
                .Agg(Sum("Price").Alias("sp"))
                .Select(Col("sp"));

StreamingQuery query = dfWindowTumbling
                            .WriteStream()
                            .OutputMode(OutputMode.Complete)
                            .Format("console")
                            .Option("truncate", false)
                            .Start();
            query.AwaitTermination();
```

**Comment by suhsteve** [comment]
have you tried changing
```csharp
StreamingQuery query = dfWindowTumbling
...
```
to
```csharp
StreamingQuery query = dfProceess
...
```

**Comment by m-evazzadeh** [comment]
Oh, sorry. I wrote it wrong 
But when I correction code to 
StreamingQuery query = dfProceess...
Again, don't show anything in console !

**Comment by m-evazzadeh** [comment]
> have you tried changing
> 
> ```cs
> StreamingQuery query = dfWindowTumbling
> ...
> ```
> 
> to
> 
> ```cs
> StreamingQuery query = dfProceess
> ...
> ```
Oh, sorry. I wrote it wrong
But when I correction code to
StreamingQuery query = dfProceess...
Again, don't show anything in console !

**Comment by suhsteve** [comment]
Can you give attach your driver logs so we can verify if it's not showing up ?

**Comment by m-evazzadeh** [comment]
tanks @suhsteve  for following up

my User-Defined Functions was wrong. 
solved this issue
