### ISSUE TITLE
How to pass StructType between .NET & JVM?

### ISSUE THREAD

**Issue by GoEddie** [dotnet/spark#651]
For FeatureHasher I need to take a StructType and pass it over to the JVM as a parameter (https://spark.apache.org/docs/2.4.0/api/java/org/apache/spark/ml/feature/FeatureHasher.html#transformSchema-org.apache.spark.sql.types.StructType-). 

At the moment I get "System.NotSupportedException : Type Microsoft.Spark.Sql.Types.StructType not supported yet".

Is the way to implement it to serialise/deserialise as json across the wire or is there a better way? StructType already has a constructor from json and a json value to get the json from it on the .NET side.

I'm not sure if I am missing something because shouldn't it just be treated like any other jvm object reference?

**Comment by Niharikadutta** [comment]
I am working on adding support to pass `StructType` between .NET and JVM as a part of #649 . You should be able to just use it once that is in. Thanks!

**Comment by GoEddie** [comment]
Great, i'll leave that method off until 649 is ready.

**Comment by suhsteve** [comment]
I'm pretty sure we solved this already.  You should use https://github.com/dotnet/spark/blob/9239e726cd745c42d32358de1267eeff02019f95/src/csharp/Microsoft.Spark/Sql/Types/DataType.cs#L89-L95


Please see this example
https://github.com/dotnet/spark/blob/9239e726cd745c42d32358de1267eeff02019f95/src/csharp/Microsoft.Spark/Sql/DataFrameReader.cs#L49-L53

**Comment by GoEddie** [comment]
got it, thanks
