### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by timing418** [dotnet/spark#659]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Niharikadutta** [comment]
Can you please refer to #557 and #304, which address this issue. Please let us know if that does not resolve this error, thanks.
