### ISSUE TITLE
.net Spark submit your application to run on Apache Spark

### ISSUE THREAD

**Issue by MichaelRodrigueess0s1** [dotnet/spark#662]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

When i'm try run the following command i'm receive following message:

Command:
%SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll

Response message
$ %SPARK_HOME%\bin\spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2.4.x-0.10.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll
bash: fg: %SPARK_HOME%binspark-submit: no such job

**Comment by Niharikadutta** [comment]
Are you able to run `spark-shell` from the path `%SPARK_HOME%\bin`?
