### ISSUE TITLE
[FEATURE REQUEST]: Develop in Python with ability to use C# in UDF

### ISSUE THREAD

**Issue by olehb007** [dotnet/spark#664]
In our company the primary language is C# and we already have many UDF's written in it. The same time I noticed for a rapid development and prototyping Python is suited better. I believe it will be very useful to be able to develop in Python and to use C# in UDF simultaneously.

**Comment by imback82** [comment]
It is possible, but quite convoluted: https://github.com/imback82/sparkdotnetudf#invoke-c-udf-from-python
