### ISSUE TITLE
[BUG]: Hyperspace import com.microsoft.hyperspace.index.IndexConfig failed

### ISSUE THREAD

**Issue by cpatte7372** [dotnet/spark#668]
I'm in the middle of testing Microsofts Hyperscale.

I'm getting the following error when I try to run the following

`import com.microsoft.hyperspace.index.IndexConfig`

command-915315058669819:1: error: object IndexConfig is not a member of package com.microsoft.hyperspace.index
import com.microsoft.hyperspace.index.IndexConfig

I'm also getting an error when I try to run the following:

`val hyperspace: Hyperspace = Hyperspace()`

 error: not found: type Hyperspace
val hyperspace: Hyperspace = Hyperspace()

I'm running Apache Spark 2.4.5, python scala 2.11

Spark 2.4

Any thoughts?

**Comment by cpatte7372** [comment]
This was resolved by installing com.microsoft.hyperspace:hyperspace-core_2.11:
0.2.0

However, when I run the following line of code `hyperspace.createIndex(emp_DF, emp_IndexConfig)` I get the error:

`java.lang.ClassCastException: org.apache.spark.sql.execution.datasources.SerializableFileStatus cannot be cast to org.apache.hadoop.fs.FileStatus`

Any thoughts?

**Comment by cpatte7372** [comment]
Can somene let me know if Hyperspace is supported on Databricks DBFS?

**Comment by rapoth** [comment]
@cpatte7372 Looks like you are testing the scala version of Hyperspace. Could you post your question(s) on the Hyperspace [issues](https://github.com/microsoft/hyperspace/issues) page instead?

I will be closing this issue but please feel free to re-open it if you are facing any issues using Hyperspace in .NET.
