### ISSUE TITLE
Spark Installation Issue

### ISSUE THREAD

**Issue by rangakrishna** [dotnet/spark#669]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

I am facing the below error message when I issue enter the below in my command prompt

%SPARK_HOME%\bin\spark-submit --version

**The system cannot find the path specified.
Failed to find Spark jars directory.
You need to build Spark before running this program.**

**Comment by Niharikadutta** [comment]
Can you please refer to #557 and #304, which address this issue. Please make sure all the required environment variables are set up correctly.

**Comment by Niharikadutta** [comment]
Hi, we are closing this issue as it has been addressed multiple times and has steps to follow as mentioned in the linked issues. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
