### ISSUE TITLE
[BUG]: The worker binary for macOS has incorrect file names

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#672]
**Describe the bug**
When I unzip the worker bianry for macOS, I see the following where each file name is prepended with `Microsoft.Spark.Worker-0.12.1\`:
```
~/D/Microsoft.Spark.Worker.netcoreapp3.1.osx-x64-0.12.1 > ls -l                                                              
total 157200
-rw-rw-r--@ 1 terryk  staff   151552 Jun 27 19:38 Microsoft.Spark.Worker-0.12.1\Apache.Arrow.dll
-rw-rw-r--@ 1 terryk  staff  3018616 Jun 27 19:39 Microsoft.Spark.Worker-0.12.1\FSharp.Core.dll
-rw-rw-r--@ 1 terryk  staff   810360 Jun 27 19:39 Microsoft.Spark.Worker-0.12.1\Microsoft.CSharp.dll
-rw-rw-r--@ 1 terryk  staff   529784 Jun 27 19:39 Microsoft.Spark.Worker-0.12.1\Microsoft.Data.Analysis.dll
-rw-rw-r--@ 1 terryk  staff    88968 Jun 27 19:39 Microsoft.Spark.Worker-0.12.1\Microsoft.DotNet.DependencyManager.dll
-rw-rw-r--@ 1 terryk  staff    52992 Jun 27 19:39 Microsoft.Spark.Worker-0.12.1\Microsoft.ML.DataView.dll
-rw-rw-r--@ 1 terryk  staff    85116 Jun 27 19:39 Microsoft.Spark.Worker-0.12.1\Microsoft.Spark.Worker
-rw-rw-r--@ 1 terryk  staff   109420 Jun 27 19:39 Microsoft.Spark.Worker-0.12.1\Microsoft.Spark.Worker.deps.json
```

**To Reproduce**
Download the latest worker binary for macOS from [here](https://github.com/dotnet/spark/releases/tag/v0.12.1) and unzip it.

**Expected behavior**
The file name shouldn't be prepended with `Microsoft.Spark.Worker-0.12.1\`.

**Comment by suhsteve** [comment]
I thought we fixed issues like this from happening by ensuring we had an up to date Microsoft.PowerShell.Archive module ?  #209

**Comment by imback82** [comment]
Not sure what happened. I will take a look.

**Comment by imback82** [comment]
Hi @safern,

We need to install `Microsoft.PowerShell.Archive` >= `1.2.3` so that we get the correct ZIP file for macOS.

However, when I run the following powershell script in the `NetCoreInternal-Pool` (`buildpool.windows.10.amd64.vs2017`):
```
- powershell: Install-Module -Name Microsoft.PowerShell.Archive -Scope CurrentUser -Force -AllowClobber -Verbose -MinimumVersion 1.2.5
```
, it fails to install it: https://dev.azure.com/dnceng/internal/_build/results?buildId=843680&view=logs&j=eeb239ec-1515-5eff-2217-95cf642eebee&t=b512a77b-ce36-5502-3b1b-dd336a82f0d8 

The same script works fine in other pool (e.g., `Hosted VS2017`), but we need to install it in `NetCoreInternal-Pool` for signing. Do you know any workaround (e.g., internal feed for the download)?

(In the worst case, I guess we can have the signing job to publish after signing and another pool does the zipping.)

Thanks in advance!
