### ISSUE TITLE
[BUG]: Failed to execute 'load' on 'org.apache.spark.sql.streaming.DataStreamReader' with args=()

### ISSUE THREAD

**Issue by hihihihiwsf** [dotnet/spark#674]
**Describe the bug**
I tried to run a job pursuing kafka streaming and I always failed on the mode yarn, while I can run it successfully local.

The error log is：
20/09/16 00:16:44 INFO [dispatcher-event-loop-0] cluster.YarnSchedulerBackend$YarnSchedulerEndpoint: ApplicationMaster registered as NettyRpcEndpointRef(spark://YarnAM@BN2AAPB241924DF:23294)
20/09/16 00:16:44 INFO [main] yarn.YarnAllocator: For the total 2 with 0 running and 0 pending executors, request 2 executor container(s), each with 1 core(s) (including 0 overhead) and 1408 MB memory (including 384 MB of overhead)
20/09/16 00:16:44 INFO [main] yarn.YarnAllocator: Submitted 2 unlocalized container requests.
20/09/16 00:16:44 INFO [main] yarn.ApplicationMaster: Started progress reporter thread with (heartbeat : 3000, initial allocation : 200) intervals
20/09/16 00:16:44 INFO [spark-rack-resolver] autopilot.AutopilotTopologyMapping: Waiting 500 ms for the physical machine mapping to load for the first 
20/09/16 00:16:45 INFO [spark-rack-resolver] autopilot.AutopilotTopologyMapping: Waiting 500 ms for the physical machine mapping to load for the first 
20/09/16 00:16:45 INFO [Thread-42] autopilot.AutopilotTopologyMapping: Read 0 physical mappings (removed 0) in 719 ms
20/09/16 00:16:45 INFO [Reporter] yarn.YarnAllocator: Asked to launch  2 containers: Drop 0 and launching  2  to reach 0 running containers
20/09/16 00:16:45 INFO [Reporter] yarn.YarnAllocator: Launching container container_e318_1600148666568_0743_01_000004 on host BN2AAP08312042D for executor with ID 1
20/09/16 00:16:45 INFO [Reporter] yarn.YarnAllocator: Launching container container_e318_1600148666568_0743_01_000005 on host BN2AAP8BD80028B for executor with ID 2
20/09/16 00:17:08 INFO [dispatcher-event-loop-3] cluster.YarnSchedulerBackend$YarnDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (100.99.109.8:46900) with ID 1
20/09/16 00:17:08 INFO [dispatcher-event-loop-1] storage.BlockManagerMasterEndpoint: Registering block manager BN2AAP08312042D:46925 with 366.3 MB RAM, BlockManagerId(1, BN2AAP08312042D, 46925, None)
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] cluster.YarnClusterSchedulerBackend: SchedulerBackend is ready for scheduling beginning after waiting maxRegisteredResourcesWaitingTime: 30000(ms)
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] cluster.YarnClusterScheduler: YarnClusterScheduler.postStartHook done
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] internal.SharedState: loading hive config file: file:/D:/data/hadoop.config/Yarn_NodeManager.mtp_20200914_77cb0308_rollout/hive-site.xml
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] internal.SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/D:/data/yarnnm/local/usercache/t-sifwu/appcache/application_1600148666568_0743/container_e318_1600148666568_0743_01_000002/spark-warehouse').
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] internal.SharedState: Warehouse path is 'file:/D:/data/yarnnm/local/usercache/t-sifwu/appcache/application_1600148666568_0743/container_e318_1600148666568_0743_01_000002/spark-warehouse'.
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /SQL.
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] handler.ContextHandler: Started o.s.j.s.ServletContextHandler@46fcf9de{/SQL,null,AVAILABLE,@Spark}
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /SQL/json.
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] handler.ContextHandler: Started o.s.j.s.ServletContextHandler@456b20fd{/SQL/json,null,AVAILABLE,@Spark}
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /SQL/execution.
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] handler.ContextHandler: Started o.s.j.s.ServletContextHandler@6660e445{/SQL/execution,null,AVAILABLE,@Spark}
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /SQL/execution/json.
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] handler.ContextHandler: Started o.s.j.s.ServletContextHandler@7760b40b{/SQL/execution/json,null,AVAILABLE,@Spark}
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] ui.JettyUtils: Adding filter org.apache.hadoop.yarn.server.webproxy.amfilter.AmIpFilter to /static/sql.
20/09/16 00:17:13 INFO [nioEventLoopGroup-2-2] handler.ContextHandler: Started o.s.j.s.ServletContextHandler@584c9680{/static/sql,null,AVAILABLE,@Spark}
20/09/16 00:17:14 INFO [nioEventLoopGroup-2-2] state.StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
20/09/16 00:17:14 ERROR [nioEventLoopGroup-2-2] dotnet.DotnetBackendHandler: Failed to execute 'load' on 'org.apache.spark.sql.streaming.DataStreamReader' with args=()
20/09/16 00:17:15 INFO [dispatcher-event-loop-2] cluster.YarnSchedulerBackend$YarnDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (100.99.100.49:36946) with ID 2
20/09/16 00:17:16 INFO [dispatcher-event-loop-3] storage.BlockManagerMasterEndpoint: Registering block manager BN2AAP8BD80028B:36967 with 366.3 MB RAM, BlockManagerId(2, BN2AAP8BD80028B, 36967, None)
20/09/16 00:17:22 INFO [Driver] dotnet.DotnetRunner: Closing DotnetBackend
20/09/16 00:17:22 ERROR [Driver] yarn.ApplicationMaster: User application exited with status 57005
20/09/16 00:17:22 INFO [Driver] yarn.ApplicationMaster: Final app status: FAILED, exitCode: 57005, (reason: User application exited with status 57005)
20/09/16 00:17:22 INFO [shutdown-hook-0] spark.SparkContext: Invoking stop() from shutdown hook
20/09/16 00:17:22 INFO [spark-listener-group-eventLog] scheduler.EventLoggingListener: set xattr for app end
20/09/16 00:17:22 INFO [shutdown-hook-0] server.AbstractConnector: Stopped Spark@6949fccf{HTTP/1.1,[http/1.1]}{0.0.0.0:0}
20/09/16 00:17:22 INFO [shutdown-hook-0] ui.SparkUI: Stopped Spark web UI at http://BN2AAPB241924DF:23295
20/09/16 00:17:22 INFO [dispatcher-event-loop-3] yarn.YarnAllocator: Driver requested a total number of 0 executor(s).
20/09/16 00:17:22 INFO [shutdown-hook-0] cluster.YarnClusterSchedulerBackend: Shutting down all executors
20/09/16 00:17:22 INFO [dispatcher-event-loop-4] cluster.YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
20/09/16 00:17:22 INFO [shutdown-hook-0] cluster.SchedulerExtensionServices: Stopping SchedulerExtensionServices
(serviceOption=None,
 services=List(),
 started=false)
20/09/16 00:17:22 INFO [dispatcher-event-loop-0] spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
20/09/16 00:17:22 INFO [shutdown-hook-0] memory.MemoryStore: MemoryStore cleared
20/09/16 00:17:22 INFO [shutdown-hook-0] storage.BlockManager: BlockManager stopped
20/09/16 00:17:22 INFO [shutdown-hook-0] storage.BlockManagerMaster: BlockManagerMaster stopped
20/09/16 00:17:22 INFO [dispatcher-event-loop-3] scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
20/09/16 00:17:22 INFO [shutdown-hook-0] spark.SparkContext: Successfully stopped SparkContext
20/09/16 00:17:22 INFO [shutdown-hook-0] yarn.YarnRMClient: sparkMaxAttempts=3(capped by yarn.resourcemanager.am.max-attempts=3);  sparkMaxAttemptsOverride=0(capped by yarn.resourcemanager.am.max-all-attempts=100)
20/09/16 00:17:22 INFO [shutdown-hook-0] util.ShutdownHookManager: Shutdown hook called
20/09/16 00:17:22 INFO [shutdown-hook-0] util.ShutdownHookManager: Deleting directory D:\data\yarnnm\local\usercache\t-sifwu\appcache\application_1600148666568_0743\spark-d577bb37-6dc8-4de5-9f4c-d254b03f5853
Picked up JAVA_TOOL_OPTIONS: -Dhadoop.root.logger.level=INFO -Dhadoop.root.logger.dest=console -Djava.security.krb5.conf=D:\data\java.latest\krb5.conf

 Could anyone kindly help me with this problem? I have been stuck for several days.

**Comment by suhsteve** [comment]
What spark-submit command are you using when you run it locally vs yarn ?

**Comment by hihihihiwsf** [comment]
> What spark-submit command are you using when you run it locally vs yarn ?

The command I submitted is : 
`spark-submit.cmd  --master yarn --deploy-mode cluster --jars hdfs://BN2-1/user/t-sifwu/kafkaspark_test/spark-sql-kafka-0-10_2.11-2.4.1.jar,hdfs://BN2-1/user/t-sifwu/kafkaspark_test/structuredstreamforspark_2.11-2.3.0-1.1.7.jar --conf spark.yarn.appMasterEnv.DOTNET_WORKER_DIR=.\worker\Microsoft.Spark.Worker-0.12.1 --conf spark.yarn.appMasterEnv.DOTNET_ASSEMBLY_SEARCH_PATHS=.\udfs  --archives hdfs://BN2-1/user/t-sifwu/kafkaspark_test/Microsoft.Spark.Worker.net461.win-x64-0.12.1.zip#worker,hdfs://BN2-1/user/t-sifwu/kafkaspark_test/Debug.zip#udfs --class org.apache.spark.deploy.dotnet.DotnetRunner hdfs://BN2-1/user/t-sifwu/kafkaspark_test/microsoft-spark-2.4.x-0.12.1.jar hdfs://BN2-1/user/t-sifwu/kafkaspark_test/Debug.zip  kafka_test.exe`

**Comment by Niharikadutta** [comment]
Can you add the `spark.driver.extraClassPath` and `spark.executor.extraClassPath` configs to the spark-submit command and point them to the additional jars you are passing through the `--jars` config?

**Comment by hihihihiwsf** [comment]
> Can you add the `spark.driver.extraClassPath` and `spark.executor.extraClassPath` configs to the spark-submit command and point them to the additional jars you are passing through the `--jars` config?

What is  the `spark.driver.extraClassPath` and `spark.executor.extraClassPath` ? Is that a jar package in my zipped Debug.zip？

**Comment by Niharikadutta** [comment]
No, these are Spark configs fed through `spark-submit` using the `--conf` parameter. Please check the [official documentation](https://spark.apache.org/docs/2.4.0/configuration.html#runtime-environment) and [this example](https://stackoverflow.com/questions/37132559/add-jars-to-a-spark-job-spark-submit) to understand how to use it.

**Comment by hihihihiwsf** [comment]
> No, these are Spark configs fed through `spark-submit` using the `--conf` parameter. Please check the [official documentation](https://spark.apache.org/docs/2.4.0/configuration.html#runtime-environment) and [this example](https://stackoverflow.com/questions/37132559/add-jars-to-a-spark-job-spark-submit) to understand how to use it.

Hi, I think this problem is caused by a simple UDF function, can this configs help that?

**Comment by Niharikadutta** [comment]
Can you also provide your `Debug.zip` file with the dlls? Since you mentioned it is working locally, I suspect it might be failing through Yarn because the jars you are providing are not being loaded by Spark (as mentioned in [this example's answer](https://stackoverflow.com/questions/37132559/add-jars-to-a-spark-job-spark-submit) adding jars through `--jars` config does not add the JAR files to your driver/executor classpath, this needs to be done explicitly, and this is how Spark knows where to look for jars that needed to be loaded in driver or executor).

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
