### ISSUE TITLE
Azure Databricks environment throwing AmbiguousMatchException for invoking UDF

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#675]
HI,
My streaming query using a UDF is throwing "System.Reflection.AmbiguousMatchException: Ambiguous match found." attached is detailed exception. 

I am using 0.10.0 version and Databricks    6.4 runtime (spark 2.4.5 and scala 2.11)

This is an existing UDF(no signature change) code which takes json string and return json string, and used to work earlier. Now i have modified internal implementation of UDF to return extra attributes in JSON. From StackTrace it doesn't look like it has reached my new code and somewhere failing to call UDF itself.
Any suggestion on what could be the reason of this exception.

[Error.txt](https://github.com/dotnet/spark/files/5235253/Error.txt)

Thanks

**Comment by rapoth** [comment]
@guruvonline Were you always on this Databricks 6.4 runtime and the code stopped working OR is this a new runtime that you are trying?

**Comment by guruvonline** [comment]
same environment was working earlier, I updated my code by modifying internal implementation of UDF and facing this issue. from stack trace looks like it's not even reaching my new code changes, so confused.

 i will try to run locally and see if i can add any additional details.

**Comment by rapoth** [comment]
Got it, thanks! If the same environment was working earlier, could you please open a support ticket with Databricks? It is likely that they have changed their runtime to break something here. If you can get them to give us a repro here on the Github repo, we would be happy to help address it.

**Comment by suhsteve** [comment]
If you modified your UDF, you may need to deploy and overwrite your udf containing assembly.

**Comment by guruvonline** [comment]
failure was due to 2 overloaded UDF functions(one function was taking string parameter; other was taking object parameter) even though when invoked UDF from Dataframe i used string signature. 
looks like spark.net works by UDF method name and not parameters. Not sure if this is something that can be handled by spark.net.
Thanks for all suggestions.
