### ISSUE TITLE
[Question]Can the API ToLocalIterator() be used in Streaming Spark?

### ISSUE THREAD

**Issue by hihihihiwsf** [dotnet/spark#679]
I'd like to process the data read from kafka, however I can't process it directly. Can the ToLocalIterator() function be used in this process?

**Comment by imback82** [comment]
Do you have a sample code you can share so I can understand the requirement a little better?

If brining in the data to driver to process is OK in your scenario, `ToLocalIterator` or `Collect` should be fine (but not recommended).

**Comment by Niharikadutta** [comment]
Hi, we are going to close this issue as it has been inactive for a while. Please feel free to re-open it if the issue persists and/or there are any new updates. Thank you!
