### ISSUE TITLE
[BUG]: TestsDaemonWorkerTaskRunners and TestCallbackServer tests flaky

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#685]
**Microsoft.Spark.E2ETest.UdfTests.DaemonWorkerTests.TestsDaemonWorkerTaskRunners** and **Microsoft.Spark.UnitTest.CallbackTests.TestCallbackServer** rely on spinning up threads and ensuring that the current number of tasks match the expected amount.  Sometimes this is not the case and the fails.

**Comment by imback82** [comment]
@suhsteve Are you looking into this issue?

**Comment by suhsteve** [comment]
@imback82 no I'm not.
