### ISSUE TITLE
[FEATURE REQUEST]: Update Microsoft.Spark.Extensions.DotNet.Interactive to support latest dotnet-interactive

### ISSUE THREAD

**Issue by suhsteve** [dotnet/spark#686]
dotnet interactive has changed the [kernel extension interface](https://github.com/dotnet/interactive/blob/main/src/Microsoft.DotNet.Interactive/IKernelExtension.cs).  Update the extension accordingly.

**Comment by rrekapalli** [comment]
Hi Steve, 

Can we embed .Net Interactive in a web application that can use .Net for Spark?  In the sense, can we create .Net interactive notebooks in ASP.Net from end application with this feature?

Thanks,
Raja
