### ISSUE TITLE
[FEATURE REQUEST]: Dataframe.toJSON()

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#695]
**Is your feature request related to a problem? Please describe.**
I want to have in-memory representation of dataframe as JSON string. this string, i have to use in some other part of my code,  so i can't save the dataframe as json file

**Describe the solution you'd like**
how to access spark api dataframe.toJSON()

**Describe alternatives you've considered**
i don't want to write custom UDF for this

**Comment by imback82** [comment]
Thanks @guruvonline. Yes we can expose this in the next release.

@Niharikadutta can you expose this API? Also, can you make sure if there are any missing APIs compared to `dataframe.py`? Thanks!

**Comment by suhsteve** [comment]
It's listed in https://github.com/dotnet/spark/issues/621 .  We can un-~~strikethrough~~ if we want to support.

**Comment by Niharikadutta** [comment]
Yes I will expose this

**Comment by Niharikadutta** [comment]
@imback82 @suhsteve I have exposed this API in #698 and verified there are no missing APIs as compared to `dataframe.py`
