### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by orestis-ms** [dotnet/spark#72]
In Windows 10, we have created a netcoreapp2.1 project in VS2019 for the sample HelloSpark, building for x64 architecture. We use the binaries for the netcoreapp2.1 Microsoft.Spark.Worker, and we try to run on a v.2.4.1 Spark local instance with 64-Bit OpenJDK and 64-bit Python3.5.2 (Anaconda).

We get the following error:
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. An attempt was made to load a program with an incorrect format. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by suhsteve** [comment]
Can you also provide the spark-submit command you used ?

**Comment by orestis-ms** [comment]
spark-submit --class org.apache.spark.deploy.DotnetRunner --master local microsoft-spark-2.4.x-0.1.0.jar HelloSpark.dll

I also had to manually copy the Microsoft.Spark.Worker DLLs to the same directory. Otherwise, it would fail to find them:
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by rapoth** [comment]
Can you please try the following command?

spark-submit `
     --class org.apache.spark.deploy.DotnetRunner `
     --master local `
     microsoft-spark-2.4.x-<version>.jar `
     <full-path-to-dotnet.exe> .\HelloSpark.dll

There was a bug in our documentation that suggested using a DLL instead of specifying the path to dotnet.exe.

**Comment by suhsteve** [comment]
Regarding the issue with manually copying the Microsoft.Spark.Worker dlls to the same directory.   Was the environment variable DotnetWorkerPath set before running the submit command?


**IMPORTANT** Create a [new environment variable](https://www.java.com/en/download/help/path.xml) `DotnetWorkerPath` and set it to the directory where you downloaded and extracted the Microsoft.Spark.Worker (e.g., `c:\bin\Microsoft.Spark.Worker`).

**Comment by imback82** [comment]
@orestis-ms Please reopen the issue if you still encounter the same issue.
