### ISSUE TITLE
[FEATURE REQUEST]:

### ISSUE THREAD

**Issue by alraziqij** [dotnet/spark#746]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alraziqij** [comment]
New Brighter World

**Comment by rapoth** [comment]
Hi - Looks like your issue is empty. I am closing this for now. Please feel free to re-open when you fill up the details. Thanks!

**Comment by alraziqij** [comment]
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.

When I can not open my documents

**Comment by alraziqij** [comment]
Open my dock

**Comment by alraziqij** [comment]
Open doc

**Comment by alraziqij** [comment]
Open my story

**Comment by alraziqij** [comment]
My story and students were not given a fighting chance for them to explore, dream and their own new Educational action do we are playing games ok. Yes I am paranoid person you guys know that some see I don't that is still no confirmation sorry￼

**Comment by alraziqij** [comment]
My story
