### ISSUE TITLE
How can. Net for Apache spark connect to MySQL?

### ISSUE THREAD

**Issue by GeorGeWzw** [dotnet/spark#750]
How can. Net for Apache spark connect to MySQL?

**Comment by mwysocki87** [comment]
AFAIK you’ll have to write a thin wrapper around MySQL client JAR-which is the biggest issue stopping me from migrating away from Java...

**Comment by imback82** [comment]
@GeorGeWzw Can you check this thread? https://github.com/dotnet/spark/issues/610#issuecomment-668429774

@mwysocki87 Could you elaborate on the thin wrapper you had to work around?

**Comment by mwysocki87** [comment]
Oh, @imback82, I was under the impression that whenever I want to use some external JAR, I have to write a wrapper around it. If it's not the case, then I stand corrected;)
