### ISSUE TITLE
[Question]: Logging inside UDF function

### ISSUE THREAD

**Issue by fforgoso** [dotnet/spark#755]
Hi.
I'm working on a project where I'm doing several calcs using a UDF function and would like to know how I can log information inside the UDF.
I tried to inject `ILogger<UDFContainerClass>` but I got the serialization error:
`Unhandled exception. System.Runtime.Serialization.SerializationException: Type 'Microsoft.Extensions.Logging.Logger'`
I'm using Microsoft.Spark v0.11.0
Thanks in advance.

**Comment by GoEddie** [comment]
The thing to bear in mind is that UDF's run in a separate process so there is no shared state and your dependency injection code won't have run.

The process is your .NET application runs, calls Apache Spark which starts the separate worker application. The worker application loads your dll and uses reflection to find your method and calls it so no module initialisation or shared state will be available.

I haven't tried but I don't see any reason why you couldn't create your ILogger inside the UDF (have a static ILogger and check if it is null, then initialize or something) using LoggerFactory.

ed

**Comment by fforgoso** [comment]
Thanks @GoEddie. Makes sense. I will give it a try ...

**Comment by Niharikadutta** [comment]
@fforgoso You might find [this article](https://medium.com/hackernoon/how-to-log-in-apache-spark-f4204fad78a) helpful, that sort of illustrates what @GoEddie explained, in Scala.

**Comment by fforgoso** [comment]
Works like a charm! Thanks again @GoEddie and @Niharikadutta!
