### ISSUE TITLE
I can't iterate in DataFrame

### ISSUE THREAD

**Issue by sergiodelossantosjr** [dotnet/spark#763]
Hi Guys,

Please help on this, why I cant iterate in DataFrame?
Below is my screenshot:
![image](https://user-images.githubusercontent.com/22256389/97773211-e2d45300-1b88-11eb-9b5c-2bed8d72d1d2.png)

**Comment by GoEddie** [comment]
"Unsupported class file major version" normally means you have the incorrect Java VM version. If you have Apache Spark 3.0 then you can use a Java 8 or 11, if you are using an older version then you will need Java version 8.

**Comment by sergiodelossantosjr** [comment]
> "Unsupported class file major version" normally means you have the incorrect Java VM version. If you have Apache Spark 3.0 then you can use a Java 8 or 11, if you are using an older version then you will need Java version 8.

Thank you @GoEddie for your help, you're right its my version of Spark has the issue so I upgraded it to Spark 3.0 and its work now 👍
