### ISSUE TITLE
[BUG]: Set Jar failed on Azure Databricks

### ISSUE THREAD

**Issue by artyomtserashkovich** [dotnet/spark#767]
**Describe the bug**
Databrick's job which was set up by set jar is failing during executions. Otherwise, the job which was set up by spark-submit with similar parameters is executing successfully.  In both scenarios, the cluster was set up with the same init script and the same dotnet spark app was used (Word Count from examples).

**To Reproduce**
Spark Version: 5.5 LTS (includes Apache Spark 2.4.3, Scala 2.11)
Microsoft.Spark package version: 1.0.0
Spark Dotnet App verions: <TargetFramework>netcoreapp3.1</TargetFramework>
jar file: microsoft-spark-2-4_2.11-1.0.0

Jobs and Clusters settings:

Spark-submit arg:
`[`
`    "--class",`
`    "org.apache.spark.deploy.dotnet.DotnetRunner",`
`    // microsoft-spark-2-4_2.11-1.0.0.jar was renamed to dotnetWorker.jar during upload`
`    "/dbfs/FileStore/shared_uploads/test/dotnetWorker.jar",`
`    "/dbfs/FileStore/shared_uploads/test/SparkExample.zip",`
`    "SparkExample",`
`    "FileStore/shared_uploads/test/test.txt"`
`]`

Set Jar arg:

`    Main Class: org.apache.spark.deploy.dotnet.DotnetRunner`
`    Arguments: /dbfs/FileStore/shared_uploads/test/SparkExample.zip SparkExample FileStore/shared_uploads/test/test.txt`

Spark-submit cluster json:
`{
    "autoscale": {
        "min_workers": 2,
        "max_workers": 4
    },
    "spark_version": "5.5.x-scala2.11",
    "spark_conf": {},
    "azure_attributes": {
        "first_on_demand": 0,
        "availability": "ON_DEMAND_AZURE",
        "spot_bid_max_price": -1
    },
    "node_type_id": "Standard_DS3_v2",
    "ssh_public_keys": [],
    "custom_tags": {},
    "spark_env_vars": {
        "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
    },
    "enable_elastic_disk": true,
    "cluster_source": "JOB",
    "init_scripts": [
        {
            "dbfs": {
                "destination": "dbfs:/FileStore/shared_uploads/test/install_dotnet_worker.sh"
            }
        }
    ]
}`

Set Jar cluster json:
`{
    "autoscale": {
        "min_workers": 2,
        "max_workers": 8
    },
    "cluster_name": "Test",
    "spark_version": "5.5.x-scala2.11",
    "spark_conf": {},
    "node_type_id": "Standard_DS3_v2",
    "driver_node_type_id": "Standard_DS3_v2",
    "ssh_public_keys": [],
    "custom_tags": {},
    "spark_env_vars": {
        "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
    },
    "autotermination_minutes": 30,
    "enable_elastic_disk": true,
    "cluster_source": "API",
    "init_scripts": [
        {
            "dbfs": {
                "destination": "dbfs:/FileStore/shared_uploads/test/install_dotnet_worker.sh"
            }
        }
    ],
    "cluster_id": ""
}`

**Expected behavior**
Set Jar job has to executed successfully as spark-submit job.

**Additional information**
Logs from Driver-Logs of Set Jar Job:

[Standard output ](https://gist.githubusercontent.com/ArtemTereshkovich/c511f4a953f575999d363b08aff3b520/raw/53b820b367be909f05b1187277309097f4048ff1/SetJarJob-Databricks-StandardOutput.txt)

[Standard error ](https://gist.githubusercontent.com/ArtemTereshkovich/290e079698a53d6118c9460d01792850/raw/1eff07534b7b37b82ac140504bbf6450941bd2d4/SetJarJob-Databricks-StandardError.txt)

[Log4j output ](https://gist.githubusercontent.com/ArtemTereshkovich/18e2081ea2f156919ae720d487ba7c99/raw/4806bbd41b29e9e440467ae20afd3c799d5512a6/SetJarJob-Databricks-log4j.txt)

**Comment by Niharikadutta** [comment]
According to the logs, looks like it is failing because of the R interpreter not starting:

`
ERROR RShell: Failed to evaluate init script at path '/local_disk0/tmp/_CleanRShell.r7367937823248128280resource.r'
20/11/05 08:23:05 ERROR RDriverLocal: Starting R interpreter failed.
`
What is this job doing? Also are you submitting the exact job through `spark-submit` and it always succeeds? How many times has it failed when submitting through 'Set jar'?

**Comment by ArtemTereshkovich** [comment]
> According to the logs, looks like it is failing because of the R interpreter not starting:
> 
> `ERROR RShell: Failed to evaluate init script at path '/local_disk0/tmp/_CleanRShell.r7367937823248128280resource.r' 20/11/05 08:23:05 ERROR RDriverLocal: Starting R interpreter failed.`
> What is this job doing? Also are you submitting the exact job through `spark-submit` and it always succeeds? How many times has it failed when submitting through 'Set jar'?

I use the same example from [Get-Started topic](https://docs.microsoft.com/en-us/dotnet/spark/tutorials/get-started?tabs=windows#3-write-your-app) for `spark-submit` and `set jar` with the same args. `spark-submit` always succeeds but `set jar` failed every time.

**Comment by Niharikadutta** [comment]
Got it, let me try to reproduce this and get back to you.

**Comment by artyomtserashkovich** [comment]
The issue is resolved. Didn't notice that `SparkSession.Stop()` can't be invoked with `SetJar`.

**Comment by kxs-btran** [comment]
Hi @artsiomtserashkovich, I ran into the same problem today and found this thread. Just want to ask how did you solve the issue? Did you just simply remove SparkSession.Stop()?

Any help would be appreciated :D Thank you!
