### ISSUE TITLE
Apache Sedona with Spark .NET

### ISSUE THREAD

**Issue by luciantimar** [dotnet/spark#771]
I'm new to Spark and might be the case that my question to be trivial but is there any possibility to use Apache Sedona with Spark .NET. 
I know the Spark SQL could be used to make the queries with Spark .NET but I don't know how to register the GeoSparkSQL/Sedona.
Than you.

**Comment by imback82** [comment]
@luciantimar I am not familiar with Apache Sedona, but it seems possible to use Sedona with Spark .NET; you many need to expose some Sedona specific classes in .NET. Can you share a specific scenario where we can help (sharing logs where integration doesn't work, etc.)?

**Comment by luciantimar** [comment]
Hi, 
I'm not familiar with Apache Sedona too, but I investigate the possibility to use it for its spatial data features. 
Frankly, I'm new to Spark too but I have to use .NET in projects, and Spark .NET is a very good candidate.
And I have no idea where to start. 

Based on their tutorial 
http://sedona.apache.org/tutorial/sql/

To initiate Spark context
```
var sparkSession = SparkSession.builder()
.AppName("appName") // 
// Enable GeoSpark custom Kryo serializer
in their spamples 
.config("spark.serializer", classOf[KryoSerializer].getName)  //
// this migh be replacable with  .Config("spark.serializer",  "org.apache.spark.serializer.KryoSerializer")
// but the next line I have o ideea  ??
.Config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
.GetOrCreate()
```

but then I have to register Register GeoSparkSQL , 
`GeoSparkSQLRegistrator.registerAll(sparkSession)` 

We suggested that I might have to expose Sedona, specific classes. 
Do you mean to expose the above method call similar to what they did for python?
https://github.com/apache/incubator-sedona/blob/master/python/sedona/register/geo_registrator.py

and then call it from .NET code?

// then load data 
```
var rawDf = sparkSession.Read().Format("csv").Option("delimiter", "\t").Option("header", "false").Load("/Download/usa-county.tsv")
rawDf.CreateOrReplaceTempView("rawdf")
rawDf.Show()

var spatialDf = sparkSession.Sql(
  """
    |SELECT ST_GeomFromWKT(_c0) AS countyshape, _c1, _c2
    |FROM rawdf
  """.stripMargin)
spatialDf.CreateOrReplaceTempView("spatialdf")
spatialDf.Show()

```
Then, porbably, I have to do a spark-submit with  --packages org.datasyslab:geospark:1.2.0,org.datasyslab:geospark-sql_2.3:1.2.0,org.datasyslab:geospark-viz_2.3:1.2.0

Any help or guidance is appreciated.

Lucian

**Comment by imback82** [comment]
> Do you mean to expose the above method call similar to what they did for python?

Yes. You can check out this repo how the bindings are done: (e.g., https://github.com/dotnet/spark/blob/master/src/csharp/Microsoft.Spark/Sql/SparkSession.cs)

You need to access internal classes if you are developing outside this project, so this will help: https://github.com/aelij/IgnoresAccessChecksToGenerator

**Comment by luciantimar** [comment]
Thank you for your information.
I will give it a try to see how it works.
If I will not manage it I will come back with new questions.
 
Thank you.
