### ISSUE TITLE
[QUESTION]: Using appSettings.json with Azure Databricks job

### ISSUE THREAD

**Issue by this-fifo** [dotnet/spark#782]
Hey, I am using an `appSettings.json` configuration file like this in my .NET Core project

```csharp
var configuration = new ConfigurationBuilder()
                .SetBasePath(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location))
                .AddJsonFile("appSettings.json", false, true)
                .AddEnvironmentVariables()
                .Build();
```

And I have the following in my `.csproj`

```xml
<None Include="appSettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        <CopyToPublishDirectory>Always</CopyToPublishDirectory>
</None>
```

This works fine running locally through `spark-submit`

Now I have tried following the Databricks deployment tutorial and have used the Set Jar option when configuring a new job using the `publish.zip` generated from `dotnet publish -c Release -f netcoreapp3.1 -r ubuntu.16.04-x64` which contains my `appSettings.json` file along with the `.dll` files etc.

When trying to run this in Databricks I am getting the following error:

```
Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appSettings.json' was not found and is not optional. The physical path is '/databricks/driver/appSettings.json'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
```

How can I configure Databricks so that it finds the file? The guides mention to include dependencies inside `db-init.sh` but I am a bit unclear of how to do that, any help is much appreciated. Thank you!

**Comment by elvaliuliuliu** [comment]
@this-fifo Can you try using [Databricks CLI](https://docs.databricks.com/dev-tools/cli/index.html) to upload files to the required location mentioned in the error message? Similar to step 2 in Publishing your App & Running section described [here](https://github.com/dotnet/spark/tree/master/deployment#run-your-app-on-the-cloud-2)

**Comment by this-fifo** [comment]
@elvaliuliuliu thank you for the quick reply!

I was able to make it work past that step just now by simply removing the attempt to locate the file and use the absolute path since it gets copied over to the `publish.zip`

what I basically did was comment that line to test just now and it worked

```csharp
var configuration = new ConfigurationBuilder()
                // .SetBasePath(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location))
                .AddJsonFile("appSettings.json", false, true)
                .AddEnvironmentVariables()
                .Build();
```

I agree this doesn't seem elegant tho, might be nicer to think of a way to include that file using the databricks cli

I would love to try that but I am not sure where to upload that file to, where would I upload that file so that it relies on `Path.GetDirectoryName(Assembly.GetEntryAssembly().Location)`?

**Comment by elvaliuliuliu** [comment]
@this-fifo  Glad to hear you have a workaround for this issue. I am not so sure but from the error above, it shows the path is `/databricks/driver/appSettings.json`?

**Comment by this-fifo** [comment]
@elvaliuliuliu yes, thank you, it seems that value is the absolute path it is outputting in the error message when it tries to find it, hardcoding it on my project to be that is actually worse then leaving it as just the filename — _having it be the filename makes it so it still works locally but if I use `/databricks/driver/appSettings.json` it won't work locally without manually updating everytime_

I am trying to find a setting that works for dev/staging/prod and that it is CI friendly without too many tweaks!

Curious to why the assembly location is different than the path of where the `publish.zip` files inside the cluster, that would help me solve the mystery of why using `.SetBasePath(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location))` doesn't work in the cluster

**Comment by this-fifo** [comment]
I guess I realize now uploading there would probably make it work with the `Path` function

My concern with using that location is that I don't understand if that is permanent or what controls it, whereas using the root of `publish.zip` keeps things in my control and remove that step

Maybe that's the solution for now?

I still would like to better understand how Databricks handle the executing assembly and why is it separate but I'm fine with the current workaround

Thank you for your help @elvaliuliuliu ! 🙇‍♂️
