### ISSUE TITLE
[BUG]: dotnet-interactive will hang due to deadlock if recursively call Spark Dotnet method

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [dotnet/spark#792]
#### for eaxmple:

we have two csharp notebooks - `Notebook1` and `Notebook2`,

where the content of `Notebook1` is something like below 
```csharp
Notebook.Run('Notebook2');
``` 
and the contnet of `Notebook2` is something like below
```csharp
spark.Range(5).Show();
```

In our java code, we will first initialize a dotnet-interactive instance just like what `livy` does (let's name it `dotnet1`) to run dotnet code from `Notebook1`,

and what the code `Notebook.Run('Notebook2')` does is actually executing something like `JvmBridge.CallConstructor("com.microsoft.spark.notebook.run", "Notebook2")`
,  sparkDotNet will eventually submit related JVM code to `DotnetBackendHandler` to run.

What the  JVM code `com.microsoft.spark.notebook.run("Notebook2")` does is actually initialize another dotnet instance (let's name it `dotnet2`) to run code from `Notebook2`.

Here, `dotnet1` instance is connected to one `DotnetBackendHandler` instance to run the related jvm code `com.microsoft.spark.notebook.run("Notebook2")`, 

`dotnet2` is connnected to another `DotnetBackendHandler` instance to run the related jvm code `spark.range(5).show()`.

However, since  sparkDotnet limit the threadId for `dotnet1` and `dotnet2` both are `1` if run in dotnet-interactive. And in one jvm process, for different `DotnetBackendHandler` instances, the current dotnetbackend code always use standtone threadPool object to maintain the map of threadId and thread, cause the jvm code `spark.range(5).show` has no chance to be executed due to deadlock.

Simplily,  the jvm code `com.microsoft.spark.notebook.run("Notebook2")` will be submit to thread with threadId is `1` to run, while this jvm code will eventuall try to submit another jvm code `spark.range(5).show` to same thread to run, then deadlock happened. And what we see from the `dotnet1` is it hang with no any results return.

**To Reproduce**
For my case, it is actually a corner case, only happened if you recursively initialize dotnet-interactive instances to run sparkdotnet code,  and the jvm code related to one dotnet-interactive is blocked to wait another jvm code submitted by another dotnet-interactive to run finished.   Hard for me to provide a repo way for you, you can just concat me (gayangya@microsoft.com) to have a sync.

**Expected behavior**
instead of hang with no any result, just return the code result to me.

**Comment by Niharikadutta** [comment]
@imback82 Can we close this issue as per #801 ?

**Comment by imback82** [comment]
Fixed by #793.
