### ISSUE TITLE
[BUG]: Memory Leak when running scheduled job using DotnetRunner

### ISSUE THREAD

**Issue by spzSource** [dotnet/spark#799]
**Description**
There is massive memory leak when running scheduled jobs using `org.apache.spark.deploy.dotnet.DotnetRunner`. As a result it causes Spark Driver node crash and restart due to GC overhead or heap size exception.

**To Reproduce**
1. Create simple batch job
  ```cs
public static void Main(string[] args)
{
    var spark = SparkSession
        .Builder()
        .GetOrCreate();
    var dataFrame = spark.Read().Format("delta").Load("/delta/source");

    dataFrame = dataFrame
        .WithColumn("RequestDate", dataFrame.Col("RequestDate").Cast("timestamp"))
        .Filter(dataFrame.Col("RequestDate")
            .Gt(Functions.DateSub(Functions.CurrentTimestamp(), 7)));
    dataFrame
        .Write()
        .Format("delta")
        .Mode(SaveMode.Overwrite)
        .Save("/delta/destination");
}
  ```
_Important note_: delta folders do not contain any data. It doesn't matter for that particular case.

2. Create databricks job definition running by schedule
![image](https://user-images.githubusercontent.com/2921990/102515689-1a4a8080-409f-11eb-917a-7ea58391c03c.png)

3. Wait a few hours and take a look at memory consumption metrics

**Actual Result**

![image](https://user-images.githubusercontent.com/2921990/102515938-5da4ef00-409f-11eb-85b2-248a16628654.png)
Note: memory drops on the graph indicate driver crashes

Heap statistics gathered using `jmap` tool right before driver crash (take a look at `PS Old Generation` metric):
```
Attaching to process ID 2284, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.265-b01

using thread-local object allocation.
Parallel GC with 4 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 0
   MaxHeapFreeRatio         = 100
   MaxHeapSize              = 6564085760 (6260.0MB)
   NewSize                  = 2187853824 (2086.5MB)
   MaxNewSize               = 2187853824 (2086.5MB)
   OldSize                  = 4376231936 (4173.5MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
PS Young Generation
Eden Space:
   capacity = 877133824 (836.5MB)
   used     = 302337464 (288.3314743041992MB)
   free     = 574796360 (548.1685256958008MB)
   34.46879549362812% used
From Space:
   capacity = 479723520 (457.5MB)
   used     = 0 (0.0MB)
   free     = 479723520 (457.5MB)
   0.0% used
To Space:
   capacity = 675807232 (644.5MB)
   used     = 0 (0.0MB)
   free     = 675807232 (644.5MB)
   0.0% used
PS Old Generation
   capacity = 4376231936 (4173.5MB)
   used     = 4375784088 (4173.072898864746MB)
   free     = 447848 (0.42710113525390625MB)
   99.98976635593019% used

47640 interned Strings occupying 5093352 bytes.
```

GC logs:

```
2020-12-16T13:41:51.773+0000: [Full GC (Ergonomics) [PSYoungGen: 1068544K->959362K(1612800K)] [ParOldGen: 4273219K->4273218K(4273664K)] 5341763K->5232581K(5886464K), [Metaspace: 261859K->261859K(1339392K)], 3.8349085 secs] [Times: user=14.02 sys=0.05, real=3.83 secs] 
2020-12-16T13:41:55.904+0000: [Full GC (Ergonomics) [PSYoungGen: 1068544K->967217K(1612800K)] [ParOldGen: 4273218K->4273218K(4273664K)] 5341762K->5240435K(5886464K), [Metaspace: 261859K->261859K(1339392K)], 3.7493484 secs] [Times: user=13.92 sys=0.03, real=3.75 secs] 
2020-12-16T13:41:59.922+0000: [Full GC (Ergonomics) [PSYoungGen: 1068544K->975163K(1612800K)] [ParOldGen: 4273218K->4273218K(4273664K)] 5341762K->5248382K(5886464K), [Metaspace: 261861K->261861K(1339392K)], 3.8089805 secs] [Times: user=14.32 sys=0.03, real=3.80 secs] 
...
```

Analyzing memory dump it's visible that there are a lot of `HashSetEntry` and `string` objects living in Old Gen which never get garbage collected. 
![image](https://user-images.githubusercontent.com/2921990/102511927-6cd56e00-409a-11eb-9cd5-e348095bce53.png)

Going deeper through object graph you can see that `JVMObjectTracker` (which is static class) keeps holding references to SparkContext and hence to aforementioned "rubbish" objects (like query execution plans and datasets) even after `DotnetBackend` stopped.

![image](https://user-images.githubusercontent.com/2921990/102514242-4bc24c80-409d-11eb-9258-c81fd025181f.png)

**Expected behavior**
- Job running by schedule using DotnetRunner must not cause Spark Driver crashes. 
- Memory consumption must not increase over time. Old gen size must be within predicted range.

**Additional context**

Affected versions: 
- microsoft-spark-2-3_2.11
- microsoft-spark-2-4_2.11
- microsoft-spark-3-0_2.12

Unfortunately I cannot attach memory dump here, as it is about 8 GB size.

**Development notes**

I've already done a few experiments with patched version, where `JVMObjectTracker` is cleaned when DotetBacked shutdown. This does help, so after applying the fix the the same job runs smoothly without any memory issues.

If everybody agree that described behavior is a bug, I'll be happy to create PR.

**Comment by imback82** [comment]
@spzSource Thanks for reporting. Could you create a PR with your patch?

So in your scenario, you have `DotnetRunner` always running and submit .NET applications?

**Comment by spzSource** [comment]
> So in your scenario, you have DotnetRunner always running and submit .NET applications?

Hi @imback82 
Yes, `DotnetRunner` spin ups jobs on the same cluster (hence on the same JVM). This is how [SetJar](https://docs.microsoft.com/en-us/dotnet/spark/how-to-guides/databricks-deploy-methods#deploy-using-set-jar) approach in Databricks works. 

Since `JVMObjectTracker` is a singleton by it's nature, it resides in spark driver node throughout the entire life cycle of the node, which leads to memory leak.

I've created PR. Will be happy is somebody take a look.
