### ISSUE TITLE
Spark-Submit --version   unrecognized

### ISSUE THREAD

**Issue by jahansha** [dotnet/spark#813]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by Niharikadutta** [comment]
Hi @jahansha , could you please provide some more information about the command you used and the stacktrace you are seeing?

**Comment by Niharikadutta** [comment]
This has been covered in detail in issues #557 and #304, please go through the steps laid out there and feel free to open an issue if this still persists. Thank you!
