### ISSUE TITLE
Can't get the spark-submit command to work on Windows 10 after installing spark

### ISSUE THREAD

**Issue by briancuster** [dotnet/spark#816]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

I installed spark in accordance with the directions located https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark and am getting the error 'spark-submit' is not recognized as an internal or external command,
operable program or batch file.

**Comment by suhsteve** [comment]
This often means that either your PATH environment variable is not set correctly or you need to open a new terminal/command prompt session.

Please follow the suggested steps in #557 and #304 .
