### ISSUE TITLE
Spark-submit not recognized

### ISSUE THREAD

**Issue by Fabiest** [dotnet/spark#831]
**Describe the bug**
spark-submit' is not recognized as an internal or external command,
operable program or batch file.

**To Reproduce**

I'm following https://dotnet.microsoft.com/learn/data/spark-tutorial/intro and I can not make spark-submit work.

%JAVA_HOME%        => C:\Program Files\Java\jdk1.8.0_281
%SPARK_HOME%      => C:\spark\spark-3.0.1-bin-hadoop2.7
%HADOOP_HOME% => C:\spark\spark-3.0.1-bin-hadoop2.7

**Screenshots**
![image](https://user-images.githubusercontent.com/43171436/110152633-e2b7be80-7dd9-11eb-8a1a-6be7cd0a2242.png)
![image](https://user-images.githubusercontent.com/43171436/110153170-9a4cd080-7dda-11eb-9dcd-5fdb3851f68e.png)
![image](https://user-images.githubusercontent.com/43171436/110153199-a59ffc00-7dda-11eb-8655-2dbc73c45be4.png)
![image](https://user-images.githubusercontent.com/43171436/110153224-ad5fa080-7dda-11eb-9cce-32e92e28097e.png)
![image](https://user-images.githubusercontent.com/43171436/110153251-b81a3580-7dda-11eb-8647-7ddaa8674cc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Niharikadutta** [comment]
This has been covered in detail in issues #557 and #304, please go through the steps laid out there and let us know if it fixes the issue.

**Comment by suhsteve** [comment]
Closing, please reopen if the suggestions in other threads did not resolve your issue.
