### ISSUE TITLE
The default branch will be renamed to main

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#838]
On the week of March 15-19, we're going to rename the default branch in this repository to main. For more details, see [our earlier announcement](https://github.com/dotnet/announcements/issues/172).

The existing PRs will be re-targeted to main automatically.

**Comment by imback82** [comment]
@dotnet/dnceng, the GitHub rename tool isn't enabled for this repo. Could you help?

![image](https://user-images.githubusercontent.com/12103644/111660761-a0c04c80-87cb-11eb-824b-326cc156bdf8.png)

**Comment by premun** [comment]
@imback82 the section on the screenshot looks exactly like the rename one. Or you're saying this is a screenshot from some other repository?

**Comment by imback82** [comment]
@premun Oh, I thought I needed the arrow as shown below?
![image](https://user-images.githubusercontent.com/12103644/111664038-9e132680-87ce-11eb-83fa-003498e4c9e5.png)

**Comment by imback82** [comment]
But looks like the "pencil" button is the rename button.

**Comment by premun** [comment]
Yeah, I think the arrows are missing since you only had 1 branch in the repo. The pencil should do the trick!

**Comment by imback82** [comment]
Thanks @premun!

**Comment by imback82** [comment]
This is now complete.
