### ISSUE TITLE
[FEATURE REQUEST]: Support new Spark 3.1 APIs

### ISSUE THREAD

**Issue by imback82** [dotnet/spark#840]
Once #836 is merged, we can expose APIs introduce in Spark 3.1 for `DataFrame`, `SparkContext`, `Column`, `Catalog`, SQL functions, etc.

Basically you can search for `@since 3.1.0` in the OSS Spark code base to compile the list of new APIs.

**Comment by imback82** [comment]
@Niharikadutta Do you want to work on this?

**Comment by Niharikadutta** [comment]
Yes I'll work on this.
