### ISSUE TITLE
while installing apache spark im getting issue

### ISSUE THREAD

**Issue by sindujacse** [dotnet/spark#841]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: linux

Im getting issue while running this command - ./spark-shell

Error - No such file or directory

**Comment by suhsteve** [comment]
You have to update your PATH to contain the SPARK_HOME\bin path detailed in https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark .  Then you'll need to restart your command prompt to ensure the session has your new env variable settings.

**Comment by suhsteve** [comment]
closing for now.  Feel free to open if this did not solve your error.
