### ISSUE TITLE
run spark-shell and get the error

### ISSUE THREAD

**Issue by nolongeriv** [dotnet/spark#843]
Unable to load native-hadoop library for your platform
![image](https://user-images.githubusercontent.com/11455509/111449814-55159080-8742-11eb-8490-c277c4c689e2.png)

**Comment by imback82** [comment]
This is a naïve warning message and shouldn't affect your job in this case. Please check #481 as well. Closing this for now.

**Comment by robyle** [comment]
so ,anyone know ,how to expect unWarning ?
