### ISSUE TITLE
Issue running spark-submit

### ISSUE THREAD

**Issue by kaoutarlehlous** [dotnet/spark#845]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/intro/run
Operating System: windows

Provide details about the problem you're experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

hello, i have a problem to submit your application to run on Apache Spark to have finally the data written to the console : i get this message as error message :
```
C:\Users\kaout\mySparkApp>spark-submit --class org.apache.spark.deploy.dotnet.DotnetRunner --master local bin\Debug\netcoreapp3.1\microsoft-spark-2-4_2.11-1.0.0.jar dotnet bin\Debug\netcoreapp3.1\mySparkApp.dll

'cmd' n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.
```

**Comment by imback82** [comment]
I updated the title and description.

**Comment by imback82** [comment]
> n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.

Translating this, I get `
is not recognized as an internal or external command, an executable program or a file`.

Please check #557 and #304.

**Comment by suhsteve** [comment]
@kaoutarlehlous I'm going to close this issue,  Please feel free to reopen if the suggestions did not help.
