### ISSUE TITLE
Apache Spark commands are not right

### ISSUE THREAD

**Issue by andreibicu** [dotnet/spark#881]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows 10

The provided commands
- setx HADOOP_HOME C:\bin\spark-3.0.1-bin-hadoop2.7\
- setx SPARK_HOME C:\bin\spark-3.0.1-bin-hadoop2.7\
- setx /M PATH "%PATH%;%HADOOP_HOME%;%SPARK_HOME%\bin"
changed my PATH value to "%PATH%;%HADOOP_HOME%;%SPARK_HOME%\bin"
It removed the previous paths and now some programs are not running anymore.

**Comment by suhsteve** [comment]
@andreibicu Did you use `cmd.exe` or `powershell` to run the commands?  I believe the instructions are meant for `cmd.exe`

**Comment by andreibicu** [comment]
I used Powershell via Windows Terminal.

I solved the problem by reverting the computer to a previous restore point.

However, shouldn't the documentation specify what kind of editor to use? 
This seems pretty important and easy to broke stuff on a computer.

**Comment by suhsteve** [comment]
@andreibicu The page does indicate what to use.  According to the page:

> Open a new **command prompt** in administrator mode and run the following commands to set the environment variables used to locate Apache Spark:

The the commands on the page also have enclosed with a prompt that has title `Command prompt`

In Windows, the "Command Prompt" shortcut in the start menu opens `cmd.exe` as does the "Command Prompt" shortcut in Windows Terminal.

**Comment by andreibicu** [comment]
My bad then.
Thanks for your help.

**Comment by suhsteve** [comment]
@andreibicu sorry you ran into problems and I'm glad you were able to resolve it.  I'll close this issue as it is resolved.  Feel free to reopen if you think it wasn't.
