### ISSUE TITLE
Display spark version with .Version() on SparkContext?

### ISSUE THREAD

**Issue by alvaromuir** [dotnet/spark#913]
Typically, the current version of Spark is available by calling .version on the sparkContext.

Any thoughts of how to get that here? Needed because there are times when using the lib in a notebook or some other interactive way it's good to check the version first.

**Comment by imback82** [comment]
Thanks @alvaromuir for reporting this. Currently, we don't expose the `def version`, but I think we should. Do you want to contribute? Otherwise, I can take this up.

**Comment by alvaromuir** [comment]
I'm on it.
