### ISSUE TITLE
[FEATURE REQUEST]: Expose Spark Version info to users

### ISSUE THREAD

**Issue by alvaromuir** [dotnet/spark#918]
**Is your feature request related to a problem? Please describe.**
Expose `Spark Version` to users

**Describe the solution you'd like**
Return the Spark `Version` when called. As typically expected on sparkContext.version() or sparkSession.version()

**Describe alternatives you've considered**
Have checked all avail methods and work arounds not there today.

**Additional context**

**Comment by suhsteve** [comment]
@alvaromuir can you update the title ?

**Comment by alvaromuir** [comment]
> @alvaromuir can you update the title ? Or maybe we can combine this with #913 ?

We should combine. I'll close #913

**Comment by imback82** [comment]
Fixed by #919
