### ISSUE TITLE
 'spark-submit' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mdharmpurikar** [dotnet/spark#924]
Problem encountered on https://dotnet.microsoft.com/learn/data/spark-tutorial/install-spark
Operating System: windows

I followed each and every step as provided in the document but getting below error.

Problem :  'spark-submit' is not recognized as an internal or external command
OS - Windows 10
Error Message -  'spark-submit' is not recognized as an internal or external command

**Comment by Niharikadutta** [comment]
Please refer to #557 and #304 and feel free to reopen the issue if that doesn't solve your problem. Thanks!
