### ISSUE TITLE
[FEATURE REQUEST]: Not able to use Structured steaming over Azure EventHub

### ISSUE THREAD

**Issue by guruvonline** [dotnet/spark#940]
**Is your feature request related to a problem? Please describe.**
I have to upgrade the version of EventHub for Spark, the latest version of library i have to specify the connection string of EventHub as encrypted. which is not supported in .NET for Spark.

https://github.com/Azure/azure-event-hubs-spark/issues/510
thread  talks about issue and possible workaround of using .NET for spark internal API. can there be public API to access eventHub.

**Comment by suhsteve** [comment]
Please see related issue #933
