### ISSUE TITLE
spark-submit command does not work after installation still says The system cannot find the path specified

### ISSUE THREAD

**Issue by timrobert777** [dotnet/spark#966]
Hello,
I installed java, Spark, Python(Python39) and also set environment variables and the paths, how ever it is still says. I tried different suggestion on #304, #496,  #523 and other issues but no luck

C:\>echo %JAVA_HOME%
C:\java\jdk1.8.0_201

C:\=>echo %SPARK_HOME%
C:\bigdata\Spark\spark-3.1.2-bin-hadoop2.7

C:\>echo %HADOOP_HOME%
C:\bigdata\Hadoop

C:\>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\java\jdk1.8.0_301\bin;C:\Python\Python39\;C:\bigdata\Spark\spark-3.1.2-bin-hadoop2.7\bin;C:\bigdata\Hadoop\bin;C:\Users\abdul\AppData\Local\Microsoft\WindowsApps;C:\java\jdk1.8.0_301\bin;C:\Python\Python39\;C:\bigdata\Spark\spark-3.1.2-bin-hadoop2.7\bin;C:\bigdata\Hadoop\bin;

C:\>%SPARK_HOME%/bin/spark-submit --version
The system cannot find the path specified.

**Comment by suhsteve** [comment]
@timrobert777  in that same command prompt session can you type `java -version` and see if that works ?

**Comment by timrobert777** [comment]
Thank you so much Steve a quick response.
Yeah java version shows up correctly.
C:\>java -version
java version "1.8.0_301"
Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.301-b09, mixed mode)

C:\>

**Comment by suhsteve** [comment]
your version returned by that says 1.8.0_**301** .  However your %JAVA_HOME% is set to C:\java\jdk1.8.0_**201**

Seems like an inconsistency that should be fixed.

**Comment by timrobert777** [comment]
Awesome Steve, I corrected it and it worked. 
Appreciate you time and for a very quick solution. Kudos to @suhsteve
