### ISSUE TITLE
Parameterized method chaining with DataFrame.Transform

### ISSUE THREAD

**Issue by rrekapalli** [dotnet/spark#998]
Hi Team:

Could someone help me/point me to an example on how I can implement method chaining with a parameter as shown in the below scala example?  
Please note the string parameter ("name") in the below example.

[https://mungingdata.com/apache-spark/chaining-custom-dataframe-transformations/](url)

`def withCat(name: String)(df: DataFrame): DataFrame = {
  df.withColumn("cats", lit(s"$name meow"))
}

val df = Seq(
  "funny",
  "person"
).toDF("something")

val niceDf = df
  .transform(withCat("puffy"))
`

Thanks

**Comment by GoEddie** [comment]
I think what you see in this sample is some of the "scala magic" but you can recreate something similar like:

```csharp
using System;
using Microsoft.Spark.Sql;
using static Microsoft.Spark.Sql.Functions;

namespace TransformFun
{
    class Program
    {
        static void Main(string[] args)
        {
            Func<DataFrame, DataFrame> WithCat(string name)
            {
                return frame => frame.WithColumn("greeting", Lit($"{name} meow"));
            }
            
            var spark = SparkSession.Builder().GetOrCreate();
            var df = spark.CreateDataFrame(new string[] {"funny", "person"}).ToDF("something");
            var withCat = WithCat("kitty");
            var weirdDf = df.Transform(withCat);
            weirdDf.Show();
        }
    }
}
```

Which outputs:

```
+---------+----------+
|something|  greeting|
+---------+----------+
|    funny|kitty meow|
|   person|kitty meow|
+---------+----------+
```

**Comment by rrekapalli** [comment]
Hi Ed,
Thank you very much for the suggestion!  This has been very helpful while implementing some data transformations through method chaining in our project.  Much appreciate your help!

**Comment by GoEddie** [comment]
Hi @rrekapalli ,

Do you need anything else? If not can you close it?

Ed

**Comment by rrekapalli** [comment]
Hi Ed, The above solution worked for me and closing the issue.  Thanks so much for your help!
